### ISSUE TITLE
Failed to find function “__sanitizer_print_stack_trace”

### ISSUE THREAD

**Issue by RosenZhu** [google/fuzzbench#1001]
I forked a new branch to run experiments, and I `git merge upstream/master` very recently. When I use `PYTHONPATH=. python3 experiment/run_experiment.py ...` to run local experiments, the following errors occur:
```
crashes/timeout-ae3bb5cf4d69728fcf01c46df3d926925c8f1b7a\n
Base64: YzovJy8vLy8vAC8vL5YA\n
==13528== ERROR: libFuzzer: timeout after 11 seconds\n
SUMMARY: libFuzzer: timeout\n
MERGE-OUTER: attempt 33\nWARNING: Failed to find function "__sanitizer_acquire_crash_state".\n
WARNING: Failed to find function "__sanitizer_print_stack_trace".\n
WARNING: Failed to find function "__sanitizer_set_death_callback".\n
INFO: Seed: 2435031264\n
INFO: -max_len is not provided; libFuzzer will not generate inputs larger than 1048576 bytes\n
MERGE-INNER: using the control file \'/tmp/libFuzzerTemp.11602.txt\'\n
```
I notice that there's already an issue about this error: [issue809](https://github.com/google/fuzzbench/issues/809#issue-718762047). 

I also get some warnings:
```
/usr/local/lib/python3.8/site-packages/clusterfuzz/stacktraces/constants.py:75:
 FutureWarning: Possible nested set at position 4
  CHROME_CHECK_FAILURE_REGEX = re.compile(
/usr/local/lib/python3.8/site-packages/clusterfuzz/stacktraces/constants.py:200:
 FutureWarning: Possible nested set at position 3
  SECURITY_CHECK_FAILURE_REGEX = re.compile(
/usr/local/lib/python3.8/site-packages/clusterfuzz/stacktraces/constants.py:202: 
FutureWarning: Possible nested set at position 3
  SECURITY_DCHECK_FAILURE_REGEX = re.compile(
```
Does this indicate that the experiments are wrongly performed? Or the results of experiments are right, but there are some problems during measuring the experiments (after the experiments are done)?

**Comment by RosenZhu** [comment]
Meanwhile, I found that the folder "crashes" is not under the folder "trial-#/corpus/", but moved to the folder "trial-#/". Is that right?

**Comment by inferno-chromium** [comment]
c#0, those are all safe warnings. clusterfuzz pypi needs update for the second set of python warnings and will be updated in new year. first set of warning are only concerning if you use bug based benchmarking and are not seeing valid crashes in crash_key column in data.csv.gz created in fuzzbench-data dir.

c#1, yes that is expected, crashes are now in its own directory. if you see any incorrect doc, would appreciate a PR fix.

**Comment by RosenZhu** [comment]
Thanks for your time!
