### ISSUE TITLE
bug benchmark issues

### ISSUE THREAD

**Issue by vanhauser-thc** [google/fuzzbench#1003]
When I look at https://www.fuzzbench.com/reports/2020-12-19-bug/index.html I see that honggfuzz and entropic are pretty bad.

When I then look at the afl++ variant test on the bug benchmark https://www.fuzzbench.com/reports/experimental/2020-12-22-bug/index.html (settings are as follows: aflplusplus=cmplog+autodictionary, aflplusplus_optimal=cmplog, aflplusplus_bug_dict=autodictionary, aflplusplus_bug_laf=laf) it shows that cmplog/redqueen makes the results much worse and not better - although in coverage it is the best feature by far.

So putting these two observations together - it seems that the bugs in the targets are very, very shallow. hence not very good fuzzers explore all these paths there and therefore have many finds, while the good fuzzers (honggfuzz, entropic, aff++) concentrate on new, long and interesting paths were no bugs are and therefore find much less.

I am not sure that the current bug benchmarks are a good choice and therefore lead to very wrong benchmark results - very biased ones.
(I can make aflplusplus_optimal being the top winner by far by just adding a single line to fuzzer.py - but that is not the point, and that would not help entropic and honggfuzz)

**Comment by andreafioraldi** [comment]
All these bug were found by fuzzing?

**Comment by inferno-chromium** [comment]
These benchmarks are coming from OSS-Fuzz repos at certain commits (benchmark integration by @Vaush). This is just initial work and we got the fuzzbench functionality working last week. We need to work together to improve+expand list of bug based benchmarks in January (ideas welcome, see also https://google.github.io/fuzzbench/developing-fuzzbench/adding-a-new-benchmark/#oss-fuzz-benchmarks). As i was talking with @lszekeres , we need a mix of both benchmarks with many bugs (for statistical analysis) and some with deep bugs. Right now, i do agree many of them hit too soon (e.g. arrow, harfbuzz_hb-subset-fuzzer), but arent some of them ok, like openh264_decoder_fuzzer and php_php-fuzz-execute.

**Comment by vanhauser-thc** [comment]
It looks like the 2 php ones are deeper plus openexr.
no fuzzer so far finds bugs in either libhevc or matio, so maybe these should be disabled for the time being.
maybe adding about 4-5 targets that have deeper bugs, and then this could be good I think.

**Comment by inferno-chromium** [comment]
> It looks like the 2 php ones are deeper plus openexr.
> no fuzzer so far finds bugs in either libhevc or matio, so maybe these should be disabled for the time being.
> maybe adding about 4-5 targets that have deeper bugs, and then this could be good I think.

Actually some fuzzer do find 1-2 bugs in some trials for libhevc and matio [so it is interesting result], it can be seen if you expand that table [since graph is statistical mean :( across all trials]

![4MgTnDnruJWKydA](https://user-images.githubusercontent.com/8731250/103035411-2067b380-451c-11eb-9f84-87b8d56da196.png)

**Comment by inferno-chromium** [comment]
And yes, we will significantly expand bug based benchmark list in January, ideas welcome on any oss-fuzz targets you are interested in OR remember seeing interesting bugs while improving fuzzing engines.

**Comment by vanhauser-thc** [comment]
I ran a bug benchmark with two fuzzers: aflplusplus without cmplog vs aflplusplus with cmplog -> https://www.fuzzbench.com/reports/experimental/2020-12-29-bug/index.html

afl++ with cmplog is only able to achieve the same bug count on 3 targets, 2 were none finds anything and 4 where it is the looser by far.

it seems that the only target with deep bugs is matio - there cmplog is able to find bugs, however too rarely.

I think this is an overall issue. so that a bug is deep it takes a long time to fuzz out that path, and the experiment time is too short. hence shallow fuzzers (or better, those that are not good at solving path constraints) will always be better in bug benchmarks - unless the run time is increased.

**Comment by jonathanmetzman** [comment]
Thanks for this feedback. It is interesting to consider if the method we used for picking benchmarks is biased towards a certain style of fuzzing that isn't helpful in the real world. I'll see if I can think of something better.

**Comment by vanhauser-thc** [comment]
I would not say "not real world" - I mean the bugs were found with existing fuzzer.
however the bugs might not be "new", hence from a time where the introspection wasn't that great. with LAF, cmplog, eclipser it is now possible to reach parts in the source code that were previously not possible to solve. I am unsure if you use any of these three mechanisms in oss-fuzz so far. adding these would make the coverage jump on all targets.

**Comment by Vaush** [comment]
It's kind of a difficult situation in general. The original idea was to have some benchmarks with known bugs, found by other fuzzers (so we knew that the fuzzers could in principle find the bugs), and use the known bugs as ground truth. This way, accounting for the fact that fuzzers could also find new bugs not in the original ground truth, we would be able to rate new fuzzers on a fixed benchmark and try to rank them objectively.

Of course, there are downsides to this, mainly the fact that the only real world, feasible benchmarks available were those in OSS-Fuzz, and thus the bugs were all found by libfuzzer/afl. This causes all sorts of problems, among those the fact that afl/libfuzzer have an advantage.

I totally see your point in saying that the benchmarks we have probably favour shallow bugs, but at the same time I haven't been able to find a criterion to use in choosing other benchmarks which might have better distributed, already known bugs.

**Comment by Vaush** [comment]
Even if we wanted to drop the idea of using real world bugs, there is still a problem of how to choose programs we know are buggy in a well distributed way, in order to have good benchmarks.

**Comment by vanhauser-thc** [comment]
closing this for now, will open a new one if I think this issue is still present with the new bug targets
