### ISSUE TITLE
Benchmarks getting stuck

### ISSUE THREAD

**Issue by vanhauser-thc** [google/fuzzbench#1008]
The current and last benchmark runs are not completing ... they are stuck at 12:15 or 7:30 respectively.

the https://www.fuzzbench.com/reports/experimental/2020-12-26/index.html is not important (and clearly shows already at 12:15 was I expected)

however https://www.fuzzbench.com/reports/experimental/2020-12-28/index.html is important.

maybe its just the reporting that stops working?

**Comment by inferno-chromium** [comment]
Yes regression cl is reverted, will restart experiments in 2020-12-29*
