### ISSUE TITLE
CI build env != prod build env

### ISSUE THREAD

**Issue by vanhauser-thc** [google/fuzzbench#1011]
aflplusplus_optimal and aflplusplus_eclipser fail in the CI when starting afl-fuzz with segmentation faults.
However when running them locally or in a benchmark run in prod they run fine.
Hence the CI build environment seems to be different to the prod environment.
My guess it's an OOM issue - less memory available in CI?

**Comment by inferno-chromium** [comment]
fixed in https://github.com/google/fuzzbench/pull/1083
eclipser sometimes ooms with 137 exit code. but that is a legit 7 gb exceed.
