### ISSUE TITLE
Benchmarks getting stuck (again)

### ISSUE THREAD

**Issue by vanhauser-thc** [google/fuzzbench#1016]
the benchmark run started yesterday does not progess anymore since it reached 1:30h - and that was about 12 hours ago.
https://www.fuzzbench.com/reports/experimental/2021-01-05-aflpp/index.html

a reoccurring #1008 maybe.

**Comment by inferno-chromium** [comment]
Really sorry about this. @lszekeres - i will revert this again, but wont reland until you can investigate what is going on.

**Comment by inferno-chromium** [comment]
@vanhauser-thc - sorry about this, we wont reland this until @lszekeres can investigate with prior experiments. Can you please re-request this experiment.

**Comment by inferno-chromium** [comment]
@vanhauser-thc - i restarted experiment as 2021-01-06-aflpp

**Comment by inferno-chromium** [comment]
https://www.fuzzbench.com/reports/experimental/2021-01-06-aflpp/index.html is the link
