### ISSUE TITLE
Plot error when generating report

### ISSUE THREAD

**Issue by Hanjun-Dai** [google/fuzzbench#102]
Hi there, 

I was trying to run the `experiment/generate_report.py` after experiment. 

However I received the error saying: 
"No axis named columns for object type <class 'pandas.core.series.Series'>"
which is triggered by [this line](https://github.com/google/fuzzbench/blob/master/analysis/data_utils.py#L239).

To reproduce this error, here is the script that I used:

```
#!/bin/bash

EXPERIMENT_NAME=testrun

PYTHONPATH=. python3 experiment/generate_report.py \
    experiments $EXPERIMENT_NAME \
    --quick \
    -c \
    --fuzzers afl libfuzzer \
    --report-dir ${EXPERIMENT_NAME}_report
```
And here is the raw data file:

[data.csv.gz](https://github.com/google/fuzzbench/files/4321470/data.csv.gz)

One should be able to reproduce the error using the script above.

**Comment by jonathanmetzman** [comment]
OK I was able to reproduce this.

**Comment by jonathanmetzman** [comment]
Laszlo, do you think you could take a look since you know the graphing code better?
i'll see what I can figure out in the meantime.

**Comment by jonathanmetzman** [comment]
I think changing the line `pivot_df = groups_ranked if num_benchmarks == 1 else groups_ranked.unstack()` to `pivot_df = groups_ranked if num_benchmarks <= 2 else groups_ranked.unstack()`
causes this exception to go away but I'm not sure if the fix affects correctness.

**Comment by lszekeres** [comment]
Thanks @Hanjun-Dai for the report, and thanks @jonathanmetzman for debugging! 
Fixed in https://github.com/google/fuzzbench/pull/104.

**Comment by Hanjun-Dai** [comment]
Greta, thanks!
