### ISSUE TITLE
Coverage is broken for benchmarks using trunk base-builder

### ISSUE THREAD

**Issue by inferno-chromium** [google/fuzzbench#1044]
```
Traceback (most recent call last):
  File "/work/src/experiment/measurer/measure_manager.py", line 405, in get_current_coverage
    coverage_info = coverage_utils.get_coverage_infomation(
  File "/work/src/experiment/measurer/coverage_utils.py", line 229, in get_coverage_infomation
    return json.loads(summary.readlines()[-1])
  File "/usr/local/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
"
```

E.g.
https://github.com/google/fuzzbench/blob/master/benchmarks/libjpeg-turbo-07-2017/Dockerfile#L17

See https://www.fuzzbench.com/reports/experimental/2021-01-18-aflpp/index.html#libxml2-v2.9.2

**Comment by wideglide** [comment]
I tried a local experiment and wonder if this was just a problem with local experiments.  I guess not.  I found two cases where this happens.  There could be more?

1. the first line is a warning
```
root@66a82d41a4a2:/work# head -n1 './measurement-folders/bloaty_fuzz_target-afl/trial-6/reports/cov_summary.json'
warning: 7 functions have mismatched data
```

2. "Unsupported coverage format version"
```
cat measurement-folders/freetype2-2017-libfuzzer/trial-13/reports/cov_summary.json
error: /work/coverage-binaries/freetype2-2017/ftfuzzer: Failed to load coverage: Unsupported coverage format version
error: Could not load coverage information
```

**Comment by inferno-chromium** [comment]
> I tried a local experiment and wonder if this was just a problem with local experiments. I guess not. I found two cases where this happens. There could be more?
> 
> 1. the first line is a warning
> 
> ```
> root@66a82d41a4a2:/work# head -n1 './measurement-folders/bloaty_fuzz_target-afl/trial-6/reports/cov_summary.json'
> warning: 7 functions have mismatched data
> ```

this one is harmless.

> 
> 1. "Unsupported coverage format version"
> 
> ```
> cat measurement-folders/freetype2-2017-libfuzzer/trial-13/reports/cov_summary.json
> error: /work/coverage-binaries/freetype2-2017/ftfuzzer: Failed to load coverage: Unsupported coverage format version
> error: Could not load coverage information
> ```

does not happen in current experiment, but i remember seeing this wrong llvm-cov version is used.

**Comment by inferno-chromium** [comment]
Not happening anymore, maybe some issue with trunk clang that is now fixed.
Both https://www.fuzzbench.com/reports/experimental/2021-01-20-aflpp/index.html and https://www.fuzzbench.com/reports/experimental/2021-01-19-aflpp/index.html going ok
@vanhauser-thc fyi
