### ISSUE TITLE
The change of experiment-config.yaml doesn't work

### ISSUE THREAD

**Issue by RosenZhu** [google/fuzzbench#1050]
I'm trying to enable `make debug ...` to mount a volume like this:
In generate_makefile.py, I change
```
if run_type == 'debug':
            section += '\t--entrypoint "/bin/bash" \\\n\t-it '
```
to 
```
if run_type == 'debug':
            section += f'\t-v {crash_plot_folders}:/data \\\n\t'
            section += '--rm \\\n\t'
            section += '--entrypoint /out/getbugs.sh '
```
where `{crash_plot_folders}` is got in:
```
def _get_makefile_run_template(image):
    # get the folder including crash test cases and files plot_data
    experiment_config = yaml_utils.read('experiment-config.yaml')
    crash_plot_folders = experiment_config['crash_plotdata_filestore']
    ...
```
The problem is, when I change the attribute `crash_plotdata_filestore` in `experiment-config.yaml`, it doesn't change in the command `sudo docker run ... -v crash_plot_folders:/data ...`. The `crash_plot_folders` is still the old one.
I tried to stage the changes of `experiment-config.yaml`, remove docker images, remove docker containers, and clear building cache, but it still doesn't change.

How can I change the `crash_plot_folders` according to file `experiment-config.yaml`?
BTW, it only works for the first time after I edit the file generate_makefile.py.

**Comment by inferno-chromium** [comment]
You need to delete `docker/generated.mk`. that is an auto-generated file that i think only changes when generation file changes (not dependent on experiment-config and does not account for your custom patch).

**Comment by RosenZhu** [comment]
Thanks, it works.
