### ISSUE TITLE
SyntaxError: invalid syntax: corpus_archive_filename = f'{benchmark}.zip'

### ISSUE THREAD

**Issue by vanhauser-thc** [google/fuzzbench#1059]
I am try to add symqemu to fuzzbench, and it is quite a long and frustrating ride ... but I am very close now.

At the final step I am experiencing a weird error, that does not come up with other fuzzers:

```
docker run \
--cpus=1 \
--cap-add SYS_NICE \
--cap-add SYS_PTRACE \
-e FUZZ_OUTSIDE_EXPERIMENT=1 \
-e FORCE_LOCAL=1 \
-e TRIAL_ID=1 \
-e FUZZER=aflplusplus_symqemu \
-e BENCHMARK=re2-2014-12-09 \
-e FUZZ_TARGET=fuzzer \
-e MAX_TOTAL_TIME=20 \
-e SNAPSHOT_PERIOD=10 \
gcr.io/fuzzbench/runners/aflplusplus_symqemu/re2-2014-12-09
  File "/src/experiment/runner.py", line 126
    corpus_archive_filename = f'{benchmark}.zip'
                                               ^
SyntaxError: invalid syntax
make: *** [docker/generated.mk:35284: test-run-aflplusplus_symqemu-re2-2014-12-09] Error 1
```
that runner.py is exactly the same file as in other working runners.
I hope someone has seen this error before and has a clue why this is happening :(

Regards,
Marc

**Comment by jonathanmetzman** [comment]
I haven't seen this but it almost certainly has to do with the wrong python version being used.
f-strings were added in Python3.6: https://www.python.org/dev/peps/pep-0498/
I think the image should be using python 3.8

**Comment by vanhauser-thc** [comment]
for whatever weird reasons python3.5 and 3.8 are installed with python3 pointing to 3.5 .... but ln -sf for the win and it works! thank you!
