### ISSUE TITLE
Clang-13 breaks aflplusplus, coverage gets stuck on benchmarks (wait couple of weeks before next ping)

### ISSUE THREAD

**Issue by inferno-chromium** [google/fuzzbench#1077]
looks like a clang regression, no rush, just fyi @vanhauser-thc 

https://www.fuzzbench.com/reports/experimental/2021-02-08-paper/index.html
libjpeg-turbo-07-2017
lcms-2017-03-21
libpng-1.2.56

reproduces locally with
make run-aflplusplus-libjpeg-turbo-07-2017

```
[*] Fuzzing test case #0 (1 total, 0 uniq crashes found, perf_score=100, exec_us=171, hits=0, map=1)...
```

this map size=1 is suspicious

if we revert benchmarks to older clang, it get fixed
```
diff --git a/benchmarks/libjpeg-turbo-07-2017/Dockerfile b/benchmarks/libjpeg-turbo-07-2017/Dockerfile
index 8809d89..c468053 100644
--- a/benchmarks/libjpeg-turbo-07-2017/Dockerfile
+++ b/benchmarks/libjpeg-turbo-07-2017/Dockerfile
@@ -14,7 +14,7 @@
 #
 ################################################################################
 
-FROM gcr.io/oss-fuzz-base/base-builder
+FROM gcr.io/oss-fuzz-base/base-builder@sha256:12125f1ecb9e4905a19c35700a3402c1eba43c82ea2d227f01c28833d75e3574
 
 RUN apt-get update && \
     apt-get install -y \
```

Some Fuzzbench benchmarks use latest clang from oss-fuzz base-builder. oss-fuzz base-builder follows the latest clang from chromium (which can be a few days old). this regression happened from https://chromium-review.googlesource.com/c/chromium/src/+/2676316, so somewhere between git tags - llvmorg-12-init-17251-g6de48655 and llvmorg-13-init-794-g83e2710e

**Comment by vanhauser-thc** [comment]
if you move to llvm-13 already then this will be a busy time for us.
you guys are just using -fsansitize feature, we the underlying IR/IRB features - as long as a new version is in development this backend changes a lot, even back and forth ... :)

**Comment by inferno-chromium** [comment]
> if you move to llvm-13 already then this will be a busy time for us.
> you guys are just using -fsansitize feature, we the underlying IR/IRB features - as long as a new version is in development this backend changes a lot, even back and forth ... :)

We follow Chromium's clang which is updated once every 2ish weeks. Right now, this is at
clang version 13.0.0 (https://github.com/llvm/llvm-project.git 83e2710eb014c9a7fcb764b0270077e4f00cdab6)
I can hardcode and force older version here - https://github.com/google/oss-fuzz/blob/master/infra/base-images/base-clang/checkout_build_install_llvm.sh#L69. Do you think this is a matter of a few days or couple of weeks work ? We don't want to hardcode for too long as other clang regressions can sneak in (e.g. for libfuzzer), so in a way we try to keep regression window to a few weeks (2-3 weeks). Once i hardcode, base-builder is updated and local repro for you would require putting a specific sha for a benchmark [adding "gcr.io/oss-fuzz-base/base-builder@sha256:a8f0c22609b9d77d30e2fb7693ab16191237c2a0329c7f5443f64f723154fd9b"]. Without hardcode, it should just reproduce as-is for now for any benchmark that uses latest base-builder, e.g. lcms, libjpeg-turbo, etc.

The main philosophy is afl-fuzz or fuzzing can break for couple of days, no worries. but testcase reproduction should not break, as this would mean all open bugs get closed. We have some stopgaps already to prevent this happening everywhere, since we run every fuzzer in a build for a few secs and if it crashes, we dont archive the build altogether. To make your life easier and not needing to update hashes everytime you need to update afl++ in OSS-Fuzz, we can have a oss-fuzz branch or follow stable.

**Comment by vanhauser-thc** [comment]
> > if you move to llvm-13 already then this will be a busy time for us.
> > you guys are just using -fsansitize feature, we the underlying IR/IRB features - as long as a new version is in development this backend changes a lot, even back and forth ... :)
> 
> Do you think this is a matter of a few days or couple of weeks work ?

about an hour or more of work - every few weeks ... that how volatile llvm is :( is gets easier after a few months when things get a bit stable, but before that a lot changes all of the time.
We were quick with llvm 11 and 12 because I had requested features I needed for LTO. now we have what we need, so we rather wait until it is less volatile.

if we can put this off for a few weeks so I can concentrate on oss-fuzz in the free time I have instead I would prefer that.

**Comment by vanhauser-thc** [comment]
in case I have spare time the next days/week - how can I easily get this clang that creates the issue?

FROM gcr.io/oss-fuzz-base/base-builder@sha256:12125f1ecb9e4905a19c35700a3402c1eba43c82ea2d227f01c28833d75e3574
and
FROM gcr.io/oss-fuzz-base/base-builder

in libjpeg worked both fine for me.

**Comment by inferno-chromium** [comment]
a8f0c22609b9d77d30e2fb7693ab16191237c2a0329c7f5443f64f723154fd9b is the buggy hash.

base-builder latest is on clang 12. and 12125f1ecb9e4905a19c35700a3402c1eba43c82ea2d227f01c28833d75e3574 from earlier comment is also clang 12.

**Comment by inferno-chromium** [comment]
@vanhauser-thc this is the patch to reproduce
```
diff --git a/benchmarks/lcms-2017-03-21/Dockerfile b/benchmarks/lcms-2017-03-21/Dockerfile
index 66e9c08..00fa6df 100644
--- a/benchmarks/lcms-2017-03-21/Dockerfile
+++ b/benchmarks/lcms-2017-03-21/Dockerfile
@@ -14,7 +14,7 @@
 #
 ################################################################################
 
-FROM gcr.io/oss-fuzz-base/base-builder
+FROM gcr.io/oss-fuzz-base/base-builder@sha256:3cb35d0276b63572793093bbae80940e122db3b81e2fef44460b7719f6ce006f
 
 RUN apt-get update && \
     apt-get install -y \
diff --git a/fuzzers/aflplusplus/builder.Dockerfile b/fuzzers/aflplusplus/builder.Dockerfile
index 156efe0..02c0feb 100644
--- a/fuzzers/aflplusplus/builder.Dockerfile
+++ b/fuzzers/aflplusplus/builder.Dockerfile
@@ -24,8 +24,7 @@ RUN apt-get update && \
 # Download and compile afl++.
 RUN git clone https://github.com/AFLplusplus/AFLplusplus.git /afl && \
     cd /afl && \
-    git checkout 17cbb03ba7d4fc0eb3b3b47911c58e25b567e89b && \
-    sed -i 's|^#define CMPLOG_SOLVE|// #define CMPLOG_SOLVE|' include/config.h
+    git checkout ec737f3368e678cbee3a916d4ef6fb683ebfa1f0
 
 # Build without Python support as we don't need it.
 # Set AFL_NO_X86 to skip flaky tests.
```

**Comment by vanhauser-thc** [comment]
workaround in #1082

**Comment by vanhauser-thc** [comment]
fixed
