### ISSUE TITLE
benchmark issues

### ISSUE THREAD

**Issue by vanhauser-thc** [google/fuzzbench#1085]
jsoncpp_jsoncpp_fuzzer has only llvm 10 installed instead of llvm 12/13 like others. this unsurprisingly breaks afl++ lto which needs at least 11:
```
/usr/local/bin/clang -v
clang version 10.0.0 (https://github.com/llvm/llvm-project.git e84b7a5fe230e42b8e6fe451369874a773bf1867)
```

bloaty_fuzz_target only has python 3.5 instead of 3.7/3.8, this breaks aflplusplus_qemu.

**Comment by inferno-chromium** [comment]
Will clean this up in next day or two, need to remove hardcoded shas in base-builder.

**Comment by vanhauser-thc** [comment]
systemd also has llvm 10 and python 3.5
