### ISSUE TITLE
How to debug measurer failures?

### ISSUE THREAD

**Issue by andreafioraldi** [google/fuzzbench#1112]
Hi to all again,
my local bug experiment (just stb and libgit) fails to evaluate the code coverage.

In the logs, I have errors like these:

```
ERROR:root:Profdata files merging failed.
ERROR:root:Merged coverage summary json file generation failed for fuzzer: aflplusplus_classic,benchmark: stb_stbi_read_fuzzer.
ERROR:root:Coverage summary json file defective or missing. Extras: {'traceback': 'Traceback (most recent call last):\n  File "/work/src/experiment/measurer/coverage_utils.py", line 277, in extract_covered_regions_from_summary_json\n    coverage_info = get_coverage_infomation(summary_json_file)\n  File "/work/src/experiment/measurer/coverage_utils.py", line 229, in get_coverage_infomation\n    return json.loads(summary.readlines()[-1])\n  File "/usr/local/lib/python3.8/json/__init__.py", line 357, in loads\n    return _default_decoder.decode(s)\n  File "/usr/local/lib/python3.8/json/decoder.py", line 337, in decode\n    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n  File "/usr/local/lib/python3.8/json/decoder.py", line 355, in raw_decode\n    raise JSONDecodeError("Expecting value", s, err.value) from None\njson.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n'}
ERROR:root:Coverage report generation failed for fuzzer: aflplusplus_classic,benchmark: stb_stbi_read_fuzzer.
```
Bugs are reported, but as you can see from the report https://b38566c1bbef.ngrok.io/experimental/bug-cmplog6/#stb_stbi_read_fuzzer-summary coverage is stuck to 0.

How can I debug these failures without restarting an experiment?

**Comment by andreafioraldi** [comment]
My fork is still based on ef464c8e0592b44bab9249e5b07586a1ad09e4df, and I see that during this week you fixed some bugs related to the PHP fuzzer (that I'm however not using).
I'm merging my fork and starting a new experiment soon to confirm if the issue is still present.

**Comment by inferno-chromium** [comment]
It is probably this - https://github.com/google/fuzzbench/pull/1109#issuecomment-797567104
just do 
make dispatcher-image
and then rerun experiment
that should fix.

**Comment by andreafioraldi** [comment]
Seems working now, should I wait a proper fix to close the issue?

**Comment by inferno-chromium** [comment]
no fix needed, that make command shouldnt be needed now, latest image has the fix.
