### ISSUE TITLE
Keep core files of fuzzers if they crash

### ISSUE THREAD

**Issue by vanhauser-thc** [google/fuzzbench#1153]
In the afl++ binary-only fuzzer variant frida seems to be a bug that results in a crash of the target binary - not the child being fuzzed but the mother process.
This only happens in fuzzbench as I am unable to reproduce this locally even using the same state corpus before the crash (from the google cloud), and refuzzing this many times for weeks.
is it possible to copy any core files in the /out folder also to the cloud bucket for future runs?

**Comment by jonathanmetzman** [comment]
You control the fuzzer.py file.
That file can put anything it wants in the `output_corpus` and it will get zipped up and included in the corpus archives for the experiment (let me know if you don't know how to access those).
