### ISSUE TITLE
version mismatch on gcr.io/fuzzbench/base-image?

### ISSUE THREAD

**Issue by SlaterLatiao** [google/fuzzbench#1159]
Hi,
I'm trying to run fuzzbench on google cloud and got the following error from dispatcher:

File "/usr/local/lib/python3.8/site-packages/google/api_core/grpc_helpers.py", line 235, in _create_composite_credentials"
credentials = google.auth.credentials.with_scopes_if_required("
TypeError: with_scopes_if_required() got an unexpected keyword argument 'default_scopes'" 

I think this is caused by google-auth being version 1.24 on the base image, as the issue goes away if I upgrade google-auth to 1.25 in the dispatcher docker file.

**Comment by inferno-chromium** [comment]
Fixed in https://github.com/google/fuzzbench/commit/c9abac0448241c34b5e96a890075418ec1c96acb
