### ISSUE TITLE
Confusion about termination of experiments on fuzzbench.com

### ISSUE THREAD

**Issue by DavidKorczynski** [google/fuzzbench#1161]
I am going through some of the reports on fuzzbench.com and am having some confusion about determining if an experiment has terminated. 

Quite a few of the reports have "experiment incomplete/still running", e.g. one which was started about five months ago by the name of it: https://www.fuzzbench.com/reports/experimental/2020-12-25/index.html  I think most reports if not all experiments following that report also shows "experiment incomplete/still running". 

My main question is how to determine if an experiment has terminated? When the message "experiment incomplete/still running" is shown, is there a possibility the experiment has terminated but is considered incomplete?

**Comment by jonathanmetzman** [comment]
Sorry, this is one area that is hard to get 100% right unless we use heuristics which we don't.
Basically, in Fuzzbench experiments thousands of trials are run. Errors happen in some of these that prevent them from finishing.
Sometimes our measurer doesn't realize this and waits forever for a testcase that will never come. I should probably fix that, but that is the current behavior.

>My main question is how to determine if an experiment has terminated? 

The answer I use is "just wait a few days after the experiment, if it's been a week and the report is incomplete, 99% of the time it is actually finished".

>When the message "experiment incomplete/still running" is shown, is there a possibility the experiment has terminated but is considered incomplete?

Yeah exactly, it's really about measuring not about the experiment. I'll think about changing this too.

**Comment by DavidKorczynski** [comment]
Makes sense and thanks for the clarification!
