### ISSUE TITLE
ffmpeg bug target has no coverage

### ISSUE THREAD

**Issue by vanhauser-thc** [google/fuzzbench#1173]
https://www.fuzzbench.com/reports/2021-06-07-crash/index.html#ffmpeg_ffmpeg_demuxer_fuzzer

my guess is the coverage binary  for it is unable to run.

**Comment by vanhauser-thc** [comment]
also on the bottom of the run it states how to get the experiment config: `curl https://storage.googleapis.com/2021-06-07-crash/config/experiment.yaml` but this yields `<?xml version='1.0' encoding='UTF-8'?><Error><Code>NoSuchBucket</Code><Message>The specified bucket does not exist.</Message></Error>`

**Comment by vanhauser-thc** [comment]
@andreafioraldi fyi

**Comment by wideglide** [comment]
looks like the url was missing a `input/`?
the config is here : http://commondatastorage.googleapis.com/fuzzbench-data/index.html?prefix=2021-06-07-crash/input/config/

I noticed the coverage binary was compiled with llvm-9, is that normal for bug benchmarks??

with LLVM-9 `llvm-profdata` and `llvm-cov`, coverage seems to work fine.

```
$ docker run --rm -it --entrypoint bash -v $PWD:/opt/data gcr.io/fuzzbench/builders/aflplusplus/ffmpeg_ffmpeg_demuxer_fuzzer:2021-06-07-crash
root@d269b62ac3ad:/src# cd /opt/data/
root@d269b62ac3ad:/opt/data# llvm-cov report -instr-profile default.profdata ffmpeg_DEMUXER_fuzzer | (head -n 1 ; tail -n1)
Filename                                          Regions    Missed Regions     Cover   Functions  Missed Functions  Executed       Lines      Missed Lines     Cover
TOTAL                                              206210            179376    13.01%        7108              5722    19.50%      237808            203614    14.38%
root@d269b62ac3ad:/opt/data# llvm-cov --version
LLVM (http://llvm.org/):
  LLVM version 9.0.0svn
  Optimized build.
  Default target: x86_64-unknown-linux-gnu
  Host CPU: ivybridge
```

**Comment by vanhauser-thc** [comment]
@inferno-chromium this is still unfixed
