### ISSUE TITLE
make presubmit goes wrong

### ISSUE THREAD

**Issue by MuseMamba** [google/fuzzbench#1223]
errors:
After the configuration according to the official document，I checked it out with the instruct "make presubmit", then it gave the error information.

analysis/test_plotting.py::test_pariwise_unique_coverage_heatmap_plot Fatal Python error: Aborted  [13%]

details:
platform linux -- Python 3.8.10, pytest-6.1.2, py-1.10.0, pluggy-0.13.1
20.04.1-Ubuntu
x86_64 GNU/Linux

Has anyone had a similar problem？
Thx!

**Comment by jonathanmetzman** [comment]
I haven't seen this before.
I don't have a python3.8 install to test this with. Could you try with python3.9?

**Comment by jonathanmetzman** [comment]
Does 3.9 fix it?

**Comment by MuseMamba** [comment]
> Does 3.9 fix it?

It doesn't work, but thank you for your help，I think it's some kind of assignment problem, I'll double-check, maybe update the information later, thx again.

**Comment by TotalKnob** [comment]
I also encountered this issue running Ubuntu 20.04.3, Python 3.8.10. Installing qt5 fixes it.

```
sudo apt update && sudo apt install -y qt5-default
```

**Comment by MuseMamba** [comment]
WOW! it works！Thanks a million!

**Comment by jonathanmetzman** [comment]
@lszekeres Could you change our docs to specify this is needed or break this dependency?
Thanks!

**Comment by jonathanmetzman** [comment]
> I also encountered this issue running Ubuntu 20.04.3, Python 3.8.10. Installing qt5 fixes it.
> 
> ```
> sudo apt update && sudo apt install -y qt5-default
> ```

I'm surprised this is needed. I feel like we don't install this in our docker images.

**Comment by leonasdev** [comment]
Fixed by `sudo apt-get install qtbase5-dev qtchooser qt5-qmake qtbase5-dev-tools` on Ubuntu 22.04.
