### ISSUE TITLE
Are benchmarks fuzzer-specific or any fuzzer should be able to run all benchmarks?

### ISSUE THREAD

**Issue by aeroned** [google/fuzzbench#1230]
Hi! Newbie here.

I was wondering if any of the provided benchmarks are fuzzer-specific. I happened to building AFL with aspell_fuzzer, though I encounter an error every time I run it. Thus, should fuzzers have a benchmark support, or they must run every benchmark?

**Comment by Strafo** [comment]
Some benchmarks are not compatible with some fuzzers and are reported in the files: fuzzbench/benchmarks/_[benchmark]_/benchmark.yaml under "**unsupported_fuzzers**".
In addition, the documentation contains more information! [blocklisting-benchmarks](https://google.github.io/fuzzbench/getting-started/adding-a-new-fuzzer/#blocklisting-benchmarks)

**Comment by aeroned** [comment]
How do I identify a new fuzzer is not compatible with a benchmark?

I believe an incompatible fuzzer will receive an error, like: 

```
executor failed running [/bin/sh -c echo "Run fuzzer_build to build the target" && if [ -z "$debug_builder" ] ; then fuzzer_build; fi]: exit code: 1
make: *** [docker/generated.mk:9002: .####-matio_matio_fuzzer-builder] Error 1
```

Am I correct?

**Comment by jonathanmetzman** [comment]
Something like that, but it might be easily fixable. Whether or not it is incompatible or needs a simple fix is basically up to you, the integrator.
