### ISSUE TITLE
Support fuzzer feature testing via configurations (also allow configurations in fuzzers dir).

### ISSUE THREAD

**Issue by vanhauser-thc** [google/fuzzbench#124]
Several fuzzers here like honggfuzz, afl, afl++, aflfast, fairfuzz etc. dont just have one feature but many and also several options to tweak behaviour and performance.

it would be a great opportunity to be able to test them all. as a simple example:
AFLfast has 5 power schedules. To have a benchmark on all 5 schedules on all targets would be beneficial to learn which are better than other and which are better on specific types of targets (no corpus vs large good corpus, binary input vs. text input, etc. etc.)

Is that something that is "allowed", "supported" or a "goal" for this project?
Because IMHO this would be the most important aspect of fuzzbench, as just comparing one fuzzer in a fixed configuration versus other fuzzers in theirs doesnt help much. Effective fuzzing campaigns must deploy various fuzzers and combine their results. hence learning which fuzzer in which configuration is strong on which kind of target scenario - that is IMHO the important learning experience.

plus of course optimizing the fuzzers themselves. but even for that I need to run "my" fuzzer in various configurations and test stages.

**Comment by inferno-chromium** [comment]
This is definitely a goal for this project and right now support is there, but not clear, we are working to improve it [e.g. structure configs properly inside fuzzer directory]. As an example, see https://www.fuzzbench.com/reports/2020-03-06-libfuzzer/index.html which was testing libfuzzer's own features.
We have to see how we visualize this, do in a main report or do it seperately in a test report (like that libfuzzer example).

Given us a week or two to let some things stabilize, right now we are fixing CI and keeping up with new CLs and making sure all benchmarks build with all new fuzzers.

**Comment by inferno-chromium** [comment]
This is also same as https://github.com/google/fuzzbench/issues/73, so closing in favor of that.

**Comment by inferno-chromium** [comment]
Actually that one is specifically for build time issues, so lets use this for general tracking.

**Comment by vanhauser-thc** [comment]
For now we could just create fuzzer directories for the variants (e.g. aflplusplus-opta-featurex, aflplusplus-optb-featurey, aflplusplus-optb-featurez).

would that be a possible interim solution? if yes, how many variants per fuzzer would be ok?

I find it difficult to work on enhancements on the fuzzer when cant really compare various runs. and doing this at "home" - I dont have the number of cores available :)

**Comment by jonathanmetzman** [comment]
> For now we could just create fuzzer directories for the variants (e.g. aflplusplus-opta-featurex, aflplusplus-optb-featurey, aflplusplus-optb-featurez).
> 
> would that be a possible interim solution? if yes, how many variants per fuzzer would be ok?
> 
I think that's fine as an interim solution yes.

I don't have an exact number for how many is OK but a few more should be fine.
And even more than that is OK as long as they aren't permanent additions. I'd rather not keep around configs that going to be actively developed any time soon.
P.S. It would help us if you could provide updates on what happens as a result of testing configs (if anything does).

**Comment by inferno-chromium** [comment]
This is done, remaining work is https://github.com/google/fuzzbench/issues/73

**Comment by vanhauser-thc** [comment]
@inferno-chromium perfect! can you point a documentation (or code ;) about how to use this? thanks :)

**Comment by inferno-chromium** [comment]
@vanhauser-thc - https://github.com/google/fuzzbench/pull/260 is for build time support (in review). once that is in, we will add docs asap and also probably convert either fastcgs or afl++ as an example/

**Comment by jonathanmetzman** [comment]
The decided not to implement special support for variants.
Right now the correct way to implement a variant (requiring buildtime or runtime changes) is to make a new fuzzer.py This fuzzer.py can import from the base fuzzer if it needs to.
