### ISSUE TITLE
Dockerfile error in ffmpeg_ffmpeg_demuxer_fuzzer

### ISSUE THREAD

**Issue by elManto** [google/fuzzbench#1240]
There is an issue in the Dockerfile to build ffmpeg_ffmpeg_demuxer_fuzzer at this line:

https://github.com/google/fuzzbench/blob/master/benchmarks/ffmpeg_ffmpeg_demuxer_fuzzer/Dockerfile#L17

Consequently you cannot build this benchmark. I tried to fix it by using one of the two hashes, but the compilation does not work in any case (even if with two different errors).

**Comment by jonathanmetzman** [comment]
Sorry about this.
I'll try to take a look today or tomorrow.
