### ISSUE TITLE
Support dictionaries (mostly done, only need to add way to test dictionaryless experiment)

### ISSUE THREAD

**Issue by jonathanmetzman** [google/fuzzbench#127]
Many of our benchmarks have dictionaries, it would probably be interesting to see how using dictionaries affects results (since dictionaries are pretty widely used in the real world).
The downsides I see to supporting dictionaries are:
1. A wider interface for integrating fuzzers.
2. Some fuzzers (like eclipser I believe) don't support dictionaries, so in some sense the comparsion won't be apples to apples.

**Comment by inferno-chromium** [comment]
Done in https://github.com/google/fuzzbench/pull/149

Will close this after first report generated.

**Comment by jonathanmetzman** [comment]
#149 doesn't support dictionariless experiments in `run_experiment.py` so I'm not sure I would say it is completed.

**Comment by inferno-chromium** [comment]
Need to think through this discussion as well - https://github.com/google/fuzzbench/pull/149#pullrequestreview-380803865

**Comment by inferno-chromium** [comment]
Generate atleast one report without dicts and keep it for reference.

**Comment by wideglide** [comment]
Just curious, what is the status on this?  I've run some side-by-side comparisons with AFL and it seems to only matter in three of the current benchmarks: lcms, libpng, libxml2, but it makes a significant difference when used.

I think using a dictionary with these targets would close the gap between fuzzers which have implemented methods to generate dictionary values on the fly (libfuzzer, honggfuzz, aflplusplus).  It would be good to know if a pre-generated dictionary works better for targets that have them available versus attempting to determine good constants/strings during fuzzing.

**Comment by inferno-chromium** [comment]
Dictionaries are currently being accounted for whereever available [any recent report uses it], we don't have a comparison with non-dictionary case yet.

**Comment by wideglide** [comment]
ok, thanks!  I wasn't sure since the issue was still open.  

What about adding the 'icc.dict' for lcms and the 'png.dict' for libpng?

**Comment by inferno-chromium** [comment]
> ok, thanks! I wasn't sure since the issue was still open.
> 
> What about adding the 'icc.dict' for lcms and the 'png.dict' for libpng?

Running short on cycles, can you submit a PR to add those in build.sh for those benchmarks ?

**Comment by wideglide** [comment]
yep, too easy!

**Comment by inferno-chromium** [comment]
@wideglide - see also https://github.com/google/fuzzing/tree/master/dictionaries, we are putting dicts there.

**Comment by wideglide** [comment]
Looks like this is already supported?
just need to add
```
env:
  SKIP_DICT: "1"
```
to the `experiment-config.yaml`?

`runner-startup-script-template.sh` has `{{additional_env}}` which is [templated](https://github.com/google/fuzzbench/blob/master/experiment/scheduler.py#L246) by schedule.py.

When [get_dictionary_path](https://github.com/google/fuzzbench/blob/master/fuzzers/utils.py#L118) is called, it will return `None` when 'SKIP_DICT' is found as an environment variable.

Looks like all fuzzer.py check the result of get_dictionary_path?

**Comment by inferno-chromium** [comment]
yes, forgot that Jonathan's local experiment cl enables this.

this would need creating fuzzer-config.yaml for every fuzzer and then adding SKIP_DICT to it. that is fine for a one-time comparison run.

i think Jonathan also wanted an experiment wide setting, can add that and then close this.

**Comment by wideglide** [comment]
just checking in on this capability -- I would be curious to see the results of a dictionaryless experiment to see how much dictionaries enhance coverage per fuzzer.  I would suspect that some fuzzers benefit more than others, but as side-by-side comparison would be interesting.

**Comment by jonathanmetzman** [comment]
We still haven't implemented it.
You could try implementing it yourself if you use the unsupported technique for running local experiments:
https://github.com/google/fuzzbench/issues/619
I think things should work enough for you to test this if you do a 2 trial, 1 fuzzer 1 benchmark experiment.

@rsprabery I think you expressed interest in implementing seedless experiments. Supporting this would be similar, and even easier since some of the work is already done.

I think these are the necessary steps:
1. Plumb skip_dict through to runner instances from config file [here (template)] (https://github.com/google/fuzzbench/blob/master/experiment/resources/runner-startup-script-template.sh#L40) and [here (templating code)](https://github.com/google/fuzzbench/blob/master/experiment/scheduler.py#L724).

Seedless experiments will be the same to support except the env var will be different. We can do SKIP_SEED_CORPUS.
And then our seed unpacking code will have to be modified. I think [_clean_seed_corpus](https://github.com/google/fuzzbench/blob/master/experiment/runner.py#L72) is a reasonable place to put this. We can just delete the contents of the seed corpus if SKIP_SEED_CORPUS is specified in the environment.

(bonus points if you can get rid of fuzzbench's bad config system of specifying env vars to pass around and replace it with passing a config file around so that each time we want to support a new var we don't need to manually change code).

**Comment by rsprabery** [comment]
@jonathanmetzman - I think it makes sense to do these two together (seedless, dictionaryless).

I may be able to dig into this in a few weeks.

**Comment by jonathanmetzman** [comment]
I found some time to do this. I'll link to the results when I get a chance to run an experiment.

**Comment by wideglide** [comment]
Has this experiment been run?  I'd really like the side-by-side comparison that shows how much (or not) dictionaries assist fuzzers.

**Comment by inferno-chromium** [comment]
> Has this experiment been run? I'd really like the side-by-side comparison that shows how much (or not) dictionaries assist fuzzers.

We are planning to run this soonish. You want
Regular experiment VS experiment with NO SEEDS AND NO DICTS 
or something else like
Regular experiment VS experiment with just NO DICTS
or something else like
Regular experiment VS experiment with just NO SEEDS

@laurentsimon @jonathanmetzman @lszekeres - your thoughts ? or do all three ?

**Comment by wideglide** [comment]
Personal preference on order of importance is:
1. regular vs NO DICTS
2. regular vs NO SEEDS and NO DICTS
3. regular vs NO SEEDS

- Only the benchmarks that have dictionaries available would need to be run in the experiment with no dictionaries, if it makes easier to run with fewer benchmarks.
- from some experiments I've run, having a well formed initial seed makes a significant difference only for about half of the benchmarks (ones with structured inputs).
