### ISSUE TITLE
Benchmark manul fuzzer

### ISSUE THREAD

**Issue by Dor1s** [google/fuzzbench#128]
//cc @mxmssh

**Comment by mxmssh** [comment]
xref: https://github.com/mxmssh/manul/issues/55

**Comment by Tanq16** [comment]
Hi @mxmssh !
Is it okay for me to proceed with the integration of Manul to FuzzBench ?
Thanks
Tanishq Rupaal

**Comment by mxmssh** [comment]
You are more than welcome! @Tanq16

**Comment by jonathanmetzman** [comment]
Done in #419.
