### ISSUE TITLE
Experiment not run?

### ISSUE THREAD

**Issue by jdhiser** [google/fuzzbench#1290]
[My PR](https://github.com/google/fuzzbench/pull/1285) for 2 experiments ([one](https://www.fuzzbench.com/reports/experimental/2021-11-18-bug), [two](https://www.fuzzbench.com/reports/experimental/2021-11-18-coverage)) was accepted 2 days ago.  However, the reports don't seem to be available.  My understanding is that experiment should happen twice daily.  Can anyone help answer if there's an interruption or some other issue or how one might debug an experiment that didn't run?

@jonathanmetzman

**Comment by vanhauser-thc** [comment]
there have been no experiment runs since the 13th november I think, although several experiment requests have been merged. something is broken.

**Comment by vanhauser-thc** [comment]
@jonathanmetzman @inferno-chromium 
experiments are built but do not run, are you aware? is this fixed now?

**Comment by vanhauser-thc** [comment]
> There was an issue I thought I fixed. Let me see what's wrong.

seems there is a different issue then. still no new experiments

**Comment by jonathanmetzman** [comment]
Making this my p0

**Comment by jonathanmetzman** [comment]
I think i've figured this out. I'm gonna land CLs for redoing the missed experiments gradually so we don't overload FB by running 7+ experiments at once.

**Comment by WorksButNotTested** [comment]
Fab. Good work!

**Comment by vanhauser-thc** [comment]
@jonathanmetzman 
still the same. binaries are built but no benchmark is run:
```
gsutil ls gs://fuzzbench-data/2021-11-22-aflpp/
gs://fuzzbench-data/2021-11-22-aflpp/build-logs/
gs://fuzzbench-data/2021-11-22-aflpp/coverage-binaries/
gs://fuzzbench-data/2021-11-22-aflpp/input/
```

**Comment by jonathanmetzman** [comment]
> @jonathanmetzman still the same. binaries are built but no benchmark is run:
> 
> ```
> gsutil ls gs://fuzzbench-data/2021-11-22-aflpp/
> gs://fuzzbench-data/2021-11-22-aflpp/build-logs/
> gs://fuzzbench-data/2021-11-22-aflpp/coverage-binaries/
> gs://fuzzbench-data/2021-11-22-aflpp/input/
> ```

I think that was just do to some slowness. I see a report now: https://www.fuzzbench.com/reports/experimental/2021-11-22-aflpp/index.html

**Comment by jdhiser** [comment]
@jonathanmetzman Did everything run properly?  [This report](https://www.fuzzbench.com/reports/experimental/2021-11-22-zafl-bug/index.html) is still missing two configurations?

**Comment by jonathanmetzman** [comment]
> @jonathanmetzman Did everything run properly? [This report](https://www.fuzzbench.com/reports/experimental/2021-11-22-zafl-bug/index.html) is still missing two configurations?

I think everything happend fine on FuzzBench's end. It's likely that some fuzzers broke with such a large experiment. What do you mean it is missing two configurations? Two benchmarks? Which configurations is it missing?

**Comment by jdhiser** [comment]
I mean that the `aflplusplus_qemu_tracepc` and `aflplusplus_qemu` fuzzers have a NaN listed for almost every benchmark.  I've run these before and gotten results for almost every benchmark.

**Comment by jonathanmetzman** [comment]
> I mean that the `aflplusplus_qemu_tracepc` and `aflplusplus_qemu` fuzzers have a NaN listed for almost every benchmark. I've run these before and gotten results for almost every benchmark.

Crap. I'll look into this tomorrow AM.

**Comment by jonathanmetzman** [comment]
> > I mean that the `aflplusplus_qemu_tracepc` and `aflplusplus_qemu` fuzzers have a NaN listed for almost every benchmark. I've run these before and gotten results for almost every benchmark.
> 
> :-(. I'll look into this tomorrow AM.

Sorry, need to fix https://github.com/google/oss-fuzz/issues/6755 before looking into this.

**Comment by jonathanmetzman** [comment]
> I mean that the `aflplusplus_qemu_tracepc` and `aflplusplus_qemu` fuzzers have a NaN listed for almost every benchmark. I've run these before and gotten results for almost every benchmark.

I think they blocklisted a lot of the crash benchmarks: https://github.com/search?q=aflplusplus_qemu+repo%3Agoogle%2Ffuzzbench+language%3AYAML&type=Code&ref=advsearch&l=YAML&l=

**Comment by jdhiser** [comment]
> > I mean that the `aflplusplus_qemu_tracepc` and `aflplusplus_qemu` fuzzers have a NaN listed for almost every benchmark. I've run these before and gotten results for almost every benchmark.
> 
> I think they blocklisted a lot of the crash benchmarks: https://github.com/search?q=aflplusplus_qemu+repo%3Agoogle%2Ffuzzbench+language%3AYAML&type=Code&ref=advsearch&l=YAML&l=

Ah, I got bug and coverage testing confused.  Thanks!
