### ISSUE TITLE
Required files are not written to the directory (corpus) throughout the campaign

### ISSUE THREAD

**Issue by dliyanage** [google/fuzzbench#1295]
Hi,
This issue is based on the results we obtained from the experiment named `2021-11-22-aflbb`. In our AFL fuzzer version named `pythia-effect-bb`, we write data file named `plot_data` to the corpus directory once every 5 seconds. After 23hrs of fuzzing, we expect it to have thousands of entries in that plot_data file. But, there were only ~170 entries while I was inspecting them on multiple subjects.
By looking at the timestamps of resulted plot_data files, I realized that the file was written to the directory only at the beginning of the campaign/s. 
If required, I can provide you those extracted data files.

Thanks

**Comment by jonathanmetzman** [comment]
>After 23hrs of fuzzing, we expect it to have thousands of entries in that plot_data file. 

Sorry, I don't know what you mean by "entry". Please clarify.
Are you saying the file was only written to ~170 times instead of once every 5 seconds?

>By looking at the timestamps of resulted plot_data files, I realized that the file was written to the directory only at the beginning of the campaign/s.

Sorry, I don't have enough context here to understand why it is FuzzBench that is at fault here and not your implementation.

**Comment by jonathanmetzman** [comment]
Ping

**Comment by dliyanage** [comment]
Hi Jonathan, 
Sorry for being late to reply. The last few days were pretty crazy.

In our version of AFL, we write some fuzzing related data to a file called `plot_data`. We write this file to `/out/corpus` directory. We write a new row to this file once every 5 seconds during the fuzzing campaign.

Therefore, we expect this `plot_data` file to have more than 15000 entries in this file. 

My concern is, we only had ~170 rows in this file which is strange. Appreciate if you can look into that? 

Please find the sample `plot_data` file attached.

Cheers and thanks.

[plot_data.csv](https://github.com/google/fuzzbench/files/7731780/plot_data.csv)

**Comment by jonathanmetzman** [comment]
My best guess is that you only saw this on a few trials but it actually only affects them because those trials were preempted. Preempted trials are thrown out and don't affect final results.

Umm...we don't have the data in gs://fuzzbench-data for this experiment anymore so I might have trouble looking into this. Data storage costs were getting high and we deleted a lot of the data for old experiments.

**Comment by jonathanmetzman** [comment]
Feel free to run another experiment.
When #1343 is fixed we'll stop deleting the corpora.

**Comment by mboehme** [comment]
These were experiments with a blackbox version of AFL. My guess is that Fuzzbench did not sync into the GCP because no new seeds were written in any of the runners.

**Comment by jonathanmetzman** [comment]
Yeah I think we exclude plot_data from the corpus, (see [here](https://github.com/google/fuzzbench/blob/master/experiment/runner.py#L58)) sorry for not realizing this earlier.
Feel free to try again with a different file name
