### ISSUE TITLE
question about fafuzz experiment

### ISSUE THREAD

**Issue by Mart11n** [google/fuzzbench#1299]
The [fafuzz experiment PR](https://github.com/google/fuzzbench/pull/1297) has been merged  yesterday. However, I do not seen any report on [the report website](https://www.fuzzbench.com/reports/experimental/2021-12-2-fafuzzer). Is there anything wrong? I see that I've made a mistake on the name of the experiment, which should be "2021-12-02-fafuzzer" and lead to the failure of last CI in the PR. Does this matter?

**Comment by jonathanmetzman** [comment]
Sorry for the delay in responding to this.
I would guess the reason you suggested is why it didn't run.
I'm looking into this now.

**Comment by jonathanmetzman** [comment]
I think this experiment should run later tonight. Please reopen if it does not.
