### ISSUE TITLE
`FUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION` discarded

### ISSUE THREAD

**Issue by EliaGeretto** [google/fuzzbench#1300]
It seems that the value of `CFLAGS` set in the builders is discarded while building the benchmarks using the appropriate `fuzzer.py` file. The discard happens here, it would seem:
https://github.com/google/fuzzbench/blob/d156b3579fe882b46fb65ab3f2bc9a5c5aeb3308/fuzzers/utils.py#L179-L180

The value of `CFLAGS` set in the builders contains `-DFUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION`, which is thus discarded while building. Discarding this value makes at least `libxslt_xpath` and `libxml2_libxml2_xml_reader_for_file_fuzzer` compile with features that make executions non-deterministic. Other benchmarks may be affected.

**Comment by EliaGeretto** [comment]
It is probably worth mentioning that the same non determinism is probably also present for `libxml2-v2.9.2`, even if this issue is fixed. The first version to support `FUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION` seems to be `v2.9.10`.

**Comment by jonathanmetzman** [comment]
Thanks! Will try to look into this later this week.

**Comment by EliaGeretto** [comment]
Actually, I have a fix that seems to work for me. I'll submit a PR.
