### ISSUE TITLE
No seeds and limited number of seeds

### ISSUE THREAD

**Issue by RosenZhu** [google/fuzzbench#1309]
In the method `experiment/runner.py/_clean_seed_corpus()`, I find that there is an environmental variable `NO_SEEDS`, but I cannot find how to set the variable. Do we set the `NO_SEEDS` in fuzzers/***/fuzzer.py/prepare_fuzz_environment()?

Moreover, if I want to use a limited number of initial seeds, is there a way to do so? I add some lines and an environmental variable `NUM_SEEDS_MAX` in `_clean_seed_corpus()` so that I can use a environmental variable to set the max number of initial seeds. The code is:
```
def _clean_seed_corpus(seed_corpus_dir):
    """Prepares |seed_corpus_dir| for the trial. This ensures that it can be
    used by AFL which is picky about the seed corpus. Moves seed corpus files
    from sub-directories into the corpus directory root. Also, deletes any files
    that exceed the 1 MB limit. If the NO_SEEDS env var is specified than the
    seed corpus files are deleted."""

    ###num_selected_seeds = 0
    max_num_seeds = 0
    if environment.get('NUM_SEEDS_MAX'):
        max_num_seeds = int(os.environ['NUM_SEEDS_MAX'])###

    if not os.path.exists(seed_corpus_dir):
        return

    if environment.get('NO_SEEDS'):
        logs.info('NO_SEEDS specified, deleting seed corpus files.')
        shutil.rmtree(seed_corpus_dir)
        os.mkdir(seed_corpus_dir)
        return

    failed_to_move_files = []
    for root, _, files in os.walk(seed_corpus_dir):
        for filename in files:
            file_path = os.path.join(root, filename)

            if os.path.getsize(file_path) > CORPUS_ELEMENT_BYTES_LIMIT:
                os.remove(file_path)
                logs.warning('Removed seed file %s as it exceeds 1 Mb limit.',
                             file_path)
                continue
            
            ###if max_num_seeds > 0 and num_selected_seeds > max_num_seeds:
                continue###

            sha1sum = utils.file_hash(file_path)
            new_file_path = os.path.join(seed_corpus_dir, sha1sum)
            try:
                shutil.move(file_path, new_file_path)
                ###num_selected_seeds += 1###
            except OSError:
                failed_to_move_files.append((file_path, new_file_path))

    if failed_to_move_files:
        logs.error('Failed to move seed corpus files: %s', failed_to_move_files)
```
The code lines between ###xxx### is the added lines.
Is this the right way to set limited initial seeds? If so, do I set the ENV in `prepare_fuzz_environment()`? For example,
``` 
os.environ['NUM_SEEDS_MAX'] = '10'
```

Thanks!

**Comment by jonathanmetzman** [comment]
> In the method `experiment/runner.py/_clean_seed_corpus()`, I find that there is an environmental variable `NO_SEEDS`, but I cannot find how to set the variable. Do we set the `NO_SEEDS` in fuzzers/***/fuzzer.py/prepare_fuzz_environment()?

To do a seedless experiment, pass `--no-seeds` to `run_experiment.py`

> 
> Moreover, if I want to use a limited number of initial seeds, is there a way to do so? I add some lines and an environmental variable `NUM_SEEDS_MAX` in `_clean_seed_corpus()` so that I can use a environmental variable to set the max number of initial seeds. The code is:
> 
> ```
> def _clean_seed_corpus(seed_corpus_dir):
>     """Prepares |seed_corpus_dir| for the trial. This ensures that it can be
>     used by AFL which is picky about the seed corpus. Moves seed corpus files
>     from sub-directories into the corpus directory root. Also, deletes any files
>     that exceed the 1 MB limit. If the NO_SEEDS env var is specified than the
>     seed corpus files are deleted."""
> 
>     ###num_selected_seeds = 0
>     max_num_seeds = 0
>     if environment.get('NUM_SEEDS_MAX'):
>         max_num_seeds = int(os.environ['NUM_SEEDS_MAX'])###
> 
>     if not os.path.exists(seed_corpus_dir):
>         return
> 
>     if environment.get('NO_SEEDS'):
>         logs.info('NO_SEEDS specified, deleting seed corpus files.')
>         shutil.rmtree(seed_corpus_dir)
>         os.mkdir(seed_corpus_dir)
>         return
> 
>     failed_to_move_files = []
>     for root, _, files in os.walk(seed_corpus_dir):
>         for filename in files:
>             file_path = os.path.join(root, filename)
> 
>             if os.path.getsize(file_path) > CORPUS_ELEMENT_BYTES_LIMIT:
>                 os.remove(file_path)
>                 logs.warning('Removed seed file %s as it exceeds 1 Mb limit.',
>                              file_path)
>                 continue
>             
>             ###if max_num_seeds > 0 and num_selected_seeds > max_num_seeds:
>                 continue###
> 
>             sha1sum = utils.file_hash(file_path)
>             new_file_path = os.path.join(seed_corpus_dir, sha1sum)
>             try:
>                 shutil.move(file_path, new_file_path)
>                 ###num_selected_seeds += 1###
>             except OSError:
>                 failed_to_move_files.append((file_path, new_file_path))
> 
>     if failed_to_move_files:
>         logs.error('Failed to move seed corpus files: %s', failed_to_move_files)
> ```
> 
> The code lines between ###xxx### is the added lines. Is this the right way to set limited initial seeds? If so, do I set the ENV in `prepare_fuzz_environment()`? For example,
> 
> ```
> os.environ['NUM_SEEDS_MAX'] = '10'
> ```
> 


If you want to set an env var across all fuzzers in an experiment I'd recommend doing so [here](https://github.com/google/fuzzbench/blob/25fd9706e11cdd05072820b0a405c8b89d28af23/experiment/resources/runner-startup-script-template.sh#L46) and [here](https://github.com/google/fuzzbench/blob/3738bd6d35c159c3371c0876a1bd291d16fd6b57/experiment/run_experiment.py#L233) and [here](https://github.com/google/fuzzbench/blob/25fd9706e11cdd05072820b0a405c8b89d28af23/experiment/scheduler.py#L689)
> Thanks!

**Comment by RosenZhu** [comment]
Thanks for your quick response.

**Comment by RosenZhu** [comment]
Just a comment for others who want to add a new env var:
The related files are [experiment-config](https://github.com/google/fuzzbench/blob/3738bd6d35c159c3371c0876a1bd291d16fd6b57/experiment/test_data/experiment-config.yaml#L31), [scheduler](https://github.com/google/fuzzbench/blob/25fd9706e11cdd05072820b0a405c8b89d28af23/experiment/scheduler.py#L689), [run_experiment](https://github.com/google/fuzzbench/blob/3738bd6d35c159c3371c0876a1bd291d16fd6b57/experiment/run_experiment.py#L233), [runner-startup-script-template](https://github.com/google/fuzzbench/blob/25fd9706e11cdd05072820b0a405c8b89d28af23/experiment/resources/runner-startup-script-template.sh#L46), [runner](https://github.com/google/fuzzbench/blob/45668bb09ccc1f7ab7f2cdebee11a18b9d8d4e27/experiment/runner.py#L81), and [test_scheduler](https://github.com/google/fuzzbench/blob/45668bb09ccc1f7ab7f2cdebee11a18b9d8d4e27/experiment/test_scheduler.py#L117)
