### ISSUE TITLE
Error caused by a new version of dependency (`MarkupSafe` Version 2.1.0)

### ISSUE THREAD

**Issue by Alan32Liu** [google/fuzzbench#1341]
## Error message
Running local experiments with [run_experiment.py](https://google.github.io/fuzzbench/running-a-local-experiment#executing-run_experimentpy) causes an `Import Error`:
```python
"/path/to/fuzzbench/.venv/lib/python3.9/site-packages/jinja2/filters.py", line 13, in <module>
    from markupsafe import soft_unicode
ImportError: cannot import name 'soft_unicode' from 'markupsafe' (/path/to/fuzzbench/.venv/lib/python3.9/site-packages/markupsafe/__init__.py)
```

## Reason
This is because `soft_unicode` was removed in [version 2.1.0 of `MarkupSafe`](https://markupsafe.palletsprojects.com/en/2.1.x/changes/#version-2-1-0).

## Fix
Until `jinja2` (and other packages that depend on `MarkupSafe`) fixes their code, we can temporarily fix it by using earlier versions of `MarkupSafe`.
For example, the following command fixed it on my machine:
```shell
pip install markupsafe==2.0.1  # the immediate previous version.
```

**Comment by jonathanmetzman** [comment]
I think https://github.com/google/fuzzbench/pull/1340 (merged yesterday) fixes your problem.
Please reopen this if I am wrong.
