### ISSUE TITLE
Report error broken links

### ISSUE THREAD

**Issue by AntonDewitz** [google/fuzzbench#1350]
Links in reports seem to be broken.
```
curl https://storage.googleapis.com/[experiment_name]/config/experiment.yaml > /tmp/experiment-config.yaml
```

results in 
```
<?xml version='1.0' encoding='UTF-8'?>
<Error>
    <Code>NoSuchBucket</Code>
    <Message>The specified bucket does not exist.</Message>
</Error>
```
when changing [experiment_name] to something like 2022-02-18-field, 2021-02-17-bug-paper, 2021-08-19-crash-s, or 2021-08-19-crash-s2

**Comment by jonathanmetzman** [comment]
Whoops, that should be storage.googleapis.com/fuzzbench-data/$experiment_name/config/experiment.yaml

Leaving this bug open because I should really change all the existing HTML files even though I don't know if it's worth the time.

**Comment by AntonDewitz** [comment]
The link `storage.googleapis.com/fuzzbench-data/$experiment_name/config/experiment.yaml` results in NoSuchKey but `storage.googleapis.com/fuzzbench-data/$experiment_name/input/config/experiment.yaml` works.

**Comment by jonathanmetzman** [comment]
Whoops, OK need to fix that too.

**Comment by jonathanmetzman** [comment]
I should be able to change this in our script so going forward the URL will be correct.
Apologies for the error, it's a feature that is meant for people other than myself and I guess I didn't test it enough (I repro through more manual means)

**Comment by jonathanmetzman** [comment]
Are you trying to reproduce these experiments by the way? there may be another issue to fix.

**Comment by AntonDewitz** [comment]
I was more interested in seeing if my own files were correct by comparing them with existing ones. Thanks for the help though!
