### ISSUE TITLE
inconsistent BENCHMARK value

### ISSUE THREAD

**Issue by thuanpv** [google/fuzzbench#137]
Hi @jonathanmetzman,

When I tested AFLSmart on libpcap_fuzz_both benchmark, I figured out that the BENCHMARK env. variable value may not be consistent with the name of corresponding benchmark stored in benchmarks folder.

For example, when I run the experiment for libpcap_fuzz_both benchmark, BENCHMARK value is "libpcap". Maybe it uses the benchmark name from OSS-Fuzz project? I don't know whether this is an issue or not.

Thuan

**Comment by jonathanmetzman** [comment]
This is a bug that probably only affects OSS-Fuzz benchmarks. I suspect this bug only has an impact on fuzzers that rely on `BENCHMARK` (ie: aflsmart).
I'll look into fixing it.

**Comment by jonathanmetzman** [comment]
I think this bug only happened when using make and not in production. It should be fixed now.
