### ISSUE TITLE
fuzzbench is difficult to use in china, due to network. I hope someone together with me make it convenient to use in china.  

### ISSUE THREAD

**Issue by Ricardio609** [google/fuzzbench#1389]
I am a Fuzzing researcher from China. Due to network issues, I can't use Fuzzbench on my computer in China. I am now trying to use Fuzzbench configuration to make it use in China. But my personal energy is limited, I hope some people can join together to achieve this goal.

**Comment by jonathanmetzman** [comment]
What do you mean "use FuzzBench in China" do you mean adding a fuzzer so that we can run it for you here on the FuzzBench service?
Or do you mean running an entire fuzzbench experiment on a machine in China or a cloud in china?

**Comment by jonathanmetzman** [comment]
The main issue I know about here is using gcr.io for docker images
