### ISSUE TITLE
Is  the value of `$LIB_FUZZING_ENGINE` and `$FUZZER_LIB`  same ?

### ISSUE THREAD

**Issue by Ricardio609** [google/fuzzbench#1391]
https://github.com/google/fuzzbench/blob/7cd47833e704b72c7136ce72bdc59eb5964b270b/benchmarks/sqlite3_ossfuzz/build.sh#L41
I'm not sure the value of `$LIB_FUZZING_ENGINE`

**Comment by jonathanmetzman** [comment]
I think so. I think internally we set LIB_FUZZING_ENGINE to the value of FUZZER_LIB.

**Comment by jonathanmetzman** [comment]
See https://github.com/google/fuzzbench/blob/246e344b331db138db6ea09fe9c9501ded666e09/fuzzers/utils.py#L70
