### ISSUE TITLE
number of trials less than expected

### ISSUE THREAD

**Issue by jiradeto** [google/fuzzbench#1425]
I noticed that for some experiments there were missing benchmark trails. For example the experiment from the fuzzbench paper https://www.fuzzbench.com/reports/paper/Main%20Experiment/index.html, for bloaty_fuzz_target benchmark eclipser has only 17 trials while other fuzzers have 20 trials. 

And also in the 7-day experiment: https://www.fuzzbench.com/reports/paper/7%20Day%20Experiment/index.html, for openthread-2019-12-23 benchmark honggfuzz has 8 trials and fairfuzz has only 3 trials whereas the rest have 10 trials.

I wonder if these fuzzing trials were not started at all or they just crashed in the middle of the experiment?

**Comment by jiradeto** [comment]
@jonathanmetzman thanks a lot four your detailed answer. I looked into what you suggested above and notice that the number of trials stored in gs://fuzzbench-data is different than in data.csv.gz. 

For instance, this experiment https://www.fuzzbench.com/reports/2022-02-15-main-fuzzers/index.html is supposed to have 20 trials but I found 40 of trial directories in https://commondatastorage.googleapis.com/fuzzbench-data/index.html?prefix=2022-02-15-main-fuzzers/experiment-folders/re2-2014-12-09-afl/trial-1883601/results/. I'd like to investigate why some trials did not finish but I stumbled upon this inconsistent data. Could you please help to explain?

**Comment by jonathanmetzman** [comment]
Youre probably seeing trials that were preempted.

**Comment by jiradeto** [comment]
from what I see preempted trials were not included in data.csv.gz though. Is it possible to access or get the copy of database (for example local.db of local experiment) of the experiments running on GCP?.

**Comment by jonathanmetzman** [comment]
20 of the afl trials were preempted 20 were not exactly as I said.
[2022-02-15-main.csv](https://github.com/google/fuzzbench/files/9141878/2022-02-15-main.csv)
I can get you the raw data for a few more experiments but I think I understand what is happening here and I don't want to spend much more time into investigating.

**Comment by jiradeto** [comment]
https://github.com/google/fuzzbench/pull/1429 fixed this, local experiment now can start all requested trails.
