### ISSUE TITLE
Benchmark `ffmpeg_ffmpeg_demuxer_fuzzer` fails to build.

### ISSUE THREAD

**Issue by Alan32Liu** [google/fuzzbench#1434]
## `ffmpeg_ffmpeg_demuxer_fuzzer`
> XEVI.c:150:16: error: implicit declaration of function 'reallocarray' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        temp_visual = Xmallocarray(n_visual, sz_VisualID32);
                      ^
./reallocarray.h:44:32: note: expanded from macro 'Xmallocarray'
#define Xmallocarray(n, size)           Xreallocarray(NULL, (n), (size))
                                        ^
./reallocarray.h:39:5: note: expanded from macro 'Xreallocarray'
    reallocarray((ptr), ((n) == 0 ? 1 : (n)), size)
    ^
XEVI.c:150:14: warning: incompatible integer to pointer conversion assigning to 'VisualID32 *' (aka 'unsigned int *') from 'int' [-Wint-conversion]
        temp_visual = Xmallocarray(n_visual, sz_VisualID32);

This was caused by a commit to a dependency (`libXert`) and was temporarily fixed by reverting to one commit earlier (d965a1a8ce9331d2aaf1c697a29455ad55171b36) in #1419.
Now that they pushed another commit in `libXert` and still did not fix this error.

Given this benchmark is not used in experiments, maybe we could remove it (from CI tests)?

**Comment by jonathanmetzman** [comment]
>Now that they pushed another commit in libXert and still did not fix this error.

Do you understand why this error is happening now or no? I can explain, it isn't very complicated.

>Given this benchmark is not used in experiments, maybe we could remove it (from CI tests)?

I think it's used in the crash benchmarks and the fix is fairly easy so I will hold off on removing it for now.

**Comment by Alan32Liu** [comment]
> Do you understand why this error is happening now or no? I can explain, it isn't very complicated.

It is because of the depth level, if I am not mistaken : )
I used that trick to remind myself to check if they will fix the error in future commits, but I guess that was not a good idea in hindsight.
