### ISSUE TITLE
centipede is failing on curl benchmarks

### ISSUE THREAD

**Issue by Navidem** [google/fuzzbench#1477]
As I can see in this [experiment](https://www.fuzzbench.com/reports/experimental/2022-08-13-centipede/index.html) `centipede` successfully build benchmarks. But now I am getting failures locally like:

```
make debug-centipede-curl_curl_fuzzer_http
```
is failing with 

```
...
#20 29.39 + /src/curl_fuzzer/scripts/install_openssl.sh /src/openssl /src/curl_install
#20 29.39 + SRCDIR=/src/openssl
#20 29.39 + INSTALLDIR=/src/curl_install
#20 29.39 + [[ ! -d /src/curl_install ]]
#20 29.39 + [[ x86_64 == \i\3\8\6 ]]
#20 29.39 + ARCH_PROG=
#20 29.39 + EC_FLAG=enable-ec_nistp_64_gcc_128
#20 29.40 + [[ address == \m\e\m\o\r\y ]]
#20 29.40 + ASM_FLAG=
#20 29.40 + pushd /src/openssl
#20 29.40 /src/openssl /src/curl_fuzzer
#20 29.40 + ./config --prefix=/src/curl_install --debug enable-fuzz-libfuzzer -DPEDANTIC -DFUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION no-shared enable-tls1_3 enable-rc5 enable-md2 enable-ssl3 enable-ec_nistp_64_gcc_128 enable-ssl3-method enable-nextprotoneg enable-weak-ssl-ciphers -DFUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION -pthread -Wl,--no-as-needed -Wl,-ldl -Wl,-lm -Wno-unused-command-line-argument -O3 -fsanitize-coverage=trace-loads -DFUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION -fno-builtin -fsanitize-coverage=trace-pc-guard,pc-table,trace-cmp -O2 -gline-tables-only -ldl -lrt -lpthread /lib/weak.o -fno-sanitize=alignment
#20 29.41 Operating system: x86_64-whatever-linux2
#20 29.51 Configuring for linux-x86_64
#20 29.53 target already defined - linux-x86_64 (offending arg: /lib/weak.o)
#20 29.54 Traceback (most recent call last):
#20 29.54   File "<string>", line 1, in <module>
#20 29.54   File "/src/fuzzers/centipede/fuzzer.py", line 47, in build
#20 29.54     utils.build_benchmark()
#20 29.54   File "/src/fuzzers/utils.py", line 82, in build_benchmark
#20 29.54     subprocess.check_call(['/bin/bash', '-ex', build_script], env=env)
#20 29.54   File "/usr/local/lib/python3.8/subprocess.py", line 364, in check_call
#20 29.54     raise CalledProcessError(retcode, cmd)
#20 29.54 subprocess.CalledProcessError: Command '['/bin/bash', '-ex', '/src/build.sh']' returned non-zero exit status 1.
------
executor failed running [/bin/sh -c echo "Run fuzzer_build to build the target" && if [ -z "$debug_builder" ] ; then fuzzer_build; fi]: exit code: 1
make: *** [docker/generated.mk:101252: .centipede-curl_curl_fuzzer_http-builder] Error 1
```

**Comment by Navidem** [comment]
@Alan32Liu could you please take a look?

**Comment by Navidem** [comment]
is it related to https://github.com/google/fuzzbench/pull/1469?

**Comment by Alan32Liu** [comment]
Hi Navid, I reckon we don't have to worry about this error if your integration works fine with other benchmarks.
Here is [a record](https://github.com/google/fuzzbench/issues/1426) of the error.

**Comment by Navidem** [comment]
> is it related to #1469?

Can confirm, the failure still happens.

**Comment by Navidem** [comment]
> Hi Navid, I reckon we don't have to worry about this error if your integration works fine with other benchmarks. Here is [a record](https://github.com/google/fuzzbench/issues/1426) of the error.

Thanks for the pinter, yes the rest of integration works.
I was interested to have the `curl` benchmark working as it seems you were able to get it to work [previously](https://www.fuzzbench.com/reports/experimental/2022-08-13-centipede/index.html).

Is this a new failure?

**Comment by Alan32Liu** [comment]
> is it related to #1469?

Not really, that PR was merely trying to avoid duplication:
Our `weak.c` duplicates `weak_sancov_stubs.cc` from Centipede, that PR removes `weak.c` and is not intended to solve any error.

**Comment by Alan32Liu** [comment]
> > Hi Navid, I reckon we don't have to worry about this error if your integration works fine with other benchmarks. Here is [a record](https://github.com/google/fuzzbench/issues/1426) of the error.
> 
> Thanks for the pinter, yes the rest of integration works. I was interested to have the `curl` benchmark working as it seems you were able to get it to work [previously](https://www.fuzzbench.com/reports/experimental/2022-08-13-centipede/index.html).
> 
> Is this a new failure?

Note that although `Centipede` works for most benchmarks in [the report you linked](https://www.fuzzbench.com/reports/experimental/2022-08-13-centipede/index.html), it has no result under `CURL` due to the same build failure you saw.

Centipede _appeared to work_ in some old reports, because it was not required to link to any weak symbols (in `weak.c` or `weak_sancov_stubs.cc`), hence did not cause the error in the record above.
It did not have to link with weak symbols because the related dataflow tracing flags (`-fsanitize-coverage=trace-loads`, etc.) were not passed to it properly, which is a mistake as that disallows `Centipede` to use dataflow tracing features.

Now that mistake has been fixed, we added the weak symbols to make `Centipede` compatible with most benchmarks, but that also made it incompatible with `CURL`.

**Comment by Navidem** [comment]
Thanks for the explanation :)

**Comment by Navidem** [comment]
Closing this, as it is a known failure.

**Comment by jonathanmetzman** [comment]
Add your fuzzers to unsupported fuzzers please: https://github.com/google/fuzzbench/blob/master/benchmarks/curl_curl_fuzzer_http/benchmark.yaml#L19

**Comment by Navidem** [comment]
> Add your fuzzers to unsupported fuzzers please: https://github.com/google/fuzzbench/blob/master/benchmarks/curl_curl_fuzzer_http/benchmark.yaml#L19

check #1479 please
