### ISSUE TITLE
Stop experiments from starting when benchmark types don't match. 

### ISSUE THREAD

**Issue by oliverchang** [google/fuzzbench#1502]
Currently, if an experiment is started with mismatching benchmark types (i.e. code vs bug), it'll only fail once the experiment gets going a lot later when we try to generate the report:

```
Traceback (most recent call last):
  File "/work/src/experiment/reporter.py", line 73, in output_report
    generate_report.generate_report(
  File "/work/src/analysis/generate_report.py", line 244, in generate_report
    detailed_report = rendering.render_report(experiment_ctx, template,
  File "/work/src/analysis/rendering.py", line 46, in render_report
    return template.render(experiment=experiment_results,
  File "/usr/local/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/usr/local/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/work/src/analysis/report_templates/default.html", line 68, in top-level template code
    {% if experiment.rank_by_median_and_average_rank.size < 2 %}
  File "/usr/local/lib/python3.8/site-packages/jinja2/environment.py", line 471, in getattr
    return getattr(obj, attribute)
  File "/work/src/analysis/experiment_results.py", line 298, in rank_by_median_and_average_rank
    return self._ranking(data_utils.benchmark_rank_by_median,
  File "/work/src/analysis/experiment_results.py", line 277, in _ranking
    key=self._relevant_column),
  File "/work/src/analysis/experiment_results.py", line 163, in _relevant_column
    return 'edges_covered' if self.type == 'code' else 'bugs_covered'
  File "/work/src/analysis/experiment_results.py", line 156, in type
    raise ValueError(
ValueError: Cannot mix bug benchmarks with code coverage benchmarks.
```

We should block this much earlier and stop such experiments from starting in the first place.

**Comment by Navidem** [comment]
Similar to #1466, in the same loop I can add another check to find mismatching benchmarks.

To clarify, we have to bail if there are at least one benchmark of type `code` AND one benchmarks of type `bug`, right?

**Comment by oliverchang** [comment]
Actually I think there's already some validation happening here? https://github.com/google/fuzzbench/blob/1957fc53d1ee2c855d567ba48d16969b0b696ea2/experiment/run_experiment.py#L174

Not sure why we are hitting this error during report generation then. @jonathanmetzman @Alan32Liu ideas?

**Comment by jonathanmetzman** [comment]
> Currently, if an experiment is started with mismatching benchmark types (i.e. code vs bug), it'll only fail once the experiment gets going a lot later when we try to generate the report:
> 
> ```
> Traceback (most recent call last):
>   File "/work/src/experiment/reporter.py", line 73, in output_report
>     generate_report.generate_report(
>   File "/work/src/analysis/generate_report.py", line 244, in generate_report
>     detailed_report = rendering.render_report(experiment_ctx, template,
>   File "/work/src/analysis/rendering.py", line 46, in render_report
>     return template.render(experiment=experiment_results,
>   File "/usr/local/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
>     self.environment.handle_exception()
>   File "/usr/local/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
>     reraise(*rewrite_traceback_stack(source=source))
>   File "/usr/local/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
>     raise value.with_traceback(tb)
>   File "/work/src/analysis/report_templates/default.html", line 68, in top-level template code
>     {% if experiment.rank_by_median_and_average_rank.size < 2 %}
>   File "/usr/local/lib/python3.8/site-packages/jinja2/environment.py", line 471, in getattr
>     return getattr(obj, attribute)
>   File "/work/src/analysis/experiment_results.py", line 298, in rank_by_median_and_average_rank
>     return self._ranking(data_utils.benchmark_rank_by_median,
>   File "/work/src/analysis/experiment_results.py", line 277, in _ranking
>     key=self._relevant_column),
>   File "/work/src/analysis/experiment_results.py", line 163, in _relevant_column
>     return 'edges_covered' if self.type == 'code' else 'bugs_covered'
>   File "/work/src/analysis/experiment_results.py", line 156, in type
>     raise ValueError(
> ValueError: Cannot mix bug benchmarks with code coverage benchmarks.
> ```
> 
> We should block this much earlier and stop such experiments from starting in the first place.

Tell me what experiment is this? It will be easy to repro this bug once I have that info

**Comment by jonathanmetzman** [comment]
I think @Alan32Liu solved this.
