### ISSUE TITLE
[GitHub.IO] Having a publications page

### ISSUE THREAD

**Issue by Alan32Liu** [google/fuzzbench#1544]
Would it help with publicity if we add a page of publications that use `FuzzBench`?

This should give researchers more incentives to start using it.
I recall that I came across `FuzzBench` before joining Google, but I did not use it because I was not sure how many people are using it and how mature it is for research work.
Having a publication page could tell others that it has been widely used by researchers and is worth spending time learning to use it as they can continue relying on it for evaluation in the long term.

**Comment by lszekeres** [comment]
Yes, that's a great idea! 

@Alan32Liu, would you be interested in adding one? I think it could be top level doc like the https://github.com/google/fuzzbench/blob/master/docs/faq.md. @jonathanmetzman, wdyt?

**Comment by Alan32Liu** [comment]
> Yes, that's a great idea!
> 
> @Alan32Liu, would you be interested in adding one? 

Yep, sure!
I can start searching for papers once I complete my task in hand : )

**Comment by Alan32Liu** [comment]
Done!
Here is our [new publication page](https://google.github.io/fuzzbench/publications/) : )
