### ISSUE TITLE
Support ClusterFuzz grouping for bug based benchmarking 

### ISSUE THREAD

**Issue by oliverchang** [google/fuzzbench#1547]

**Comment by jonathanmetzman** [comment]
This is high-priority work

**Comment by Alan32Liu** [comment]
Yep, I am working on this.
For record purposes, this takes two steps:
1. [x] [Expose `ClusterFuzz`'s `crash comparer`](https://github.com/google/clusterfuzz/pull/2941).
2. [x] Bump up the required version of `CF` dependency (to `2.6.0`).
3. [ ] WIP replace [`FuzzBench`'s duplication algorithm](https://github.com/google/fuzzbench/blob/master/analysis/data_utils.py#L141) with `CF`'s `crash comparer`.

I am doing 2&3 in one PR.

**Comment by jonathanmetzman** [comment]
@Alan32Liu have you tested your implementation in an experiment?

**Comment by Alan32Liu** [comment]
I think this is completed : )
