### ISSUE TITLE
Cloud log error

### ISSUE THREAD

**Issue by Alan32Liu** [google/fuzzbench#1550]
Found[ this error message](https://pantheon.corp.google.com/logs/query;cursorTimestamp=2022-11-11T02:46:15.554829786Z;query=--Hide%20similar%20entries%0A-%2528jsonPayload.message%3D~%22pulling%20image,%20retrying%5C.%5C.%5C.%22%2529%0A--End%20of%20hide%20similar%20entries%0A--Hide%20similar%20entries%0A-%2528severity%3D%22INFO%22%0AjsonPayload.message%3D~%22%5B%5E%20%3D%5Ct%5Cn%5Cr%5Cf%5C%22%5C%2528%5C%2529%5C%5B%5C%5D%5C%7C'%5D%2B%5B%5E%20%3D%5Ct%5Cn%5Cr%5Cf%5C%22%5C%2528%5C%2529%5C%5B%5C%5D%5C%7C'%5D%2B%5B%5E%20%3D%5Ct%5Cn%5Cr%5Cf%5C%22%5C%2528%5C%2529%5C%5B%5C%5D%5C%7C'%5D%2B%20not%20found:%20manifest%20unknown:%20Failed%20to%20fetch%20%5C%22%2528%5Cd%7B4%7D-%25280%5B1-9%5D%7C1%5B0-2%5D%2529-%25280%5B1-9%5D%7C%5B12%5D%5B0-9%5D%7C3%5B01%5D%2529%2529%5B%5E%20%3D%5Ct%5Cn%5Cr%5Cf%5C%22%5C%2528%5C%2529%5C%5B%5C%5D%5C%7C'%5D%2B%5C%22%20from%20request%20%5C%22%5B%5E%20%3D%5Ct%5Cn%5Cr%5Cf%5C%22%5C%2528%5C%2529%5C%5B%5C%5D%5C%7C'%5D%2B%2528%5Cd%7B4%7D-%25280%5B1-9%5D%7C1%5B0-2%5D%2529-%25280%5B1-9%5D%7C%5B12%5D%5B0-9%5D%7C3%5B01%5D%2529%2529%5B%5E%20%3D%5Ct%5Cn%5Cr%5Cf%5C%22%5C%2528%5C%2529%5C%5B%5C%5D%5C%7C'%5D%2B%22%0A-labels.logLabel:*%0A-labels.activity_type_name:*%0A-httpRequest:*%0A-jsonPayload.response_code:*%0A-jsonPayload.referer:*%0A-jsonPayload.path:*%0A-jsonPayload.name:*%0A-jsonPayload.code:*%2529%0A--End%20of%20hide%20similar%20entries%0Atimestamp%3D%222022-11-11T02:46:15.554829786Z%22%0AinsertId%3D%22ftwiwfe2z0no%22;timeRange=2022-11-11T02:20:37.922Z%2F2022-11-11T03:41:37.922Z?project=fuzzbench) re-occurring almost every meeting in the log explorer when I was monitoring the new experiments I launched.

Not sure when it started, only know it has started before my commits today.

**Comment by jonathanmetzman** [comment]
I don't know what this is but I know that logs are saved for 30 days max, so unless you remember, we must close this.
In the future, quote the problem instead of only linking please.
