### ISSUE TITLE
ModuleNotFoundError: No module named 'google.cloud.logging.handlers.handlers'

### ISSUE THREAD

**Issue by 18Song** [google/fuzzbench#1609]
when I execute run_experiment.py, this problem comes out. Besides, it shows 
"No matching distribution found for google.cloud.logging.handlers.handlers" 
when I try “pip install google.cloud.logging.handlers.handlers”.
So, how can I get this module?

**Comment by itsleeqian** [comment]
What did you to resolve this issue in the end?

**Comment by 18Song** [comment]
> What did you to resolve this issue in the end? Facing the same issue at the moment..

well.. I don't need this project for now, so I skipped this error report. I don't know how to fix it either..

**Comment by jonathanmetzman** [comment]
Did you run make install-dependencies first?

**Comment by itsleeqian** [comment]
Yes, followed the instructions [from ](https://google.github.io/fuzzbench/getting-started/prerequisites/), and make install-dependencies returned [make: Nothing to be done for 'install-dependencies'.]. 
Make presubmit also runs fine. 

After running run_experiment.py, the console returns this (at the end): 
Traceback (most recent call last):
  File "/work/src/experiment/dispatcher.py", line 29, in <module>
    from common import logs
  File "/work/src/common/logs.py", line 22, in <module>
    from google.cloud.logging.handlers.handlers import CloudLoggingHandler
ModuleNotFoundError: No module named 'google.cloud.logging.handlers.handlers'

**Comment by itsleeqian** [comment]
Ran that, returned this: 
Using default tag: latest
latest: Pulling from fuzzbench/dispatcher-image
846c0b181fff: Already exists 
4163df5d916e: Pull complete 
1db82b7e157c: Pull complete 
00cc1b3aa855: Pull complete 
7d00075242ec: Pull complete 
9d740e8f81ff: Pull complete 
70da513c5877: Pull complete 
05e505750e56: Pull complete 
3b06cd3bba6f: Pull complete 
ea79951b4d36: Pull complete 
cf9e3e88c540: Pull complete 
371a87936733: Pull complete 
8047a2bc799e: Pull complete 
2bd6eb32993e: Pull complete 
a8e09ccb4fc1: Pull complete 
095e1dbeb763: Pull complete 
Digest: sha256:17e374040f7c6c05b5bdb04af42318acda1c4dcadf48ae6c383f617cc74240df
Status: Downloaded newer image for gcr.io/fuzzbench/dispatcher-image:latest

But it still gives the same ModuleNotFoundError.

**Comment by jonathanmetzman** [comment]
Dongge please look into this.

**Comment by Alan32Liu** [comment]
Interesting. This definitely sounds like a python version issue.
Personally, I don't have this problem when running local commands, but let me check with a clean ubuntu env.

**Comment by Alan32Liu** [comment]
@itsleeqian I cannot reproduce this error in a clean `Ubuntu:20.04` docker container with `python3.10`. could you please also check `ptyhon3.10` is used?
In particular, `Makefile` line 51 is
```
python3.10 -m venv .venv || python3 -m venv .venv
```
in which `python3` may lead to using an earlier version of python.

BTW, did you really get `google.cloud.logging.handlers.handlers` or `google.cloud.logging_v2.handlers.handlers`? (The difference is `_v2`.)
I am pretty sure [the former was replaced by the latter](https://github.com/google/fuzzbench/pull/1526/files#diff-2b58b32eee32d4a6c88fdb6a45aba16cac295a0279d513a9b051bf8e93fef8dbR22) last year.

**Comment by itsleeqian** [comment]
Ah, I'm actually following a fork of fuzzbench for a specific fuzzer: [fuzzbench-snappy](https://github.com/vusec/fuzzbench-snappy), which has python3.9.16 as it's python version. 

I specifically got google.cloud.logging.handlers.handlers. The last edit made for the fuzzbench-snappy fork (sept 2022) was before the _v2 patch so maybe that may have been the issue.

**Comment by jonathanmetzman** [comment]
It really would have been nice to tell us you are using a fork.

**Comment by itsleeqian** [comment]
Sorry!!
