### ISSUE TITLE
Support downloading of OSS-Fuzz corpora for use in benchmarks

### ISSUE THREAD

**Issue by jonathanmetzman** [google/fuzzbench#162]
This should be easy to implement but maybe a bit tough to manage in terms of running this service, should we put these benchmarks in the same report?

This feature would be quite nice as it would allow us to determine if a fuzzer can break through a coverage wall that ClusterFuzz encounters from fuzzing (using LibFuzzer, HonggFuzz and AFL).

**Comment by jonathanmetzman** [comment]
This would be even more useful in conjunction with #77. It is needed according to #156.

**Comment by inferno-chromium** [comment]
This is done, although some folks prefer to do this dynamically. I am not sure of the value and it creates more confusion to put oss_fuzz_corpus in some bucket.

**Comment by inferno-chromium** [comment]
Experiment is now running https://www.fuzzbench.com/reports/experimental/2020-10-07-ossfuzzc/index.html with latest corpus (from backup archive). corpora used = https://storage.cloud.google.com/storage/browser/fuzzbench-data/2020-10-07-ossfuzzc/oss_fuzz_corpora
