### ISSUE TITLE
Make logs publicly available.

### ISSUE THREAD

**Issue by jonathanmetzman** [google/fuzzbench#1636]
So users can help debug experiments

**Comment by jonathanmetzman** [comment]
This should have logs in an hour assuming there's no service account issues: https://pantheon.corp.google.com/storage/browser/fuzzbench-logs;tab=objects?project=fuzzbench&prefix=&forceOnObjectsSortingFiltering=false
CC @Alan32Liu

**Comment by jonathanmetzman** [comment]
If this works we need to document how to read logs for experiments (and include links/instructions in reports).

**Comment by jonathanmetzman** [comment]
It works!

**Comment by oliverchang** [comment]
woot!!! can we close this?

**Comment by jonathanmetzman** [comment]
Need #1638 to land and me to update the router and then test it in an experiment and then we can close.

**Comment by jonathanmetzman** [comment]
Testing in an experiment isn't stricly necessary. I updated the router. When I come online tomorrow if I see junk in there like audit logs then I didn't do what I wanted and i'll reopen this. But I think we can close yeah.

**Comment by jonathanmetzman** [comment]
I think this needs more thought. We can't expose details from private experiments
