### ISSUE TITLE
llvm in the build image

### ISSUE THREAD

**Issue by vanhauser-thc** [google/fuzzbench#1641]
Building in the container is problematic as there are two clang versions installed, and there is no directory version distinguish between them.

```
3df0aaa39d2c /afl # /usr/bin/llvm-config --version
10.0.0
3df0aaa39d2c /afl # /usr/local/bin/llvm-config --version
15.0.0git
```

And in AFL++ we can see this being a problem:
>  #8 11.08 [!] WARNING: we have llvm-config version 10.0.0 and a clang version 15.0.0

there is no clang-10 (or a clang pointing to clang-10), only a clang in /usr/local/bin that is clang-15.

So I think the llvm-config-10 is a relict that needs to be removed, and llvm-config needs to point to llvm-config-15 ?

(also llvm-config-10 --bindir shows `/usr/lib/llvm-10/bin/` but there is no clang or clang++ in there either, so I think `/usr/lib/llvm-10` can be removed too)

**Comment by jonathanmetzman** [comment]
Is this in every benchmark's image or just one?

**Comment by vanhauser-thc** [comment]
I looked into three targets (stb_stbi_read_fuzzer, mruby and ... uh forgot which was the third), and they all have llvm-10 in /usr/bin

**Comment by jonathanmetzman** [comment]
This is because the base-builder image ran the centipede install script.
Dongge can you update the version of base-builder we use.

**Comment by vanhauser-thc** [comment]
thank you!

**Comment by Alan32Liu** [comment]
> This is because the base-builder image ran the centipede install script. Dongge can you update the version of base-builder we use.

Sorry, I just noticed this: It seems my email filter did not capture my name in your comment.
Thanks for fixing it! I will edit my email filter so that this won't happen again.

**Comment by jonathanmetzman** [comment]
Dongge probably had filters sending emails from me to /dev/null
😄

**Comment by Alan32Liu** [comment]
> Dongge probably had filters sending emails from me to /dev/null 😄

Please uninstall the supervisory malware that you planted in my OS and discovered this 😫
