### ISSUE TITLE
Build process is killed unexpectedly.

### ISSUE THREAD

**Issue by Alan32Liu** [google/fuzzbench#1648]
A process that builds `Centipede` with benchmark `freetype2-2017` was killed unexpectedly.
The [build log file](https://storage.googleapis.com/fuzzbench-data/2023-01-27-test-local-launch/build-logs/benchmark-freetype2-2017-fuzzer-centipede.txt) did not show any error before cut off.
The [gcloud log](https://pantheon.corp.google.com/logs/query;query=2023-01-27-test-local-launch%0Aseverity%3E%3DWARNING%0Acentipede%0Afreetype2-2017;timeRange=2023-01-25T22:29:52.080Z%2F2023-01-29T23:29:52.080Z;cursorTimestamp=2023-01-29T00:17:53.044294409Z?project=fuzzbench) did not show useful info expect that it `died with <Signals.SIGKILL: 9>`.

The same error also happened on other benchmarks, e.g. [`harfbuzz`](https://pantheon.corp.google.com/logs/query;query=2023-01-27-test-local-launch%0Aseverity%3E%3DWARNING%0Acentipede%0Aharfbuzz%0A;timeRange=2023-01-25T22:29:52.080Z%2F2023-01-29T23:29:52.080Z;cursorTimestamp=2023-01-29T00:17:53.044294409Z?project=fuzzbench).

`make test-run-centipede-freetype2-2017` works perfectly.

Other info:
These processes were part of a locally-launched cloud experiment `2023-01-27-test-local-launch`, with which we want to test if the latest framework changes will affect experiments launched from locally or requested by `requests.yaml`.

**Comment by Alan32Liu** [comment]
> Could this be due to the OOM killer?

I do not recall any change in memory limit or related code since  `centipede`'s last successful experiment on the same benchmark `freetype2-2017` on [18-01](https://storage.googleapis.com/www.fuzzbench.com/reports/experimental/2023-01-18-centipede-test/index.html#freetype2-2017-summary), though.

BTW, this error also affects other fuzzers, e.g. [`afl++`](https://pantheon.corp.google.com/logs/query;cursorTimestamp=2023-01-27T21:26:19.422495177Z;query=2023-01-27-test-local-launch%0Aseverity%3E%3DWARNING%0Aaflplusplus%0Atimestamp%3D%222023-01-27T21:26:18.653986717Z%22%0AinsertId%3D%2213ehs20f18fc8i%22;timeRange=2023-01-25T22:29:52.080Z%2F2023-01-29T23:29:52.080Z?project=fuzzbench).

**Comment by oliverchang** [comment]
Can we see `dmesg` logs on these machines, or any memory usage stats via the GCP console for any indication of OOM?

**Comment by Alan32Liu** [comment]
> Can we see `dmesg` logs on these machines, or any memory usage stats via the GCP console for any indication of OOM?

Thanks!
I did not notice any from the [`gcloud log`](https://pantheon.corp.google.com/logs/query;query=2023-01-27-test-local-launch%0Aseverity%3E%3DDEFAULT%0Acentipede%0Afreetype2-2017;timeRange=2023-01-25T22:29:52.080Z%2F2023-01-29T23:29:52.080Z;cursorTimestamp=2023-01-27T21:30:21.738006556Z?project=fuzzbench).
Would you know any way to access gcloud build instances? They are built with `gcloud builds submit /work/src --config=/tmp/tmpg6woqb8o --timeout=46800s --worker-pool=projects/fuzzbench/locations/us-central1/workerPools/buildpool` and are not [the list of VM instances](https://pantheon.corp.google.com/compute/instances?project=fuzzbench&pageState=(%22instances%22:(%22p%22:1))). I did not find a way to access them in [the docs](https://cloud.google.com/sdk/gcloud/reference/builds) either.
Otherwise, we can probably add some debug log in the code to print memory info.

**Comment by oliverchang** [comment]
Lookign around, I'm not sure if there's a way to view system logs in a CloudBuild worker pool.

Is this happening consistently? If so, might be worth changing the instance type to something with a bit more memory (e.g. from "e2-highcpu-32" to "e2-standard-32" temporarily to see if it fixes things.

**Comment by Alan32Liu** [comment]
I don't recall seeing this in the past and am unsure if it is flaky.
A silly question: We have always been running those experiments in gcloud and it has always worked alright.
Is there a way to see if some default configuration was changed by gcloud?

At the same of running this experiment, I also [request another one from GitHub](https://github.com/google/fuzzbench/pull/1643).
In that experiment, the build logs of [`(centipede, freetype2-2017)`](https://storage.googleapis.com/fuzzbench-data/2023-01-27-test-local-launch/build-logs/benchmark-freetype2-2017-fuzzer-centipede.txt) terminated at the same step, while [`(afl++, libxml2)`](https://storage.googleapis.com/fuzzbench-data/2023-01-27-test-request/build-logs/benchmark-libxml2-v2.9.2-fuzzer-aflplusplus.txt) also terminated at similar steps. 

Temporarily changing the instance type is a good idea. I will see if I can tweak that and launch another experiment on some selected `(fuzzer, benchmark)` pairs.

**Comment by Alan32Liu** [comment]
Testing this in #1650.

**Comment by vanhauser-thc** [comment]
I see the same issue in my experiment:
https://www.fuzzbench.com/reports/experimental/2023-01-27-aflpp/index.html
80% !! of the experiments are failing to build

In the CI they all went green:
https://github.com/google/fuzzbench/actions/runs/4025274106/jobs/6918292861
(only one failing and that is one that is not in the coverage benchmark)

The build logs of the failing experiments all end in the middle of the build process without any errors being seen (`gs://fuzzbench-data/2023-01-27-aflpp/build-logs/benchmark-libjpeg-turbo-07-2017-fuzzer-aflplusplus_at_cm.txt`):
```
c655d92adaf3: Layer already exists
13bbbaf28a73: Layer already exists
546f9db501ca: Layer already exists
31fb99fed15d: Layer already exists
e65a3ff4b09d: Layer already exists
4dc14efe7306: Layer already exists
0002c93bdb37: Layer already exists
```

:-(

**Comment by vanhauser-thc** [comment]
maybe a feature that a benchmark run is aborted if > 25% of the build targets fail would be good? would prevent wasting resources.

**Comment by jonathanmetzman** [comment]
> maybe a feature that a benchmark run is aborted if > 25% of the build targets fail would be good? would prevent wasting resources.

Eh...I think there's too many smart features in FB as is.

**Comment by jonathanmetzman** [comment]
1. I'm not sure this is a centipede issue. Centipede doesn't do anything too exotic in builds since it just uses clang, also Marc is pointing out issues with AFL++'s builds.
2. I'm not sure we should switch to the fancier instances. As we saw in oss-fuzz they can cost a lot more.

**Comment by Alan32Liu** [comment]
> 1. I'm not sure this is a centipede issue. Centipede doesn't do anything too exotic in builds since it just uses clang, also Marc is pointing out issues with AFL++'s builds.

Yep, I don't think it is either.

> 2. I'm not sure we should switch to the fancier instances. As we saw in oss-fuzz they can cost a lot more.

We did not have this issue before, is there something that changed and caused this?

**Comment by Alan32Liu** [comment]
Build failure disappeared after using a higher memory worker pool instance.
More details about the sequence of experiments: https://github.com/google/fuzzbench/pull/1626#issuecomment-1409510034.

**Comment by vanhauser-thc** [comment]
maybe an update in the image (Ubuntu packages) increased the memory footprint? e.g. a docker update now needing more resourcen or something...
Are the docker images builds being performed with `make -j`? reducing the number of parallel processes would also reduce the memory required but of course lengthen the build process.

**Comment by vanhauser-thc** [comment]
can someone please kill the experiment `2023-01-29-aflpp` please? again way too many build errors to be useful, so this is just wasting resources. thank you

**Comment by vanhauser-thc** [comment]
I noticed that an experiment with just 2 fuzzers built & ran cleanly, whereas one with 4 fuzzers had ~20% build failures and one with 5 fuzzers ~70% build failures.

maybe building less fuzzers in parallel on one instance is the easy solution?

**Comment by jonathanmetzman** [comment]
> 2023-01-29-aflpp

Done.

**Comment by jonathanmetzman** [comment]
> I noticed that an experiment with just 2 fuzzers built & ran cleanly, whereas one with 4 fuzzers had ~20% build failures and one with 5 fuzzers ~70% build failures.
> 
> maybe building less fuzzers in parallel on one instance is the easy solution?

I don't think we are building multiple fuzzers on one instance though

**Comment by vanhauser-thc** [comment]
> > I noticed that an experiment with just 2 fuzzers built & ran cleanly, whereas one with 4 fuzzers had ~20% build failures and one with 5 fuzzers ~70% build failures.
> > maybe building less fuzzers in parallel on one instance is the easy solution?
> 
> I don't think we are building multiple fuzzers on one instance though

there is however a correlation between number of fuzzers in the benchmark and build failures.
I pushed a run with 2 fuzzers this morning - and it is running fine without any build failures, like the other one. 
Where I pushed a run with 5 runners it again had 70% failures (the one you canceled for me).

**Comment by vanhauser-thc** [comment]
As I am doing lots of tests at the moment I can tell you this:

if more than 3 fuzzer builds are running (in one benchmark request or more, total count is what is important), then build failures occur. so if I requests 2 experiments at once, both with just 2 variants in there, or if I request 1 experiment with 4 variants, then there are fails. the more variants, the more fails, exponentially.

if I wait until the first requested benchmark is built and then request another (with max 2-3 variants) everything works fine.

**Comment by jonathanmetzman** [comment]
What's the most recent experiment where this was an issue?

**Comment by jonathanmetzman** [comment]
Well I'm quite sure this is a quota issue. These are appearing all over the logs in experiments with build failures.

**Comment by jonathanmetzman** [comment]
Looks like we regularly exceed this 
![image](https://user-images.githubusercontent.com/31354670/219071795-23bd5726-6864-4318-9137-d6c453ad5f59.png)

**Comment by jonathanmetzman** [comment]
We get higher than oss-fuzz wrt this metric. There are two relevant (i think) differences between how we do builds.
1. OSS-Fuzz (in trial builds) has a 1 second sleep.
2. OSS-Fuzz uses python libraries for submitting builds, not gcloud

**Comment by vanhauser-thc** [comment]
that could be the reason.
for the competition this will be an issue as these have to run in parallel?

**Comment by jonathanmetzman** [comment]
> that could be the reason. for the competition this will be an issue as these have to run in parallel?

I'm gonna try my best to fix this before the competition.

**Comment by Alan32Liu** [comment]
Thanks!

**Comment by Alan32Liu** [comment]
I didn't see this error again in the past two week's experiment, shall we close this?

**Comment by oliverchang** [comment]
Let's close. We can always re-open if we see it again. @jonathanmetzman you had a better longer term fix in mind, let's track that in a new bug.
