### ISSUE TITLE
Set an optimization level by default

### ISSUE THREAD

**Issue by jonathanmetzman** [google/fuzzbench#167]
Unless there is a specific reason not to in particular cases, we probably want all fuzzers using the same optimization level to compile benchmarks. This means that we should probably set this in `CFLAGS/CXXFLAGS` before fuzzer.build() is called so that fuzzer integrators don't need to think about this.

**Comment by inferno-chromium** [comment]
If we silently set this in CFLAGS/CXXFLAGS, then it is less obvious to fuzzer author what optimization level is used. i think utils.set_default_optimization_level() explicitly called will be more clear.
