### ISSUE TITLE
how to add a fuzzer based on aflpp cmplog mode

### ISSUE THREAD

**Issue by Ricardo-609** [google/fuzzbench#1704]
I designed a fuzzer based on aflpp cmplog mode, and changed the cmplog instrumentation. when add it to fuzzbench, I have two question:
1. should the instrumentation how to replace vanilla with ` afl-cc and afl-c++`  for using my changed instrumentation ?
2. what should I do if I want to compare with aflpp(enable `-D`)?
Thanks.

**Comment by vanhauser-thc** [comment]
concerning afl++ questions you should @ me in the future.

the easiest you can do is copy the aflplusplus/ folder to a new name and change the git clone + checkout in builder.Dockerfile to match your code.

if you want to compare to aflplusplus with -D you can copy another instance fo aflplusplus/ and change fuzzer.py to add -D to the command line parameters.

test that your variants work by `make test-run-YOUR_VARIANT_DIRECTORY_NAME-stb_stbi_read_fuzzer`

then to request an experiment you git add your directories, and create a new test entry at services/experiment-request.xml
then you create a PR to the fuzzbench repo. when it is merged the test runs.

**Comment by Ricardo-609** [comment]
Thanks! @vanhauser-thc
