### ISSUE TITLE
wpantund benchmark can initiate network connections

### ISSUE THREAD

**Issue by robertswiecki** [google/fuzzbench#171]
The wpantund benchmark can initiate networking connections to remote networks under some conditions. Attaching a testcase for that:

[1788a8b166e1fe4e854bdbb1572e2bb6.00000080.honggfuzz.cov.txt](https://github.com/google/fuzzbench/files/4391761/1788a8b166e1fe4e854bdbb1572e2bb6.00000080.honggfuzz.cov.txt)

```shell
$ strace -f ~/fuzz/wpantund/wpantund-fuzz ~/fuzz/wpantund/corpus/1788a8b166e1fe4e854bdbb1572e2bb6.00000080.honggfuzz.cov
...
openat(AT_FDCWD, "/tmp", O_RDWR|O_EXCL|O_TMPFILE, 0600) = 6
fcntl(6, F_GETFL)                       = 0x418002 (flags O_RDWR|O_LARGEFILE|O_TMPFILE)
fstat(6, {st_mode=S_IFREG|0600, st_size=0, ...}) = 0
write(6, "\235mfProxy:EnabiG:NNN\305SocketPath \""..., 127) = 127
lseek(6, 0, SEEK_SET)                   = 0
read(6, "\235mfProxy:EnabiG:NNN\305SocketPath \""..., 4096) = 127
read(6, "", 4096)                       = 0
close(6)                                = 0
brk(0xb518000)                          = 0xb518000
socket(AF_INET6, SOCK_STREAM, IPPROTO_IP) = 6
connect(6, {sa_family=AF_INET6, sin6_port=htons(4951), inet_pton(AF_INET6, "::ffff:0.0.3.122", &sin6_addr), sin6_flowinfo=htonl(0), sin6_scope_id=0}, 28^C) = ? ERESTARTSYS (To be restarted if SA_RESTART is set)
..
```

I know nothing about wpantund internals, so maybe this can be fixed (if you want to fix it) in the fuzzer harness code (maybe some API option needs to be set).

If not on API level, a quick hack could be to add something like

```C
unshare(CLONE_NEWUSER|CLONE_NEWNET);
```

at the beginning of the file.

I'm not sure if we want to leave current behavior as-is. On one hand it might be a useful case to test fuzzing timeouts, on the other, benchmarks initiating connections over non-loopback sound somehow wrong (and they also add unnecessary timeouts).

**Comment by jonathanmetzman** [comment]
Thanks for noticing this. We could try one of the solutions you propose. Or we could maybe find another benchmark. We can get pretty much anything from OSS-Fuzz, but new benchmarks may have their own problems.

**Comment by jonathanmetzman** [comment]
I took a look at AFL++'s
[fuzzer_stats file](https://github.com/google/fuzzbench/files/4440364/fuzzer_stats.txt)
for the wpantund benchmark.
(`gsutil cp gs://fuzzbench-data/2020-03-19/experiment-folders/wpantund-2018-02-27-aflplusplus_mopt/trial-64082/corpus/corpus-archive-0097.tar.gz ~/Downloads/`).
some of the things I saw were:
```
stability         : 99.81%
unique_hangs      : 0
execs_per_sec     : 202.70
exec_timeout      : 20
```
So in spite of these network connections the benchmark seems to 1. be very deterministic 2.never timesout (ie: takes longer than >20ms) 3. execute relatively fast.
I would certainly be better for the benchmark not to do this but I'm not 100% sure the benchmark behaves badly enough to warrant removing, what do others think?

**Comment by robertswiecki** [comment]
I guess it's because other fuzzers can produce such inputs. I've attached one of them in the first note, and unfortunately it timeouts the coverage binary you use from in fuzzbench, as well as it makes networking connections through it. It's ultimately your choice, but this behavior doesn't seem like a well behaving fuzzing API should behave.

I'm using network namespacing by default in honggfuzz now so it doesn't affect it muchj, but I think this might affect libfuzzer/eclipser performance badly, where they don't use either dynamic timeouts (like afl + clones do) or network namespacing (like honggfuzz does).

The binary I used comes from here: https://storage.cloud.google.com/fuzzbench-data/2020-04-01/coverage-binaries/coverage-build-wpantund-2018-02-27.tar.gz

```
$ ls test/
1788a8b166e1fe4e854bdbb1572e2bb6.00000080.honggfuzz.cov.txt
$ ./cov.wpantund -timeout=10 -merge=1 -dump_coverage=1 out/ test/
INFO: Seed: 4161775567
INFO: Loaded 1 modules   (28888 guards): 28888 [0x867448, 0x8837a8), 
MERGE-OUTER: 1 files, 0 in the initial corpus
MERGE-OUTER: attempt 1
INFO: Seed: 4161781061
INFO: Loaded 1 modules   (28888 guards): 28888 [0x867448, 0x8837a8), 
INFO: -max_len is not provided; libFuzzer will not generate inputs larger than 1048576 bytes
MERGE-INNER: using the control file '/tmp/libFuzzerTemp.4090468.txt'
MERGE-INNER: 1 total files; 0 processed earlier; will process 1 files now

<stalls here>
<Ctrl+C>

^C==4090471== libFuzzer: run interrupted; exiting
SanitizerCoverage: ./cov.wpantund.4090471.sancov: 189 PCs written
MERGE-OUTER: zero succesfull attempts, exiting
```

```
$ ls test/
1788a8b166e1fe4e854bdbb1572e2bb6.00000080.honggfuzz.cov.txt
$ strace -e connect -f ./cov.wpantund -timeout=10 -merge=1 -dump_coverage=1 out/ test/
INFO: Seed: 135418229
INFO: Loaded 1 modules   (28888 guards): 28888 [0x867448, 0x8837a8), 
strace: Process 4090922 attached
MERGE-OUTER: 1 files, 0 in the initial corpus
MERGE-OUTER: attempt 1
strace: Process 4090923 attached
strace: Process 4090924 attached
INFO: Seed: 135425616
INFO: Loaded 1 modules   (28888 guards): 28888 [0x867448, 0x8837a8), 
strace: Process 4090925 attached
INFO: -max_len is not provided; libFuzzer will not generate inputs larger than 1048576 bytes
MERGE-INNER: using the control file '/tmp/libFuzzerTemp.4090921.txt'
MERGE-INNER: 1 total files; 0 processed earlier; will process 1 files now
[pid 4090924] connect(4, {sa_family=AF_UNIX, sun_path="/dev/log"}, 110) = 0
[pid 4090924] connect(5, {sa_family=AF_INET6, sin6_port=htons(4951), inet_pton(AF_INET6, "::ffff:0.0.3.122", &sin6_addr), sin6_flowinfo=htonl(0), sin6_scope_id=0}, 28^C) = ? ERESTARTSYS (To be restarted if SA_RESTART is set)
```

**Comment by jonathanmetzman** [comment]
>I guess it's because other fuzzers can produce such inputs.

Ah very good point, I didn't think of this.

> It's ultimately your choice, but this behavior doesn't seem like a well behaving fuzzing API should behave to me.

I think you've convinced me we should remove it then.

**Comment by darconeous** [comment]
@abtink
