### ISSUE TITLE
Honggfuzz: missing parameter to avoid multithreading

### ISSUE THREAD

**Issue by andreafioraldi** [google/fuzzbench#173]
https://github.com/google/fuzzbench/blob/87ec75dce13f5aade95cb1cf9c5c862dbc04bc74/fuzzers/honggfuzz/fuzzer.py#L53

I just noted that `-n 1` is missing. I'm not sure if this is intended.
By default, hongg uses #cpus / 2 threads, for a fair evaluation it should use a single thread.

**Comment by robertswiecki** [comment]
I think all tests are executed on 1CPU machines, cause the number of threads defaults to 1.

https://storage.googleapis.com/fuzzbench-data/2020-03-19/experiment-folders/bloaty_fuzz_target-honggfuzz/trial-58348/results/fuzzer-log.txt

```
[run_fuzzer] Running target with honggfuzz
Persistent signature found in '/out/fuzz_target'. Enabling persistent fuzzing mode
cmdline:'/out/fuzz_target', bin:'/out/fuzz_target' inputDir:'/out/seeds', fuzzStdin:false, mutationsPerRun:6, timeout:10, mutationsMax:0, threadsMax:1
```

**Comment by inferno-chromium** [comment]
Thanks @robertswiecki for confirming.

**Comment by jonathanmetzman** [comment]
When https://github.com/google/fuzzbench/pull/8 lands this behavior might be a bit of an issue since locally you won't have just one core. Maybe docker can be made to only use N cores.

**Comment by andreafioraldi** [comment]
--cpuset-cpus is the parameter IIRC

**Comment by robertswiecki** [comment]
I assume --cpuset-cpus will set affinity, and honggfuzz uses ```sysconf(_SC_NPROCESSORS_ONLN)``` which under the hood analyses ```/sys/devices/cpu/... sthsth..```.

That's not to say the honggfuzz's way is the canonical way of doing that, more that pretty much noone analyses cpu affinity set to count allowed CPUs.

Maybe it'd be best to simply set ```-n1```

**Comment by lszekeres** [comment]
Perhaps the best would be to do it on both levels: set the fuzzers to use one core (the ones that make this configurable), and also set `--cpus=1` for docker (https://docs.docker.com/config/containers/resource_constraints/#configure-the-default-cfs-scheduler).

**Comment by robertswiecki** [comment]
This seems to use cgroups, which is as fine as using the cpuset here since you're using one VM per fuzzer. But, if you intend to use either, please set '-n1' for honggfuzz, cause it'll still detect the amount of CPUs physically present in the VM. I doubt that docker overwrites the /sys/devices/system/cpu tree with any custom values.
