### ISSUE TITLE
Internal server error when downloading `apt-key.gpg` of Google's `cloud-sdk`

### ISSUE THREAD

**Issue by Alan32Liu** [google/fuzzbench#1754]
This is not likely fixable by us but affects building our `base-image`.
Here is [an example of the error](https://github.com/google/fuzzbench/actions/runs/4274298900/jobs/7443085312#step:8:10714).

Related: [sdk install guide](https://cloud.google.com/sdk/docs/install). The command that fails is:
```
root@c08b95568822:/# curl https://packages.cloud.google.com/apt/doc/apt-key.gpg
Internal Server Error. That's all we know.
```

**Comment by adrianherrera** [comment]
@Alan32Liu do you have a work around? It's pretty frustrating when infrastructure you can't control breaks like this! 😫

**Comment by Alan32Liu** [comment]
> curl https://packages.cloud.google.com/apt/doc/apt-key.gpg

Not sure if you can access this, but FuzzBench's base image is also available from:
```
docker pull gcr.io/fuzzbench/base-image
```
In this way, you don't have to build it from scratch and trigger the error.

I am also actively finding alternative solutions to this and will update here when I find one.
The only good news so far is that [it does not affect all cases and only breaks at a relatively low probability](gcr.io/fuzzbench/base-image).

**Comment by Alan32Liu** [comment]
> @Alan32Liu do you have a work around? It's pretty frustrating when infrastructure you can't control breaks like this! 😫

Hi @adrianherrera,

Not sure if you can access this, but FuzzBench's base image is also available from:
```
docker pull gcr.io/fuzzbench/base-image
```
In this way, you don't have to build it from scratch and trigger the error.

I am also actively finding alternative solutions to this and will update here when I find one.
The only good news so far is that [it does not affect all cases and only breaks at a relatively low probability](gcr.io/fuzzbench/base-image).

**Comment by adrianherrera** [comment]
Cool thanks! I did try that, and while it downloaded the image, I still failed with the same error. However, blowing away my cache appears to have fixed it.

**Comment by Alan32Liu** [comment]
A quick update:
There is nothing we can do at this moment, but hopefully, it will be fixed later today by `gcloud` team as it has affected many people.

**Comment by benoittgt** [comment]
https://github.com/GoogleCloudPlatform/gcsfuse/issues/961#issuecomment-1446073052

    It is an ongoing bug regarding the apt-get key, not the gcsfuse bug. We will update this thread once it gets fixed.

You can use temporary the cached key. See discussion https://github.com/GoogleCloudPlatform/gcsfuse/issues/961#issuecomment-1445711531

**Comment by Alan32Liu** [comment]
I will close this now as the issue is fixed.
