### ISSUE TITLE
SBFT experiments are  frozen

### ISSUE THREAD

**Issue by addisoncrump** [google/fuzzbench#1778]
It appears that the SBFT experiments are frozen:
 - https://www.fuzzbench.com/reports/experimental/2023-03-06-sbft23-cov/index.html
 - https://www.fuzzbench.com/reports/experimental/2023-03-06-sbft23-bug/index.html

Is this intentional? No results seem to have been added past 45 minutes.

**Comment by jonathanmetzman** [comment]
I'll take a look, but sometimes there are bottlenecks saving results. Thanks for being on top of this.

**Comment by Alan32Liu** [comment]
Hi @VTCAKAVSMoACE,

I just checked our google cloud logs of both experiments, and I am pretty sure they are still running fuzzer evaluations.
The report may seem frozen, but `FuzzBench` will automatically update the plot and statistics periodically.

**Comment by jonathanmetzman** [comment]
the reason why "periodically is so infrequent now is probably due to the size of this experiment"

**Comment by jonathanmetzman** [comment]
I think there's something going on with measurement that I need to fix

**Comment by jonathanmetzman** [comment]
I manually fixed the issue. We may need to fix some of the results (some benchmarks should be excluded based on most fuzzers being incompatible): https://www.fuzzbench.com/reports/experimental/2023-03-06-sbft23-cov-manual/index.html

**Comment by addisoncrump** [comment]
Awesome, thank you for the updates. Shall we close this now that final evals have been announced?

**Comment by Alan32Liu** [comment]
Sure!
Thanks again for reporting this to us!
