### ISSUE TITLE
irssi benchmark seems to accumulate state

### ISSUE THREAD

**Issue by robertswiecki** [google/fuzzbench#179]
I've quickly scanned through the irssi benchmark code, and I don't think it's "written correctly". It seems to accumulate states across LLVMTestOneInput() invocations, making it painfully slow after a couple of thousand of iterations (e.g. slowing down to ~20 invocations per second).

I think some fuzzing engines have a tendency to kill fuzzed processes after some time they run (as the fresh instance is capable of processing 1000+ calls per second), and I can do the same in honggfuzz to make it work better, but I think I'd rather suggest exchanging this benchmark with something else (but maybe it can be fixed, dunno, I haven't looked into irssi code that long).

Unless, of course, you also want to test this aspect - i.e. how well fuzzing engines are handling benchmarks which performance might be degrading across LLVMFuzzerTestOneInput() calls.

**Comment by inferno-chromium** [comment]
This would be a really nice if we can detect this kind of badness automatically. We have fuzzer stats, but this currently requires manual analysis. Ideas/thoughts, we should probably use this to filter bad benchmarks ?

**Comment by robertswiecki** [comment]
Unsure, you can always run the libfuzzer's coverage build for say 1h, and perform some heuristics (parsing its exec/s output, and doing some analysis over time), but I don't think these problems are common. 

This benchmark is the only I've seen doing that (as in, starting one server, and sending generated input toward its way), so maybe there's no need to do anything special about it? I guess, one of us (fuzzer engine authors) can spot the problem and let you know.

**Comment by lszekeres** [comment]
Just linking https://github.com/google/fuzzbench/issues/41, as these issues could be spotted more easily if we collected and plotted execs/sec data.

**Comment by jonathanmetzman** [comment]
Linking to the harness for reference: https://github.com/irssi/irssi/blob/e36d6b9b8c1266f9786bbb3c197f32f208f8aaeb/src/fe-fuzz/server.c#L165

I took a look at AFL++'s
[fuzzer_stats file](https://github.com/google/fuzzbench/files/4440406/fuzzer_stats.txt)
for the irssi benchmark.
(`gsutil cp gs://fuzzbench-data/2020-03-19/experiment-folders/irssi_server-fuzz-aflplusplus/trial-59587/corpus/corpus-archive-0097.tar.gz
 ~/Downloads/`).
Some of the things I saw were:
```
execs_per_sec     : 645.51
stability         : 53.84%
unique_hangs      : 0
exec_timeout      : 20
```
1. The benchmark behaves pretty nondeterministically 
2. The benchmark executes pretty fast IMO and doesn't seem to ever timeout.

I'm not sure why you saw such slow execution speeds, but from eyeballing the code I would guess it is accumulating state. Maybe it should be removed.

**Comment by robertswiecki** [comment]
afl restarts the process when it goes over 20 or maybe 40ms per exec (based on some heuristics), but the same slowdown I also observed there. I've added code to honggfuzz to behave similarly, so it doesn't matter that much anymore from my perspective, and we could close it.

**Comment by jonathanmetzman** [comment]
> afl restarts the process when it goes over 20 or maybe 40ms per exec (based on some heuristics), but the same slowdown I also observed there. I've added code to honggfuzz to behave similarly, so it doesn't matter that much anymore from my perspective, and we could close it.

I'm interpreting `unique_hangs: 0` to mean AFL never restarted the binary because it took longer than 20ms. When you made this change to Honggfuzz do you observe it restarting the binary?

**Comment by jonathanmetzman** [comment]
Even though Robert closed this, I'm still unsure if we want to remove this benchmark.

**Comment by robertswiecki** [comment]
I compiled irssi myself (both for afl and for honggfuzz), but based on the oss-fuzz's build file. But maybe there's some difference, cause I remember vanilla afl slowing down (and restarting the fuzzed binary) as easily as it happened with honggfuzz. But you observe no such thing with afl++.

But, there's a slight chance the binary produced by fuzzbench build images might behave differently. Unfortunately I deleted my VM with fuzzbench environment by mistake a couple days ago, so it'll take a day or two to repeat that test with a binary built by fuzzbench scripts.

**Comment by robertswiecki** [comment]
Hm.. I compiled server-fuzz for AFL++ (manually, but still based on oss-fuzz's build.sh file), and ran it with the input seed like that (i.e. with the initial seed corpus only, taken from here: https://github.com/irssi/irssi-fuzzing-corpora/tree/master/server-fuzz-corpus)

```shell
AFL_SKIP_CPUFREQ=1 AFL_NO_AFFINITY=1 AFL_I_DONT_CARE_ABOUT_MISSING_CRASHES=1 ~/src/AFLplusplus/afl-fuzz -i seeds/ -o output -d -m none -- ./aflxx.server-fuzz 2147483647
```

And within maybe a 1 minute the exec speed goes down from ~2000execs/s to ~60execs/sec.

Would it be possible to try to repeat that on your side, I guess you can use the ```server-fuzz``` binary created by the oss-fuzz/fuzzbench builder.

**Comment by robertswiecki** [comment]
Also, I think your testing was simply running it over final corpus generated by AFL++? If so, the slowdown here is gradual, and requires maybe 20-100k fuzzing iterations to go down to painful levels (e.g. 20execs/sec), while a typical corpus from fuzzbench will be on the order of 1k files.

**Comment by jonathanmetzman** [comment]
>Would it be possible to try to repeat that on your side, I guess you can use the server-fuzz binary created by the oss-fuzz/fuzzbench builder

Trying this now. I've seen it go down to ~80 but creep back up to ~200 execs/sec where it seems to be staying (I'm not sure if the number AFL prints to the terminal is cumulative average or average over a recent window).

>Also, I think your testing was simply running it over final corpus generated by AFL++? If so, the slowdown here is gradual, and requires maybe 20-100k fuzzing iterations to go down to painful levels (e.g. 20execs/sec), while a typical corpus from fuzzbench will be on the order of 1k files.

That number was from AFL's stats file, so it was the average number of executions while fuzzing.

I don't think we need to worry about the speed so much though. The accumulation of state (i.e. low stability). I think is probably enough to remove it. 
We still need to come up with criteria for inclusion since misbehaving fuzz targets are pretty common in the real world. But while we don't have any, I think it's fine to mostly exclude misbehaving targets.
