### ISSUE TITLE
How to build fuzzing driver in wpantund-2018-02-27?

### ISSUE THREAD

**Issue by LebronX** [google/fuzzbench#180]
Hi,

I would like to know how to build fuzz driver in wpantund? Because it doesn't describe in build.sh.

**Comment by jonathanmetzman** [comment]
What do you mean build fuzz driver?
Does make build-afl-wpantund-2018-02-27 not work for you?

**Comment by LebronX** [comment]
For example, in `libpng`, we use `target.cc` as the driver to fuzz the project.

So for `wpantund`, are the any command to build the drivers?

**Comment by jonathanmetzman** [comment]
The command I gave above should work for building the wpantund fuzzer. I'm still not sure what you are asking because i don't know why one would want to "build the driver" as opposed to the entire fuzzer.
