### ISSUE TITLE
Only trigger experiments when a comment starts with `/gcbrun`

### ISSUE THREAD

**Issue by Alan32Liu** [google/fuzzbench#1897]
Currently, a `GCB` experiment will be triggered if our comment **_mentions_** `/gcbrun`.

This is problematic because experiments will be launched unintendedly (e.g., when we quote previous `/gcb` commands, or even when we mention `/gcb` in any form).

## Root cause
1. `GCB` trigger simply [checks for `/gcb` without any constraints](https://pantheon.corp.google.com/cloud-build/triggers/edit/fff67372-9e94-4eeb-ab8c-4566ca73badf?project=fuzzbench). 
2. Our `gcbrun_experiment.py` [iterates all previous comments](https://github.com/google/fuzzbench/blob/56caa83e81bc59a1389367c6bd29d46fd35d03e6/service/gcbrun_experiment.py#L57) to find the latest valid `/gcb` command, which might have already been run.

## Proofs
1. [This example](https://github.com/google/fuzzbench/pull/1893#issuecomment-1716770892) quotes an old command and modifies its experiment name. However, it triggers an experiment with the old name, indicating we launch the latest valid experiment command.
2. [This example](https://github.com/google/fuzzbench/pull/1893#issuecomment-1716780709) includes a random `/gcb` command in the middle of the sentence. It also triggers the same old experiment, confirming the same conclusion.

## Propose fix
Change https://github.com/google/fuzzbench/blob/56caa83e81bc59a1389367c6bd29d46fd35d03e6/service/gcbrun_experiment.py#L56-L57
to
```python
 if not body.startswith(RUN_EXPERIMENT_COMMAND_STR): 
     return None 
```

## Justification
1. Based on our setting on Google Cloud, all `/gcb` commands will immediately trigger an experiment, there is no need to search back in history for an old command.
2. If we need to run an old command, we can always add a new comment for it.

@jonathanmetzman: Did I miss anything?
If it looks good to you, I will implement the fix proposed above.

**Comment by jonathanmetzman** [comment]
you mean `[/]gcbrun` run right?

**Comment by jonathanmetzman** [comment]
I think this is a good idea.

**Comment by Alan32Liu** [comment]
> you mean `[/]gcbrun` run right?

Yep, fixed.
