### ISSUE TITLE
expose BENCHMARK env variable to builder container

### ISSUE THREAD

**Issue by lmrs2** [google/fuzzbench#191]
It would be useful to expose a BENCHMARK env variable to the runner. This way fuzzer.py can use it adjust the building code (fuzzer.py). For example: currently lafintel uses the PWD env variable to detect the php benchmark. Cleaner to have a BENCHMARK variable

**Comment by jonathanmetzman** [comment]
I think we provide it to the runner container, just not to the fuzzer.py when run in the *builder*.

**Comment by inferno-chromium** [comment]
Should we give oss-fuzz.yaml's project name instead of BENCHMARK variable ? Also, how to get right project name for non-oss-fuzz benchmark. i think this issue is just https://github.com/google/fuzzbench/issues/45

**Comment by jonathanmetzman** [comment]
>Should we give oss-fuzz.yaml's project name instead of BENCHMARK variable? Also, how to get right project name for non-oss-fuzz benchmark.

Right, this would mean inconsistent behavior between OSS-Fuzz benchmarks and regular ones so I don't think there's a reason to give project name instead of the benchmark.

>Also, how to get right project name for non-oss-fuzz benchmark. i think this issue is just #45

I don't think it's quite the same though I don't really understand #45. We do give $BENCHMARK in the runner, we don't give it in the builder.

**Comment by lmrs2** [comment]
I think I made a mistake. I meant expose BENCHMARK in the builder.

>

**Comment by inferno-chromium** [comment]
also this needs fixing - https://github.com/google/fuzzbench/pull/193/files#diff-2549469637697094671972023bf99edd to not use PWD.

**Comment by vanhauser-thc** [comment]
isnt this similar to #227 ? so maybe close 227?

**Comment by inferno-chromium** [comment]
@vanhauser-thc , #227 is about exposing fuzz target / fuzzer path as FUZZ_TARGET env variable. This one is about exposing benchmark name as BENCHMARK. Similar small bugs, but not same.

**Comment by vanhauser-thc** [comment]
@inferno-chromium ok then what is which value? I would expect FUZZ_TARGET is libpng-1.2.56 and BENCHMARK is 2020-04-20-aflplusplus, but from the conversation it seems to be the opposite?

And are both variables already available?

**Comment by inferno-chromium** [comment]
FUZZ_TARGET is actually full path to fuzz target binary.
/out/<fuzzer_name>

BENCHMARK is like libpng-1.2.56

Some of these vars are not available during build process. And some like FUZZ_TARGET is only set for non oss-fuzz benchmarks. will try to fix this soon to avoid confusion.

**Comment by inferno-chromium** [comment]
This is already exposed to runner, see
https://github.com/google/fuzzbench/blob/master/experiment/resources/runner-startup-script-template.sh#L28

Need to fix builder.
