### ISSUE TITLE
Encounter problems when adding a new fuzzer

### ISSUE THREAD

**Issue by zhangteng0526** [google/fuzzbench#1960]
When I follow the steps on the official website to add a new fuzzer, a problem occurs during make, as shown in the picture.
There are no rules for making goals
![image](https://github.com/google/fuzzbench/assets/49060609/79a4e872-6408-45f4-bf4d-1fd40512244f)

**Comment by zhangteng0526** [comment]
make: *** No rule to make target 'build-nestfuzz-libpng-1.2.56'.  Stop.

**Comment by DonggeLiu** [comment]
The benchmark name has to be a benchmark dir under [the benchmark directory](https://github.com/google/fuzzbench/tree/master/benchmarks).
In your example, it could be [libpng_libpng_read_fuzzer](https://github.com/google/fuzzbench/tree/master/benchmarks/libpng_libpng_read_fuzzer).

**Comment by DonggeLiu** [comment]
Feel free to reopen this if it does not work.
