### ISSUE TITLE
Ankou: Request for new fuzzer integration

### ISSUE THREAD

**Issue by inferno-chromium** [google/fuzzbench#198]
https://github.com/SoftSec-KAIST/Ankou

@Jiliac, @sangkilc - can you please consider integration Ankou with our fuzzer benchmarking platform. We would love to have the community benefit from your research work.

**Comment by Jiliac** [comment]
Hello. Thanks for pinging us :-) We are preparing for it.

**Comment by zchcai** [comment]
Hi @Jiliac, how about the progress of integration in your side? Maybe I can help. :)

Zhicheng
FuzzBench

**Comment by Jiliac** [comment]
Ah sorry I totally missed the activity on this thread. Thanks a ton for handling it @zchcai !

**Comment by jonathanmetzman** [comment]
We have results https://www.fuzzbench.com/reports/2020-05-28/index.html, but I think they aren't accurate in Ankou's case because the integration has some bugs: https://github.com/google/fuzzbench/issues/392
