### ISSUE TITLE
generate_report exceptions - 1) exception before first snapshot period 2) exception for one fuzzer usecase.

### ISSUE THREAD

**Issue by mboehme** [google/fuzzbench#215]
I've been trying to run FuzzBench on GCP and get the following error during report generation.
```
Traceback (most recent call last):
  File "/work/src/experiment/reporter.py", line 43, in output_report
    in_progress=in_progress)
  File "/work/src/experiment/generate_report.py", line 123, in generate_report
    in_progress)
  File "/work/src/analysis/rendering.py", line 41, in render_report
    in_progress=in_progress)
  File "/work/.venv/lib/python3.7/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/work/.venv/lib/python3.7/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/work/.venv/lib/python3.7/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/work/src/analysis/report_templates/default.html", line 81, in top-level template code
    src="{{ experiment.critical_difference_plot }}">
  File "/work/.venv/lib/python3.7/site-packages/jinja2/environment.py", line 471, in getattr
    return getattr(obj, attribute)
  File "/work/src/analysis/experiment_results.py", line 169, in critical_difference_plot
    average_ranks = self.rank_by_median
  File "/work/src/analysis/experiment_results.py", line 109, in rank_by_median
    self._experiment_snapshots_df, data_utils.rank_by_median)
  File "/work/src/analysis/data_utils.py", line 189, in experiment_pivot_table
    benchmark_blocks = experiment_snapshots_df.groupby('benchmark')
  File "/work/.venv/lib/python3.7/site-packages/pandas/core/frame.py", line 5810, in groupby
    observed=observed,
  File "/work/.venv/lib/python3.7/site-packages/pandas/core/groupby/groupby.py", line 409, in __init__
    mutated=self.mutated,
  File "/work/.venv/lib/python3.7/site-packages/pandas/core/groupby/grouper.py", line 598, in get_grouper
    raise KeyError(gpr)
KeyError: 'benchmark'

Message: Error generating HTML report.
```

My data bucket contains the corpus for all trials, but my report bucket remains empty after the experiment. Let me know what else you need.

**Comment by inferno-chromium** [comment]
Sorry, this is a harmless exception that shows up in first 15 minutes of experiment once when no data is measured. After the first reading, then it goes away.

@lszekeres - can you please fix this.

**Comment by mboehme** [comment]
Yes, this might be it. The database doesn't have any entries.

```
postgres=> SELECT * FROM trial;                                                                                                      
 id |  fuzzer   | experiment |     benchmark      | time_ended |        time_started        
----+-----------+------------+--------------------+------------+----------------------------
  1 | entropic  | 10min      | bloaty_fuzz_target |            | 2020-04-10 05:06:53.627576
  2 | entropic  | 10min      | bloaty_fuzz_target |            | 2020-04-10 05:06:53.769494
  3 | entropic  | 10min      | bloaty_fuzz_target |            | 2020-04-10 05:06:53.771469
  4 | entropic  | 10min      | bloaty_fuzz_target |            | 2020-04-10 05:06:53.949327
  5 | entropic  | 10min      | bloaty_fuzz_target |            | 2020-04-10 05:06:53.811318
(5 rows)

postgres=> SELECT * FROM snapshot;                                                                                                                                                                                                                                           
 time | trial_id | edges_covered 
------+----------+---------------
(0 rows)
```
Now, I still need to figure out why the database doesn't fill up.

**Comment by inferno-chromium** [comment]
Did your experiment run for longer, like more than 30 minutes, then generate_report starts working. Do you see trial vm instances running on GCP's vm instances page ?

**Comment by mboehme** [comment]
Yes, I saw the 5 runners (one for each trial) in the 10min experiments. I'll try 1 hour now.

**Comment by inferno-chromium** [comment]
ah are you running just one fuzzer ? Laszlo told me that generate_report / comparison only works for 2+ fuzzers.

**Comment by mboehme** [comment]
In 1h experiment, the `snapshot` table filled up in 15min increments, but the report bucket is still empty. I'll add another fuzzer and repeat the 1h experiment.

**Comment by mboehme** [comment]
All good. The HTML report is properly generated when more than one fuzzer is run for at least 30 minutes.

**Comment by inferno-chromium** [comment]
Sorry about confusion @mboehme , we will fix these two bugs. Thanks for your feedback.

If you felt anything was unclear/incorrect on this documentation - https://google.github.io/fuzzbench/running-your-own-experiment/, please do file an issue as well. We want to smoothen the process for a new researcher.

**Comment by mboehme** [comment]
No, the GCP setup for FuzzBench went like a breeze.

I like the result-database-centric design. There is one compute instance for each trial and each instance writes to a common database. I can just run another round of experiments with the same name to add more trials or to add another fuzzer configuration to the results. You could even copy the results of the baseline (which don't change) to the next round of experiments.

Thanks so much for making FuzzBench available!

**Comment by inferno-chromium** [comment]
> No, the GCP setup for FuzzBench went like a breeze.
> 
> I like the result-database-centric design. There is one compute instance for each trial and each instance writes to a common database. I can just run another round of experiments with the same name to add more trials or to add another fuzzer configuration to the results. You could even copy the results of the baseline (which don't change) to the next round of experiments.

Just fyi, Adding a new fuzzer to existing experiment name might work, but it easily comes in the no warranty zone if same fuzzer was there in old and new experiment. it is recommended to use new experiment name with each experiment. you can easily combine results across experiment names by running generate_report.py.

Make sure local psql connection is set as per https://google.github.io/fuzzbench/running-your-own-experiment/setting-up-a-google-cloud-project/#set-up-the-database
source .venv/bin/activate
PYTHONPATH=/path/to/fuzzbench/repo python3 generate_report.py -n <any_name> -d <output_dir> <experiment_1> <experiment_2>....

@jonathanmetzman - maybe need to document this (sorry i think we removed it before, but i think folks might need this).

> 
> Thanks so much for making FuzzBench available!

**Comment by lszekeres** [comment]
> Sorry, this is a harmless exception that shows up in first 15 minutes of experiment once when no data is measured. After the first reading, then it goes away.

Yep, sorry about that, with https://github.com/google/fuzzbench/pull/265 we give a meaningful error.

> ah are you running just one fuzzer ? Laszlo told me that generate_report / comparison only works for 2+ fuzzers. 

With https://github.com/google/fuzzbench/pull/264 single fuzzer is supported too.
