### ISSUE TITLE
curl benchmark: the faster it's being tested, the lower the coverage results

### ISSUE THREAD

**Issue by robertswiecki** [google/fuzzbench#224]
I've been working recently on new coverage modes in honggfuzz, and implemented a faster version (at least for curl) of libfuzzer's 8-bit-counters but based on good, old pc-guards. It's way faster for curl, where ~80k edges are instrumented.

The former version goes up to 17k execs/sec on a single core, and the latter up to 45k execs/secs. Aaaand, the later version is way slower in gaining coverage than the former one, despite pretty much the same info being gathered in both modes.

I was thinking initially that there's a problem with my implementation, but I've checked/debugged it for a long time with nothing obvious found. Also, no other benchmarks show similar characteristics.

At some point I've added an artificial usleep() to the faster mode, to even the execs/sec in both modes, aaand it helped. It seems that making fuzzing slower, makes it get better results.

I'm not 100% sure yet, but I think there's some problem with the curl benchmark, and maybe because of time-outs it implements, maybe because of something else (still some timing condition I guess) it prevents it from being tested full-speed.

Still looking at it though.

For removing the benchmark it is too early IMO, so filling this in to coordinate progress on analysing this conspiracy theory in more details :)

**Comment by jonathanmetzman** [comment]
Thanks for checking this out Robert.
@bagder We've been using the `curl_fuzzer_http` fuzz target to benchmark fuzzers (like AFL, Honggfuzz etc) and Robert noticed this interesting behavior. Do you have any ideas why this might be happening?

Any help on this would be greatly appreciated!

**Comment by jonathanmetzman** [comment]
@robertswiecki, I have a question about how you measure coverage. Is this coverage reported by honggfuzz while fuzzing or will taking the corpus and measuring the coverage offline show that the slower run is better?

**Comment by robertswiecki** [comment]
@jonathanmetzman It's both. Both honggfuzz and the coverage binary show that the coverage gains (both in number of edges reached, and number of created inputs) are smaller, the faster fuzzing is.

E.g. after 1 minute running of both the faster and slower versions:

Slower (8bit-counters)

```
------------------------[  0 days 00 hrs 01 mins 00 secs ]----------------------
  Iterations : 971,800 [971.80k]
  Mode [3/3] : Feedback Driven Mode
      Target : ./8bitcnt.curl_fuzzer_http
     Threads : 1, CPUs: 16, CPU%: 207% [12%/CPU]
       Speed : 14,510/sec [avg: 16,196]
     Crashes : 0 [unique: 0, blacklist: 0, verified: 0]
    Timeouts : 0 [1 sec]
 Corpus Size : 810, max: 8,192 bytes, init: 31 files
  Cov Update : 0 days 00 hrs 00 mins 01 secs ago
    Coverage : edge: 4,768/80,691 [5%] pc: 163 cmp: 141,790
---------------------------------- [ LOGS ] ------------------/ honggfuzz 2.1 /-

$  rm *.sancov; mkdir out; rm out/*; ASAN_OPTIONS=soft_rss_mb=2048 ./cov.curl -reduce_inputs=0 -merge=1 -dump_coverage=1 out/ corpus2
...
SanitizerCoverage: ./cov.curl.1284822.sancov: 3829 PCs written
...
```

Faster (pc-guards + counters)
```
------------------------[  0 days 00 hrs 01 mins 00 secs ]----------------------
  Iterations : 2,732,172 [2.73M]
  Mode [3/3] : Feedback Driven Mode
      Target : ./curl_fuzzer/curl_fuzzer_http
     Threads : 1, CPUs: 16, CPU%: 109% [6%/CPU]
       Speed : 47,461/sec [avg: 45,536]
     Crashes : 0 [unique: 0, blacklist: 0, verified: 0]
    Timeouts : 0 [1 sec]
 Corpus Size : 485, max: 8,192 bytes, init: 31 files
  Cov Update : 0 days 00 hrs 00 mins 00 secs ago
    Coverage : edge: 4,589/75,863 [6%] pc: 160 cmp: 142,950
---------------------------------- [ LOGS ] ------------------/ honggfuzz 2.1 /-
$ rm *.sancov; mkdir out; rm out/*; ASAN_OPTIONS=soft_rss_mb=2048 ./cov.curl -reduce_inputs=0 -merge=1 -dump_coverage=1 out/ corpus
...
SanitizerCoverage: ./cov.curl.1284893.sancov: 3724 PCs written
...
```

The numbers (differences) are not big here, but repeatable.

Consider this artificially slower (with usleep(50) added between runs in honggfuzz) 1 min run of the same pcguard's version (which was originally way faster at 47k iterations/sec, now at 6k iterations / sec). The number of edges is bigger: 4,758 vs 4,589 as counted by honggfuzz, and 3871 vs 3724  as counted by the coverage binary, and 784 vs 485 produced inputs.

```
------------------------[  0 days 00 hrs 01 mins 00 secs ]----------------------
  Iterations : 381,034 [381.03k]
  Mode [3/3] : Feedback Driven Mode
      Target : ./curl_fuzzer/curl_fuzzer_http
     Threads : 1, CPUs: 16, CPU%: 48% [3%/CPU]
       Speed : 6,165/sec [avg: 6,350]
     Crashes : 0 [unique: 0, blacklist: 0, verified: 0]
    Timeouts : 0 [1 sec]
 Corpus Size : 784, max: 8,192 bytes, init: 31 files
  Cov Update : 0 days 00 hrs 00 mins 00 secs ago
    Coverage : edge: 4,758/75,863 [6%] pc: 164 cmp: 149,080
---------------------------------- [ LOGS ] ------------------/ honggfuzz 2.1 /-

$ rm *.sancov; mkdir out; rm out/*; ASAN_OPTIONS=soft_rss_mb=2048 ./cov.curl -reduce_inputs=0 -merge=1 -dump_coverage=1 out/ corpus
...
SanitizerCoverage: ./cov.curl.1285375.sancov: 3871 PCs written
```

I know it seems a bit funky, but I have no other explanation so far.

**Comment by bagder** [comment]
Sorry, it sounds super crazy but unfortunately I can't provide any good guesses as to why! I don't know the specifics here but it certainly feels like there's an error somewhere in the measuring or something as adding plain sleeps can make make it report increased coverage.

**Comment by jonathanmetzman** [comment]
> Sorry, it sounds super crazy but unfortunately I can't provide any good guesses as to why! I don't know the specifics here but it certainly feels like there's an error somewhere in the measuring or something as adding plain sleeps can make make it report increased coverage.

OK, thanks for the prompt reply!

**Comment by jonathanmetzman** [comment]
@robertswiecki hmmm...very bizarre. I'll try to play around with this when I get a chance, but I don't really have ideas for why this happens. Maybe we will need to find another benchmark.

**Comment by vanhauser-thc** [comment]
@robertswiecki for me the obvious step would be - what edges does the slower one discover that the faster one doesn't? that might answer your question. (my guess - it could be timing things in curl, timeout or measurement or ...)

**Comment by robertswiecki** [comment]
I think I solved this mystery, it's actually a combination of things in the curl fuzzer and in honggfuzz.

Honggfuzz implements a score function, which it applies to given inputs based on how fast they execute, how small they are, how many cases they generated etc: https://github.com/google/honggfuzz/blob/a2d3a2d5d252eb0d84314310b984512f511eb074/input.c#L461

And then it prefers those with better score.

Now, curl_fuzzer comes into play, with this check: https://github.com/curl/curl-fuzzer/blob/82eb95b410cc84579b8f9d663f2a7e38f3bdb41f/curl_fuzzer.cc#L68

``` 
if(tlv_rc != TLV_RC_NO_MORE_TLVS) {
    /* A TLV call failed. Can't continue. */
    goto EXIT_LABEL;
  }
```

It turns out that it's relatively easy for a fuzzer to generate some list of TLV values with random tags sizes and values, but it's not that easy to generate TLVs' sizes which will fit the remaining input length, esp. for those TLV sets closer to the end of the iput.

So, many (most, probably >70%) of inputs fail on this check and return early (probably because size in TLV is too big/small). Honggfuzz started preferring those inputs, because they execute quick.

After commenting out the score function, both versions execute more or less at the same time. I must adjust this scoring, so it's not that aggressive.

Sorry for the noise, we can close this issue. Though, it was a fun challenge to solve :)

**Comment by vanhauser-thc** [comment]
That was also my analysis - original afl prefers (among other factors) fast running inputs. But this results in shallow fuzzing. So I added two schedulers that ignore that and concentrate on new paths (mmopt) or unique edges (rare) and surprise they are better

**Comment by robertswiecki** [comment]
Yeah, I turned some engineering knobs here and there to the same effect and, at least for curl, it got way better: https://github.com/google/honggfuzz/commit/75749045240d9d9e520d94e3abed335094bdec83

The goal was similar: prefer inputs which already generated other inputs more, and put less emphasis on execution speed or size of the input. I can add overall size of edges (or, new edges) soon as a new factor.
