### ISSUE TITLE
Use URL fragments on report pages so individual benchmark results can be linked to

### ISSUE THREAD

**Issue by jonathanmetzman** [google/fuzzbench#235]
Currently there is some support for URL fragments on our report pages, if one copies the link to a benchmark on the sidebar you get a URL for that benchmark. This should be improved in some small ways:
1. The wrong benchmark is highlighted in the side menu (e.g. when you go to https://www.fuzzbench.com/reports/2020-04-14/index.html#woff2-2016-05-06 "vorbis-2017-12-11" is darkened). This is probably some simple off-by-one error.
2. The URL should change when scrolling on the page or when one clicks on a benchmark. This will make the feature much more visible and usable.

**Comment by lszekeres** [comment]
> 2. The URL should change when scrolling on the page or when one clicks on a benchmark. This will make the feature much more visible and usable.

A more common way to do this is providing anchor links when someone hovers over a section title. Here's an example: https://github.blog/2020-04-16-remote-work-working-together-when-were-not-together/

**Comment by lszekeres** [comment]
https://github.com/google/fuzzbench/pull/239 adds such links.

**Comment by jonathanmetzman** [comment]
I think the off by one issue still occurs

**Comment by jonathanmetzman** [comment]
It doesn't seem to happen anymore. https://www.fuzzbench.com/reports/2020-06-09/index.html#php_php-fuzz-parser-summary goes to the right place.
