### ISSUE TITLE
Add a Jupyter/Colab notebook to make custom analyses of experiment results easy

### ISSUE THREAD

**Issue by lszekeres** [google/fuzzbench#268]

**Comment by lszekeres** [comment]
@wideglide Thanks for [sharing](https://github.com/google/fuzzbench/issues/366#issuecomment-633069478) your [colab notebook](https://colab.research.google.com/drive/1-_6oUD4Xz3Rm9LXpgNbns6vwteW5_hbL) for comparing the  different ranking methods of the [analysis](https://github.com/google/fuzzbench/tree/master/analysis) library. It's a very nice notebook! 

Would you be interested in checking it into the repo? 

(You can do it even from Colab: File/Save a copy in GitHub.) 

Thanks!

**Comment by wideglide** [comment]
Sure thing!  Hadn't even seen this issue. :)
Where would you want something like this?  In the analysis folder or somewhere else?

**Comment by lszekeres** [comment]
Great, thanks a lot!

> Where would you want something like this?  In the analysis folder or somewhere else?

Yes, could be say `analysis/notebooks/ranking.ipynb`
