### ISSUE TITLE
Important: Add time feature in report generation

### ISSUE THREAD

**Issue by inferno-chromium** [google/fuzzbench#276]
This will make it easy to generate report at 1h,6h,12h,24h

**Comment by jonathanmetzman** [comment]
Sorry, I'm not sure I understand what this is for, can you explain please?

**Comment by inferno-chromium** [comment]
Requested by a researcher to ease in generating reports around different times and compare results.
Like how do results at 6h compare to the one at 24h. This can be easily done in generate_report.py with a --end_time or something argument.
