### ISSUE TITLE
[GCP] Runners are not started.

### ISSUE THREAD

**Issue by mboehme** [google/fuzzbench#285]
I pulled master and tried to evaluate libfuzzer against honggfuzz in 5 trials for 1 hour on 1 benchmark (mbedtls_fuzz_dtlsclient). It doesn't generate the report anymore. The web bucket is empty, the experiments-result folder does not exist in the data bucket, the SQL database is empty, and the Error Reporting gives the following error:
```
ValueError: Empty experiment data. Message: Error generating HTML report.
at validate_data (/work/src/analysis/data_utils.py:21)
at generate_report (/work/src/analysis/generate_report.py:132)
at output_report (/work/src/experiment/reporter.py:43)
```

I deleted authorization keys of the service account. I deleted the old and set up a new SQL database (incl. `alembic upgrade head`). I cleaned out the container registry (by deleting the `container` folder in the corresponding bucket). I cleaned out the Cloud Builds (by deleting `source` folder in the corresponding bucket). It recreates the containers and builds, when I start the dispatcher. The dispatcher runs properly. I SSH'ed into a random runner: `docker images` and `docker ps -a` return empty-handed. Is the recent setup gcr.io/fuzzbench-specific? Any suggestion to debug?

**Comment by jonathanmetzman** [comment]
Thanks for this report.
Sorry about this problem, we are looking into it now.
To debug you can look at /tmp/runner-log.txt on the runners host. 
(I'm going to file an issue to copy this file to the data bucket).

**Comment by inferno-chromium** [comment]
2020-05-01 09:57:41.621 PDT
Executed command: "nice -n 5 python3 -u -c import fuzzer; fuzzer.fuzz('/out/seeds', '/out/corpus', '/out/fuzz_dtlsclient')" returned: -9.

other part of logs seem normal, let me try running this locally.

**Comment by jonathanmetzman** [comment]
>experiments-result

You mean experiments-folders right?
