### ISSUE TITLE
afl++ benchmark batches

### ISSUE THREAD

**Issue by vanhauser-thc** [google/fuzzbench#286]
@jonathanmetzman 
I dont want to spam the announcement thread so I think communicating in a dedicated issue is better?

you wanted to run the next batch today. Will that happen? And if so - when do you roughly expect the measurements to be finished? With the changes I expect the total time to be less than the previous runs.

We have so many developments in our repo we want/need to measure we get into a backlog and need to plan the order etc.

so also - what is the minimum and maximum number of entries that make sense to run in a batch?

in about 2-3 iterations I hope we can put a "best setup" for default fuzzing in fuzzbench. until then lots of testing :)

**Comment by jonathanmetzman** [comment]
>@jonathanmetzman
>I dont want to spam the announcement thread so I think communicating in a dedicated issue is better?

Probably, discussing everything experiment related on one issue might become to noisy.

>you wanted to run the next batch today. Will that happen? 

Yep. Will start it shortly

>And if so - when do you roughly expect the measurements to be finished? With the changes I expect the total time to be less than the previous runs.

Still not sure. 
The main issue with measuring is that we use a 96 core machine to measure the output of many more cores, this issue still exists.
We're still discussing how to fix this (it's more difficult when we want FuzzBench to work outside of Google Cloud). It's probably the highest priority issue we have now, but fixing it is a bit of an invasive change.

I might break up the afl++ experiment into two so we get 192 measurement cores.
I'd guess measuring finishes 2-4 days after the trials depending on whether I break it up or not.


>so also - what is the minimum and maximum number of entries that make sense to run in a batch?

I think 10 is a maximum for now. 2-3 is probably a good minimum.

**Comment by jonathanmetzman** [comment]
This is blocked on #291 landing btw.

Also, we've made some changes that could possibly affect all fuzzers like 252 (https://github.com/google/fuzzbench/pull/252) since 2020-04-21 and 2020-04-20-afl++. I personally think it's fine to compare these two even if it isn't 1000% scientific to do so. Are you fine with this? I personally don't think there will be any real difference by building the targets in docker images with less unnecessary dependencies.

**Comment by jonathanmetzman** [comment]
Sorry also blocked on #293.

**Comment by vanhauser-thc** [comment]
if there are block then there are blocks.
If you want you can merge the new run with the results of the old ones if you want. I get the resultsdata myself and import it to Excel and run my analysis, so for me it is not necessary. I only need the standard report table with the median edges found for each target :)

if there are 192 cores than optimal should be 4 or 8 fuzzers as this would cleanly divide. I will keep this in mind for the future.

**Comment by jonathanmetzman** [comment]
I started 2 new experiments for the AFL based fuzzers: https://www.fuzzbench.com/reports/2020-05-01-aflplusplus-1/index.html and 2020-05-01-aflplusplus-2 which should be up soon.

**Comment by vanhauser-thc** [comment]
if the two benchmarks have the "huge table" difference - how do you compare if with or without is better if the fuzzers run in both a different in their setups can cant be compared?

besides huge tables, irsii and wolff - were other changes have been made that could impact performance?

e.g. the 8 april and 20 april results have a difference that cant be their configuration. the 8 april one has much less coverage results over the board so seems to have run overall slower

**Comment by jonathanmetzman** [comment]
> if the two benchmarks have the "huge table" difference - how do you compare if with or without is better if the fuzzers run in both a different in their setups can cant be compared?
> 

I reverted this before running the AFL++ experiments.

> besides huge tables, irsii and wolff - were other changes have been made that could impact performance?
> 

We didn't get rid of woff permanently, just for that one experiment. I can remove that from the combined experiment.

> e.g. the 8 april and 20 april results have a difference that cant be their configuration. the 8 april one has much less coverage results over the board so seems to have run overall slower

I don't know what's causing this. Probably some sort of bug I need to fix.

**Comment by vanhauser-thc** [comment]
ah so the two afl++ runs are basically all equal except that one has more targets than the other?

**Comment by vanhauser-thc** [comment]
How far through are the tests?
because the results so far seem not to be comparable to the 2020-04-20 run.
ngram2 and ngram4 from 2020-04-20 have both better results (~73.500) than ngram3 and ngram5 from this run (~70.800 edges so far). (and in general 2020-04-20 have higher results than this run - these are just the one where it can clearly be seen it makes no sense :) )

(and the batch from 2020-04-01 is also noticable lower in the total edge count than 2020-04-20)

(of course I am comparing the same test cases - excluding those that are not in both)

**Comment by jonathanmetzman** [comment]
>ah so the two afl++ runs are basically all equal except that one has more targets than the other?

Yep, I just broke up the experiment so we'd get the benefit of using two measurers instead of one.

> How far through are the tests?

They look done to me. All benchmarks have results for 24 hours for 20 trials for all fuzzers.
I think the reason why the page says they are incomplete is related to me restarting measuring process in the middle.

> because the results so far seem not to be comparable to the 2020-04-20 run.
> ngram2 and ngram4 from 2020-04-20 have both better results (~73.500) than ngram3 and ngram5 from this run (~70.800 edges so far). (and in general 2020-04-20 have higher results than this run - these are just the one where it can clearly be seen it makes no sense :) )
> 
> (and the batch from 2020-04-01 is also noticable lower in the total edge count than 2020-04-20)
> 
> (of course I am comparing the same test cases - excluding those that are not in both)

Sorry, I'm not really noticing what's higher in 2020-04-20. Could you tell me what's a specific benchmark you see where results look odd.

**Comment by vanhauser-thc** [comment]
I select two where this is most visible:

test|ngram3|ngram4|ngram5
libxml2-v2.9.2|4200|4375|4123
vorbis-2017-12-11|988|1002.5|984.5

**Comment by vanhauser-thc** [comment]
Can you run the following in the next batch please?
```
          - aflplusplus_lto_cmplog_mopt2
          - aflplusplus_ngram3_cmplog_mopt2
          - aflplusplus_ngram3_cmplog_mopt2_17
          - aflplusplus_instrim_cmplog_mopt2
          - aflplusplus_instrim_laf_mopt2
          - aflplusplus_instrim_laf_mopt2_17
```
the LTO one might not compile all targets though, but that would be fine for me.
See PR#295

**Comment by jonathanmetzman** [comment]
> I select two where this is most visible:
> 
> test	ngram3	ngram4	ngram5	ngram4-coe
> libxml2-v2.9.2	4200	4375	4123	4032
> vorbis-2017-12-11	988	1002.5	984.5	996.5
> Edit: I also added ngram4-coe which is from the current run (so only ngram4 is from 2020-04-20). this does not make it better :) it is 2nd best in vorbis, which would add to the theory that there is a notable difference. in libxml however it is the worst entry.

I'm looking into this now. Right now the tooling for reproducing an old experiment isn't great so it might be prohibitively expensive to investigate this thoroughly. 
One thing I did find is the coverage build binary (fuzz-target) for libxml from 2020-04-20-aflplusplus, 2020-05-01-aflplusplus-1, 2020-05-01-aflplusplus-2 all have the same md5 d733c6fef5e3216d07794799985a2334. I frankly am somewhat surprised by this, maybe we accidentally used the old build but assuming there is no bug that leaves the following possibilites:
1. Something changed in the measurer that caused this.
2. Something changed in AFL++ that caused this and the results are in fact correct.
3. Something changed in the way fuzzbench runs fuzzers making results incorrect.

I downloaded the last corpus from a trial of ngram5 and a trial of ngram4 for libxml. I found that the ngram4 one had higher coverage (OK sample size is insignificant, but if you could script this and report back ngram5 results look higher than ngram4 results, that would be very interesting, as it would probably be a bug in measurer. Note that you can't get the exact coverage because of instability (e.g. locally I found trial 14426 has 4133 edges locally, fuzzbench says 4136).

**Comment by jonathanmetzman** [comment]
The simplest way to figure out if something changed would probably be to add back a fuzzer from each experiment, run them again and see.

**Comment by jonathanmetzman** [comment]
> Edit: I also added ngram4-coe which is from the current run (so only ngram4 is from 2020-04-20). this does not make it better :) it is 2nd best in vorbis, which would add to the theory that there is a notable difference. in libxml however it is the worst entry.
> 
> The difference between ngram4-coe and ngram4 on vorbis is about 10 edges. Maybe just chance caused this?

Sorry I meant to write a new reply, not edit yours.

**Comment by vanhauser-thc** [comment]
> One thing I did find is the coverage build binary (fuzz-target) for libxml from 2020-04-20-aflplusplus, 2020-05-01-aflplusplus-1, 2020-05-01-aflplusplus-2 all have the same md5 d733c6fef5e3216d07794799985a2334. I frankly am somewhat surprised by this

two compilations can not have the same MD5 sums.
simply because:
```
  gettimeofday(&tv, &tz);
  rand_seed = tv.tv_sec ^ tv.tv_usec ^ getpid();
  AFL_SR(rand_seed);  // <= srandom()
```
and every edge gets a `random() % MAP_SIZE` value

so every binary will look different (unless the srandom value is the same by cheer luck ... 2^32 ...)

**Comment by jonathanmetzman** [comment]
> > One thing I did find is the coverage build binary (fuzz-target) for libxml from 2020-04-20-aflplusplus, 2020-05-01-aflplusplus-1, 2020-05-01-aflplusplus-2 all have the same md5 d733c6fef5e3216d07794799985a2334. I frankly am somewhat surprised by this
> 
> two compilations can not have the same MD5 sums.
> simply because:
> 
> ```
>   gettimeofday(&tv, &tz);
>   rand_seed = tv.tv_sec ^ tv.tv_usec ^ getpid();
>   AFL_SR(rand_seed);  // <= srandom()
> ```
> 
> and every edge gets a `random() % MAP_SIZE` value
> 
> so every binary will look different (unless the srandom value is the same by cheer luck ... 2^32 ...)

I'm perfectly willing to grant that a bug caused this, and I'll look into it because it is suspicious. But this build is done using libFuzzer's instrumentation which doesn't use randomness for the map like AFL.

**Comment by vanhauser-thc** [comment]
> But this build is done using libFuzzer's instrumentation which doesn't use randomness for the map like AFL.

what do you mean? the instrumentation (compilation) is done via afl-clang-fast and various options which modify how the binary is to be instrumented

**Comment by jonathanmetzman** [comment]
> > But this build is done using libFuzzer's instrumentation which doesn't use randomness for the map like AFL.
> 
> what do you mean? the instrumentation (compilation) is done via afl-clang-fast and various options which modify how the binary is to be instrumented

Sorry I wasn't specific, I meant the build we use to measure coverage (i.e. fuzzers/coverage).
I didn't check the afl builds.

**Comment by vanhauser-thc** [comment]
ah ok, yeah that is fine and a good thing (afl's `paths found` value is not specific).
but does not change that the binaries have to be different every time.

**Comment by jonathanmetzman** [comment]
> ah ok, yeah that is fine and a good thing (afl's `paths found` value is not specific).
> but does not change that the binaries have to be different every time.

I understand. I was pointing out the measurers were the same because I made some changes to the way benchmarks could have been built and thought this may have been a source of differences between the experiments. But because the measurer/coverage binary build of libxml is exactly the same I was ruling this out.

And I don't think this is due to a bug either. When I run `make build-coverage-` and get a shell with `docker run -ti gcr.io/fuzzbench/builders/coverage/libxml2-v2.9.2:latest /bin/bash` the md5 of fuzz-target is the same d733c6fef5e3216d07794799985a2334, so the possibility that differences were caused by the build changing but we used a stale for libxml one is also not the cause.

**Comment by vanhauser-thc** [comment]
@jonathanmetzman btw we figured out why afl performs so much better than afl++
its the trace pc guard implementation. it has a better performance and a bit more coverage than the classic afl-llvm-pass. so weird. the instrim results will likely catch up a bit, but overall still not get to the pc guard implementation. 
So in a future patch we will too change the default to trace pc guard here.
But: LTO should be better than trace pc guard. I have a 7% performance increase and similar coverage.

**Comment by jonathanmetzman** [comment]
>it has a better performance and a bit more coverage than the classic afl-llvm-pass. it has a better performance and a bit more coverage than the classic afl-llvm-pass.

Is the performance better in general or just fuzzbench? In general would be a bit surprising to me since (and I think the docs point this out) it's slower instrumentation since a callback is inserted rather than an inline add. On fuzzbench that isn't so surprising since that is what the measurer/coverage build uses (thus there might be slight bias).

**Comment by vanhauser-thc** [comment]
the performance is in general better. I verified against my own targets (e.g. both libtiff and test-instr).
And yes because of the context switch it should be slower. But it is 5% faster.

**Comment by jonathanmetzman** [comment]
> the performance is in general better. I verified against my own targets (e.g. both libtiff and test-instr).
> And yes because of the context switch it should be slower. But it is 5% faster.
> 

Very nice find! One of many cases where reasoning doesn't match reality in fuzzing.

> Edit: and another thing why afl++ was worse: we skipped instrumenting single block functions because I assumed there would be no value. but tests have shown that is not the case, especially with c++ targets.

Also interesting, that also makes sense to me in theory.

**Comment by vanhauser-thc** [comment]
The new benchmark test ... timed out? dunno.
`The following fuzzers do not have enough samples: ...` and then a list of fuzzers.
e.g. freetype got only to 3:30 for 12 fuzzers.

**Comment by jonathanmetzman** [comment]
> The new benchmark test ... timed out? dunno.
> `The following fuzzers do not have enough samples: ...` and then a list of fuzzers.
> e.g. freetype got only to 3:30 for 12 fuzzers.

Sorry, it didn't timeout. We used preemptible instances which means many didn't finish. But most of the experiment finished and I think the results are still usable, just that the heuristics we use for missing data generated a bad report because they aren't meant for a situation like this. [Here](https://www.fuzzbench.com/reports/2020-05-14-aflplusplus-2/index.html) is a report from the same data where I tuned the heuristics to be less aggressive.

Note that in most cases we have >10 trials per fuzzer-benchmark. But if you expand "Sample statistics and statistical significance" you can see that often there is a fuzzer-benchmark that has 9 or 8 (when the graphs say "9 trials/fuzzer" it's talking about the minimum number of trials any one fuzzer has that reaches the time).

Until #352 lands the reports for preemptible experiments may need to be manually fixed. After it lands, I think there won't be much noticeable difference between the experiments we used to do without preemptibles and the new experiments we will do with preemptibles.

**Comment by jonathanmetzman** [comment]
Also note the experiment is 23 hours instead of 24 because preemptibles cannot last longer than 24 hours (we do 23 so we have some breathing room for startup times and what not).

**Comment by vanhauser-thc** [comment]
23h is OK ... but means I cannot compare the results to previous runs which are 24h.
well, better than nothing.
when can you start the next batch? #348

**Comment by jonathanmetzman** [comment]
> 23h is OK ... but means I cannot compare the results to previous runs which are 24h
> well, better than nothing.

I think we can, see the `--end-time` option in `generate_report.py`

(you probably also want to set `FUZZER_SAMPLE_NUM_THRESHOLD=.4` and `BENCHMARK_SAMPLE_NUM_THRESHOLD=.4` to deal with those heuristics I mention earlier in the thread).

> when can you start the next batch? #348

Today or tomorrow.

**Comment by vanhauser-thc** [comment]
The benchmark is done. I guess you have again generate the final report by hand?

**Comment by jonathanmetzman** [comment]
Here you go: https://www.fuzzbench.com/reports/2020-05-20-aflplusplus-2/index.html

**Comment by vanhauser-thc** [comment]
thank you!

**Comment by vanhauser-thc** [comment]
@jonathanmetzman  the new run https://www.fuzzbench.com/reports/2020-05-24/index.html seems to be ... weird ...

it looks like that the aflplusplus setup is the old one from 2 weeks ago.
The setup of aflplusplus is the same as afl, just with a little bit faster internals.

and it is missing aflplusplus_optimal.

**Comment by vanhauser-thc** [comment]
no ... there is something wrong in the aflplusplus setup. damn ...

**Comment by vanhauser-thc** [comment]
Pushed a fix. we lost around 10-20% performance. no wonder aflplusplus looks so bad.

**Comment by vanhauser-thc** [comment]
Ankou now builds correctly. Can we have a run with the three afl++ instances and Ankou and combine it with 2020-05-24 ? :)

**Comment by jonathanmetzman** [comment]
Sure. I'll probably do it today or tomorrow with https://github.com/google/fuzzbench/pull/352 since it seemed to work on the toy examples I've done. Hopefully there won't be an issues but if there are it might need to be run again with fixes applied.

**Comment by vanhauser-thc** [comment]
@jonathanmetzman  Can you please restart the 2020-05-28 run and include aflplusplus? the one in the previous report is the broken build (as in: no optimization where it should have been, and negatively over optimization in other areas)

**Comment by vanhauser-thc** [comment]
hmm also building php failed. #389 fixes that. its a oneliner.

**Comment by jonathanmetzman** [comment]
> @jonathanmetzman Can you please restart the 2020-05-28 run and include aflplusplus? the one in the previous report is the broken build (as in: no optimization where it should have been, and negatively over optimization in other areas). overall a 15-20% performance decrease ...

I'll do another experiment with afl++, I'm not sure I want to terminate the current one, it will give me useful results anyway. Worst case scenario we can rerun afl_optimized in that experiment as well.

**Comment by vanhauser-thc** [comment]
thats fine too. maybe I get the "shmem" variant on track until then. it is really good in several benchmarks, but is very, very bad in most. there must be a bug, deadlock, ... dunno.

**Comment by vanhauser-thc** [comment]
did the run went wrong? the report has not been updated for many hours

**Comment by jonathanmetzman** [comment]
The report on this experiment will be messed up. But here's one I made with a fix applied: https://commondatastorage.googleapis.com/fuzzbench-reports/2020-05-28/index.html

**Comment by jonathanmetzman** [comment]
By the end of the experiment, and with my patch we should get a good report.

**Comment by vanhauser-thc** [comment]
how long will it take until the benchmark is done?

**Comment by jonathanmetzman** [comment]
I think ~10 hours from now it should have results that are similar to or better than the other preemptible experiments I've done. I think if my patch is used the report will be decent at that point. Then I think over the next day some more trials will complete until 2 days from now everything should finish.

**Comment by jonathanmetzman** [comment]
In a few hours I will go offline until Saturday night so someone else would need to generate the report with my patches.

**Comment by vanhauser-thc** [comment]
no worries, Saturday night it is then.
How comparable will be the results vs 2020-05-24?

**Comment by jonathanmetzman** [comment]
> no worries, Saturday night it is then.
> How comparable will be the results vs 2020-05-24?

The results at the end should be the same except for ending at 23 hours instead of 24.
But I can truncate 2020-05-24 to 23 hours when I combine them.
This is assuming I didn't have any bugs in my implementation, which will be the new standard for running experiments eventually.

**Comment by jonathanmetzman** [comment]
I updated the reports.
For many benchmarks results are near what we would expect from non-preemptibles. 
For others, not so much. But I'm not sure my scheduler patch is at fault. It looks like ankou in particular is broken in a way that is unrelated to the scheduler. Will investigate tomorrow or Monday.

**Comment by vanhauser-thc** [comment]
yes the results for optimal look as they should. I compared them to the other run and the win is clear against afl and comes very close to honggfuzz. with the missing php result and depending on which ranking method is used honggfuzz or aflplusplus_optimal are first. good result :)
