### ISSUE TITLE
master cannot pass "make presubmit"

### ISSUE THREAD

**Issue by zchcai** [google/fuzzbench#308]
Current master branch has one failed at "``make presubmit``".

To reproduce: ``git clone https://github.com/google/fuzzbench ; cd fuzzbench ; git submodule update --init ; make install-dependencies ; source ./vene/bin/activate ; make presubmit``

https://github.com/google/fuzzbench/blob/41aa9b4267907185bd51514a6fb335ff70f4990d/experiment/test_measurer.py#L347

E            assert 0 == 3798

Reference: https://google.github.io/fuzzbench/getting-started/prerequisites/

**Comment by jonathanmetzman** [comment]
Can you post the output. It doens't reproduce on my desktop (the same one I use for developing).

**Comment by jonathanmetzman** [comment]
Ah OK it makes sense why this test would fail. I'll disable it by default.

**Comment by zchcai** [comment]
It seems relate to the TODO: https://github.com/google/fuzzbench/blob/41aa9b4267907185bd51514a6fb335ff70f4990d/experiment/test_measurer.py#L340

**Comment by jonathanmetzman** [comment]
I suspected something else. Could you run this command and post the output?
`./fuzzbench/experiment/test_data/test_measure_snapshot_coverage/freetype2-2017-coverage`

**Comment by jonathanmetzman** [comment]
My guess is that this test relies on running a binary that won't run on every machine where make install-deps succeeds.

**Comment by zchcai** [comment]
./fuzzbench/experiment/test_data/test_measure_snapshot_coverage/freetype2-2017-coverage: error while loading shared libraries: libarchive.so.13: cannot open shared object file: No such file or directory

**Comment by zchcai** [comment]
`sudo apt-get install libarchive13` will solve this issue. Thanks for double checking.

**Comment by jonathanmetzman** [comment]
I think we shouldn't have dependency on that though. And I'm sure someone will run into a libc issue no matter what binary we use. I think it's probably better to not have tests that run binaries on by default (@inferno-chromium any thoughts? I guess in CF we do have this).

**Comment by inferno-chromium** [comment]
since we are running in ci, that is fine, otherwise we can add the dependency in that dir and change rpath.
