### ISSUE TITLE
curl benchmark and openssl

### ISSUE THREAD

**Issue by vanhauser-thc** [google/fuzzbench#320]
I noticed that the curl benchmark also downloads and compiles+instruments openssl.
Why is that done? I think the target is curl not openssl, hence openssl should not be instrumented (and just openssl-dev installed & used).

Normally I would not care, but the LTO instrumentation of the curl targets needs so much memory because of this that 16GB RAM + 16GB swap is not enough :)

**Comment by jonathanmetzman** [comment]
> I noticed that the curl benchmark also downloads and compiles+instruments openssl.
> Why is that done? I think the target is curl not openssl, hence openssl should not be instrumented (and just openssl-dev installed & used).
> 
> Normally I would not care, but the LTO instrumentation of the curl targets needs so much memory because of this that 16GB RAM + 16GB swap is not enough :)

I think curl instruments everything. Sometimes in OSS-Fuzz there are bugs in dependencies or in a project's use of dependencies so it *may* make sense to instrument them.

**Comment by vanhauser-thc** [comment]
The question is though if it makes sense. if it just pollutes the map and increases the run time ...

but for me its not a memory issue, I debugged it further. it just seems that it does not work with LTO (a few targets dont, e.g. ffmpeg). I will close this for now, I guess this is an oss-fuzz issue to instrument so it is useful.
