### ISSUE TITLE
Experiment is not ended and dispatcher stays alive even at end of experiment.

### ISSUE THREAD

**Issue by inferno-chromium** [google/fuzzbench#322]
Looks like measurer is not finished, scheduler did finish.

**Comment by jonathanmetzman** [comment]
What experiment was this?

**Comment by inferno-chromium** [comment]
aarya-test-6, one i did on friday (only 1 hour test one).

**Comment by jonathanmetzman** [comment]
Do you know why it didn't finish? I think under the current setup, the measurer is pretty fragile and won't finish if any trials are missing snapshots.

**Comment by inferno-chromium** [comment]
Nothing was missing (simple 2 trial experiment - http://commondatastorage.googleapis.com/fuzzbench-reports/aarya-test-6/index.html), but i will try debugging more today with a new one. looks like a regression.

**Comment by inferno-chromium** [comment]
Something is up with
all_trials_ended. measure_all_trials is complete, it returns False. but all_trials_ended is not causing the break to happen.

                all_trials_ended = scheduler.all_trials_ended(experiment)

                if not measure_all_trials(experiment, max_total_time, pool, q):
                    # We didn't measure any trials.
                    if all_trials_ended:
                        # There are no trials producing snapshots to measure.
                        # Given that we couldn't measure any snapshots, we won't
                        # be able to measure any the future, so break now.
                        break

**Comment by inferno-chromium** [comment]
Investigating, i atleast see a bug in wrong bool result of gcloud.delete_instances.

**Comment by jonathanmetzman** [comment]
Seems related to #262. I think the gcloud delete results are not reliable. Instead we should query google cloud to see what is running.

**Comment by jonathanmetzman** [comment]
But if it's just a regresion we won't need to do this.
