### ISSUE TITLE
Use one source of truth for building images

### ISSUE THREAD

**Issue by jonathanmetzman** [google/fuzzbench#336]
Currently, making changes to building images is extremely bug prone.
Steps for building images are defined in docker/build.mk and gcb/*.yaml.
Instead we should have one source of truth for building images and generate these files from those steps.

**Comment by jonathanmetzman** [comment]
The system should define the relationships between docker images using something like Python classes.

**Comment by inferno-chromium** [comment]
This is tracked in build simplification issue now.
