### ISSUE TITLE
Logscale X-axis on the time scales on coverage/time graphs

### ISSUE THREAD

**Issue by gamozolabs** [google/fuzzbench#40]
Without having a log scale X axis the first part of the fuzz run (typically the densest), it's pretty hard to read meaningful data from the charts.

-B

**Comment by inferno-chromium** [comment]
Two solutions:
* Either use log scale
* Or switch to interactive graphs just for coverage growth plot [that helps to select a part of time interval, allow selecting only particular fuzzers, etc].

We might start with 1) and in a few weeks, switch to 2)
