### ISSUE TITLE
Add graphs of coverage/iter

### ISSUE THREAD

**Issue by gamozolabs** [google/fuzzbench#42]
While a graph including coverage over time is the _true_ performance of a fuzzer, this does not allow for controlling for the hardware, threads, scaling, etc. Having a graph which shows coverage over fuzz cases allows seeing the "density" of the fuzzer. It's a really meaningful graph for determining how frequently the fuzzer makes a good input.

-B

**Comment by inferno-chromium** [comment]
Just fyi, corpus snapshots (every 15 min) are available to analyze at https://console.cloud.google.com/storage/browser/fuzzbench-data/sample/experiment-folders/

Can you explain a little more on what you want to see. you want to see coverage achieved vs total number of testcases in corpus at a particular time ?

**Comment by gamozolabs** [comment]
Yeah, in this case it'd just be what I think AFL calls execs. Or runs of an input through the target application. It's just useful because it doesn't allow hardware differences to skew results. For example, if I spun up AFL on my 1000 core server, it'd perform much better than AFL in this dataset.

Effectively, log the number of execs on each coverage increase, and stamp that information wherever it's being logged. Allowing the data to contain the execs at the time the coverage was found, and the existing time.

(Note: I haven't looked at the raw data yet to see what is already present, sorry on travels)

**Comment by inferno-chromium** [comment]
Thanks, looks similar to https://github.com/google/fuzzbench/issues/41. Closing.
