### ISSUE TITLE
Benchmark libFuzzer's comparison instrumentation feature

### ISSUE THREAD

**Issue by jonathanmetzman** [google/fuzzbench#427]
@kcc + @morehouse would like some hard evidence on the utility of this feature (it's similar to lafintel).
This feature has a runtime part, and a compile-time instrumentation part.
In our discussion, we decided there are two ways this can be tested:
1. Set `-use_cmp=0` at runtime. If this does as well as normal libFuzzer, then the feature is useless.
2. Turn it off at compile time. This is the right way to do it. If 1 is worse we need this method to verify that it isn't the slowdown without the benefit causing problems.

@kcc/@morehouse could you make a copy of `fuzzers/libfuzzer` that sets the right flags here https://github.com/google/fuzzbench/blob/master/fuzzers/libfuzzer/fuzzer.py#L27 for option 2? Alternatively can you give me the flags to set and I'll do it.

Thanks!

**Comment by morehouse** [comment]
I'm pretty sure we just need `-fsanitize=fuzzer-no-link -fno-sanitize-coverage=trace-cmp`.

**Comment by jonathanmetzman** [comment]
https://www.fuzzbench.com/reports/2020-06-12/index.html
I think the findings here are similar to @vanhauser-thc 's on comparison instrumentation.
In most cases not doing comparison instrumentation seems very slightly better (probably because of improved speed).
But in some cases like libpcap_fuzz_both, it makes an extremely large difference.

**Comment by jonathanmetzman** [comment]
CC @dokyungs 
I think we've done this already. Closing.
