### ISSUE TITLE
make install-dependencies fails

### ISSUE THREAD

**Issue by andreafioraldi** [google/fuzzbench#43]
Hi,
I runned `make install-dependencies fails` and it failed with:

```
source .venv/bin/activate && python3 -m pip install -r requirements.txt
/bin/sh: 1: source: not found
Makefile:20: recipe for target '.venv/bin/activate' failed
make: *** [.venv/bin/activate] Error 127
```

I'm on Ubuntu 18.04.4 where /bin/sh is symlinked to dash and not bash, where source is not available.

I solved invoking bash directly, however, I'm not opening a PR cause this is a rude workaround:

```
include docker/build.mk

VENV_ACTIVATE := .venv/bin/activate

${VENV_ACTIVATE}:
	python3 -m pip install --user virtualenv
	rm -rf .venv
	virtualenv -p `which python3` .venv
	bash -c "source ${VENV_ACTIVATE} && python3 -m pip install -r requirements.txt"

install-dependencies: ${VENV_ACTIVATE}

presubmit: install-dependencies
	bash -c "source ${VENV_ACTIVATE} && python3 presubmit.py"

format: install-dependencies
	bash -c "source ${VENV_ACTIVATE} && python3 presubmit.py format"

licensecheck: install-dependencies
	bash -c "source ${VENV_ACTIVATE} && python3 presubmit.py licensecheck"

lint: install-dependencies
	bash -c "source ${VENV_ACTIVATE} && python3 presubmit.py lint"

typecheck: install-dependencies
	bash -c "source ${VENV_ACTIVATE} && python3 presubmit.py typecheck"

docs-serve:
	cd docs && bundle exec jekyll serve --livereload
```

**Comment by lszekeres** [comment]
Thanks for the report! Can you check if https://github.com/google/fuzzbench/pull/44 solves the issue? Thanks!

**Comment by jonathanmetzman** [comment]
Laszlo, thanks for looking into this.
I think there's another (rare) issue on new systems.
```
virtualenv -p `which python3` .venv
/bin/sh: 1: virtualenv: not found
```
I think it needs to be `~/.local/bin/virtualenv` to use the virtualenv installed by the command.

**Comment by ammaraskar** [comment]
Just fyi you can invoke `virtualenv` with `python3 -m virtualenv` to avoid passing the `-p` flag.

**Comment by lszekeres** [comment]
Thanks @jonathanmetzman and @ammaraskar, fixed that too in https://github.com/google/fuzzbench/pull/44, PTAL.

**Comment by jonathanmetzman** [comment]
Nice! Thanks ammar!
