### ISSUE TITLE
Improve measurement of coverage

### ISSUE THREAD

**Issue by jonathanmetzman** [google/fuzzbench#430]
This involves some of the things discussed in https://github.com/google/fuzzbench/issues/77 and https://github.com/google/fuzzbench/pull/421
But there are other important features I think we want here like coverage reports I'll add more details later.

**Comment by jonathanmetzman** [comment]
@Shadoom7 can you link to this issue when making pull requests or opening issues about individual problems? It will make tracking, much easier. Thanks!

**Comment by Shadoom7** [comment]
Yeah, of course.
