### ISSUE TITLE
rename `experiment_path.gcs` to `experiment_path.filestore`

### ISSUE THREAD

**Issue by zchcai** [google/fuzzbench#447]
After #444 merged, this function will not only help for cloud running, where we use Google Cloud Services, but also convert to a local filestore path:
https://github.com/google/fuzzbench/blob/552c297719fe8f475ac7291f3585a93dd645f55f/common/experiment_path.py#L26-L33

Thus I suggest to rename this function to `experiment_path.filestore`, instead of `experiment_path.gcs`.

There are several usages: https://github.com/google/fuzzbench/search?q=exp_path.gcs&unscoped_q=exp_path.gcs

**Comment by zchcai** [comment]
Clarify: it does not affect local running if we don't rename it. This is just a function name change for better readability.

**Comment by jonathanmetzman** [comment]
Go ahead, rename it.
