### ISSUE TITLE
error and warning: Corpus not found for cycle

### ISSUE THREAD

**Issue by zchcai** [google/fuzzbench#449]
## *When* does this occur?

When running *local* experiments, there may exist some error messages like the following:
```
INFO:root:Measuring cycle: 6. Extras: {'fuzzer': 'fairfuzz', 'benchmark': 'jsoncpp_jsoncpp_fuzzer', 'trial_id': '18', 'cycle': '6'}
ERROR:root:Executed command: "cp /usr/local/home/alice/fuzzbench/fuzzbench-data/multitest/experiment-folders/jsoncpp_jsoncpp_fuzzer-aflfast/trial-12/corpus/corpus-archive-0006.tar.gz /work/experiment-folders/jsoncpp_jsoncpp_fuzzer-aflfast/trial-12/corpus/corpus-archive-0006.tar.gz" returned: 1. Extras: {'output': "cp: cannot stat '/usr/local/home/alice/fuzzbench/fuzzbench-data/multitest/experiment-folders/jsoncpp_jsoncpp_fuzzer-aflfast/trial-12/corpus/corpus-archive-0006.tar.gz': No such file or directory\n"}
WARNING:root:Corpus not found for cycle: 6. Extras: {'fuzzer': 'aflfast', 'benchmark': 'jsoncpp_jsoncpp_fuzzer', 'trial_id': '12', 'cycle': '6'}
```

Some of these messages are not actual errors and probably have no harm for experiment running and report generating.

## *Why* does this show up?
This is related to the logic of measuring. Related code or files are below:
First `measure_snapshot_coverage` will call `filestore_utils.cp`
https://github.com/google/fuzzbench/blob/552c297719fe8f475ac7291f3585a93dd645f55f/experiment/measurer.py#L542-L545

and, since we run it locally, that is actually running with `local_filestore.cp` and it will call `new_process`

https://github.com/google/fuzzbench/blob/552c297719fe8f475ac7291f3585a93dd645f55f/common/local_filestore.py#L31-L35

where it will log the `ERROR:root...` messages

https://github.com/google/fuzzbench/blob/552c297719fe8f475ac7291f3585a93dd645f55f/common/new_process.py#L122-L124

## *Where* on the platform does it happen?

Linux 5.2.17-1rodete3-amd64, CPU: 16 cores, RAM: 62.9 G
Docker version 19.03.5, build 633a0ea838

## *How* do we replicate the issue?

Refer to the local running documentation. Please stay in tune.
Or please refer to #399, but replace the code source as https://github.com/zchcai/fuzzbench/tree/b294ef59062a429b8b27f2fb933ac34f8d46e7b3

## Expected behavior (i.e. solution)

Though those reported errors are not bugs, we may need to prevent those reports during local running.

## Other
This is just a kind reminder here when you see those error messages.

**Comment by jonathanmetzman** [comment]
:-( unfortunately I think this started cropping up becuase I eliminated the expect_zero option from a lot of the filestore api functions. I see two ways of fixing this issue:
1. Add expect_zero back for any command that is expected to fail so that new_process.execute doesn't log the failures as errors.
2. Make new_process.execute always failures as something other than error.

2. might be viable but I don't know if it makes sense to do in every case. I think one is the easier option.

I don't think this issue only affects local by the way so I removed the label.

**Comment by zchcai** [comment]
That makes sense. That also explains why I didn't see those before in #399 experimental local running.
How about add them back?

**Comment by jonathanmetzman** [comment]
Look for uses of filestore module and see where we are doing try-except. If you see that, add the expect_zero param to those functions.

**Comment by zchcai** [comment]
> Look for uses of filestore module and see where we are doing try-except. If you see that, add the expect_zero param to those functions.

Yes. Also make it call with `expect_zero=False`, right?

**Comment by jonathanmetzman** [comment]
Yep!

**Comment by zchcai** [comment]
Use the old patterns back: #466
