### ISSUE TITLE
Improve Coverage Measurement in FuzzBench

### ISSUE THREAD

**Issue by jonathanmetzman** [google/fuzzbench#453]
We're planning on doing a lot of changes to improve coverage measurement in FuzzBench.
This will the tracking bug for those efforts.
@Shadoom7 can you mention this bugs in your pull requests so they can be tracked better.

**Comment by jonathanmetzman** [comment]
The first step in these efforts is integrating clang coverage with FuzzBench.
There are some questions about whether it is fast enough for this purpose.
@Shadoom7 will try replacing SanitizerCoverage with clang coverage on a branch, and then do experiments to compare the speed of measurement using clang coverage vs sanitizercoverage. Ideally we would not support both systems, but if clang coverage is too slow. We will only use it at the end of an experiment.

**Comment by jonathanmetzman** [comment]
Related to #77

**Comment by Shadoom7** [comment]
#564 
This PR replaces the sanitizer coverage with clang coverage

**Comment by Shadoom7** [comment]
#565 
This PR will collect and store the covered region data in cloud storage

**Comment by Shadoom7** [comment]
#595 
This is the rebased version of #565.

**Comment by Shadoom7** [comment]
#602 
Some fix to ensure the coverage info is always dumped.

**Comment by Shadoom7** [comment]
#618 
Generate the clang coverage reports.

**Comment by Shadoom7** [comment]
#622 
A fix to reduce the memory use during measuring.

**Comment by Shadoom7** [comment]
#657 
Implemented two matrix and plots to measure and display the unique coverage of each pair of fuzzer and benchmark.

**Comment by Shadoom7** [comment]
#662 
Add one column in the `Experiment` table in database to better support merging between experiments.

**Comment by Shadoom7** [comment]
#680 
Fix the broken coverage reports.

**Comment by Shadoom7** [comment]
#685 
Some fix and implemented one more summary ranking plot of unique coverage.
