### ISSUE TITLE
woff2 contains some invalid seeds

### ISSUE THREAD

**Issue by vanhauser-thc** [google/fuzzbench#463]
I noticed that the seeds for woff2 are actually no valid seeds but the source code for a font
e.g. in gcr.io/fuzzbench/runners/aflplusplus_shmem/woff2-2016-05-06 :
```
root@8a8b05a37956:/out# ls seeds/
README.md  index.html  package.json  roboto.css.map  sass
fonts      less        roboto.css    roboto.scss
```
I am not sure which input data the benchmark actually expects (maybe it converts from ttf to woff2?) but good seeds are here:
https://github.com/MozillaSecurity/fuzzdata/ and then e.g. in samples/woff2/

And I am hijacking the issue with a question :) how is it possible that coverage is *lost* during a run? as can be seen in this run on aflplusplus:
http://commondatastorage.googleapis.com/fuzzbench-reports/2020-06-14-test5/vorbis-2017-12-11_coverage_growth.svg

**Comment by jonathanmetzman** [comment]
Actually, I don't there was an issue of bias here. If you run AFL is on this benchmark you can see it has 61 seeds because we clean up the seeds directory to eliminate hierarchy and seeds of 1MB before fuzzing. Specifically for AFL https://github.com/google/fuzzbench/blob/master/experiment/runner.py#L67

**Comment by vanhauser-thc** [comment]
I dont care if there was bias, I was just pointing out that copying there just woff files would make a better fuzzing than lots of pointless files like README and css files :)
I dont expect that there is a a lot of bad files because they will not be used as they have little new coverage. but having more good woff2 files instead - that is the right move IMHO

**Comment by jaylinski** [comment]
I also noticed this in my personal setup. I changed this to use the "official" corpus from oss-fuzz:

```sh
# https://github.com/google/oss-fuzz/tree/master/projects/woff2/corpus
git clone https://github.com/google/oss-fuzz.git && cd ./oss-fuzz
git checkout 7643d953146b4d1840e4581b00041ecf432250d7
cp ./projects/woff2/corpus/* $OUT/seeds
```

**Comment by jonathanmetzman** [comment]
I made a fix based on @jaylinski 
I didn't really notice a huge difference though. make-test-run with the fix gets ~820 edges. Without the fix ~835.
