### ISSUE TITLE
remove google* related Python packages installation (for local)

### ISSUE THREAD

**Issue by zchcai** [google/fuzzbench#468]
Since local running has no dependency on Google Cloud services, shall we remove these packages requirement for local running? 
https://github.com/google/fuzzbench/blob/c40344d85cb128a639eeacfc5b6e884d1f3e4a3a/requirements.txt#L2-L5
For example, a separate requirement.txt for local execution.
https://github.com/google/fuzzbench/blob/c40344d85cb128a639eeacfc5b6e884d1f3e4a3a/experiment/run_experiment.py#L405
Currently, this above line is copied from the script used for cloud running (startup-dispatcher.sh):
https://github.com/google/fuzzbench/blob/c40344d85cb128a639eeacfc5b6e884d1f3e4a3a/docker/dispatcher-image/startup-dispatcher.sh#L29

**Comment by inferno-chromium** [comment]
Not a big deal for the additional branching / complexity it introduces.

**Comment by jonathanmetzman** [comment]
Agreed. Definitely not worth the complexity.
