### ISSUE TITLE
Some honggfuzz targets seem to be not instrumented

### ISSUE THREAD

**Issue by robertswiecki** [google/fuzzbench#47]
Hi, I was looking at some poorer honggfuzz results, e.g. for the systemd parser, and this log file

https://console.cloud.google.com/storage/browser/_details/fuzzbench-data/sample/experiment-folders/systemd_fuzz-link-parser-honggfuzz/trial-40413/results/fuzzer-log.txt

might suggest that the binary is not instrumented at all. I.e. it is slightly instrumented, probably for some str*cmp comparisons during final linking, but not really for trace-pc-guard,trace-cmp,trace-div,indirect-calls b/c logs like

```Size:8192 (i,b,hw,ed,ip,cmp): 0/0/0/0/0/24, Tot:0/0/0/0/0/4167```

mean, that there're no pc-guard, nor indirect-pc paths seen. Only few cmp hits.

Looking at https://github.com/google/fuzzbench/blob/master/benchmarks/systemd_fuzz-link-parser/oss-fuzz.yaml the target is somehow shared with oss-fuzz, so probably built in some special way, other than majority of targets.

Could it be some obvious problem, that you can spot here, or will it require some deeper debugging? Which I can do, just hoping you might spot the problem way faster :)

**Comment by robertswiecki** [comment]
FYI, found a way to repro it with build rules from oss-fuzz. Looking into it now.

**Comment by jonathanmetzman** [comment]
Thanks for spotting this Robert!

**Comment by robertswiecki** [comment]
Ok, I think I figured it out. It's a bit complex, but here's the gist of it for the posterity.

I think I have fixed it with https://github.com/google/honggfuzz/commit/77ea4dc4b499799e20ba33ef5df0152ecd113925 and I also updated the https://github.com/google/honggfuzz/releases/tag/oss-fuzz to include it.

So, ```fuzz-link-parser``` depeneds in ```libsystemd```

```shell
$ ldd ./systemd/out/fuzz-link-parser | grep systemd
	libsystemd-shared-245.so => /home/jagger/fuzz/systemd/./systemd/out/src/shared/libsystemd-shared-245.so (0x00007f5548d0d000)
```

And libsystemd contains honggfuzz's symbols already.

```
$ nm /home/jagger/fuzz/systemd/./systemd/out/src/shared/libsystemd-shared-245.so | grep cmp4
00000000002fd060 T hfuzz_trace_cmp4
00000000002fcd70 t hfuzz_trace_cmp4_internal
00000000002fcfe0 T __sanitizer_cov_trace_cmp4
00000000002fe040 T __sanitizer_cov_trace_const_cmp4
```

But, when compiling ```fuzz-link-parser``` two things happen.

1). The compiler sees that e.g. ```__sanitizer_cov_trace_cmp4``` is already defined in the dynamic lib ```libsystemd.so```, do it omits libhfuzz.a defintion.

Now, -fsanitize=address comes into place, which provides its own empty ```__sanitizer_cov_trace_cmp4```, which takes precendence over the dynamic symbol from ```libsystemd.so```, possiblt because ```libasan.a``` is compiled in with implicit ```-Wl,--whole-archive``` and ```libhfuzz.a``` doesn't use it.

I'm not 100% sure if I understand every interaction here correctly, but including ```libhfuzz.a``` twice, before and after all objects files (https://github.com/google/honggfuzz/commit/77ea4dc4b499799e20ba33ef5df0152ecd113925) solves the problem.

I'll run a few more tests, but this should help.

**Comment by jonathanmetzman** [comment]
>Looking at https://github.com/google/fuzzbench/blob/master/benchmarks/systemd_fuzz-link-parser/oss-fuzz.yaml the target is somehow shared with oss-fuzz, so probably built in some special way, other than majority of targets.

Does this also affect trace-pc-guard instrumentation? We use that in AFL fuzzers too.

>Would it be possible to update honggfuzz used in fuzzbench to the google/honggfuzz@77ea4dc ?

Certainly. I can do this myself tommorrowish (i'm kind of OOO today) or feel free to update [this](https://github.com/google/fuzzbench/blob/master/fuzzers/honggfuzz/builder.Dockerfile#L26) (I'll ping you if it breaks anything).

**Comment by inferno-chromium** [comment]
Can send a PR to update hash on https://github.com/google/fuzzbench/blob/master/fuzzers/honggfuzz/builder.Dockerfile#L26
Best to test with make run-honggfuzz-<two benchmarks, one oss-fuzz e.g. systemd, and one like freetype2 (regular).

**Comment by robertswiecki** [comment]
> Does this also affect trace-pc-guard instrumentation? We use that in AFL fuzzers too.

I don't know... but maybe not.

I think the AFL library driver comes in a form of *.o file, which is pretty much always included in final binaries (should take precendence over ASAN libs).

While honggfuzz provides an *.a file, which is treated by linker as ```if there are undefined symbols which can then become defined, use specific .o from this specific *.a, otherwise discard the whole *.a```

**Comment by robertswiecki** [comment]
> Can send a PR to update hash on
> https://github.com/google/fuzzbench/blob/master/fuzzers/honggfuzz/builder.Dockerfile#L26

Thanks, yeah, will do soon

**Comment by jonathanmetzman** [comment]
> > Can send a PR to update hash on
> > https://github.com/google/fuzzbench/blob/master/fuzzers/honggfuzz/builder.Dockerfile#L26
> 
> Thanks, yeah, will do soon

Sorry it's not ready yet, but later this week I will try to enable CI so that it rebuilds all benchmarks when a fuzzer is changed.

**Comment by robertswiecki** [comment]
Shall I drop the PR for now?

**Comment by inferno-chromium** [comment]
> Shall I drop the PR for now?

I think he means that right now we dont have CI up, but CL is fine (since you tested locally).
