### ISSUE TITLE
Should we exclude the results on libpcap (with no valid seed) from the summary?

### ISSUE THREAD

**Issue by thuanpv** [google/fuzzbench#472]
Hi,

As we know, libpcap benchmark doesn't come with valid seeds and several fuzzers (e.g., AFL, AFLFast, AFLSmart, FairFuzz), which don't have "laf-intel" mechanism enabled, achieve very poor results. I think it is okay to use this benchmark to show the effectiveness of laf-intel and other fuzzers that have implemented a similar feature (e.g., Honggfuzz, aflplusplus_optimal). However, if the results are used to produce the summary, the overall results, especially the average normalized score, of AFL, AFLFast, AFLSmart, FairFuzz ... could be negatively affected.

In fact, I think laf-intel is an orthogonal approach in the sense that AFL, AFLFast, AFLSmart results could be improved if the binary under test is instrumented with laf-intel passes enabled.

Regards,

Thuan

**Comment by vanhauser-thc** [comment]
I think it is good to have it. there is not only laf-intel but also input2state mechanisms (eg cmplog/redqeen and more coming the next months) and it is interesting to compare them against each other. it also shows that if you have a good corpus that these mechanisms help little.

**Comment by mboehme** [comment]
I agree with @vanhauser-thc. In addition, I think we shouldn't remove subjects only because some fuzzers don't perform well there.

See also https://github.com/google/fuzzbench/issues/327#issuecomment-627730677 and https://github.com/google/fuzzbench/issues/48#issuecomment-627754082

**Comment by thuanpv** [comment]
Thanks @vanhauser-thc and @mboehme for your comments. I would like to clarify my point; it seems that it was not very clear in my first post; I am sorry for that. As we know, in the current FuzzBench report, we see two parts. The first part is the **Experiment Summary** which includes average normalized scores, average ranks, critical difference diagram, and median coverages on each benchmark. The second part includes the detailed results for each benchmark (e.g., bloaty_fuzz_target summary, libpng-1.2.56 summary). In asked whether we should exclude libpcap (with no valid seeds) from the first part (**Experiment Summary**), not from the second part of the report which still have the results for libpcap. I hope my question makes some sense now.

**Comment by mboehme** [comment]
This depends on the objective of the evaluation. If you want to determine which fuzzer performs best on an arbitrary subject (I suppose, in general you could find other subjects just like libpcap), then the result summary should contain results over all subjects. If you want to evaluate how your fuzzer performs in different settings (e.g., only when valid seed is available), then maybe FuzzBench should allow to filter subjects according to such criteria during result reporting.

See also https://github.com/google/fuzzbench/issues/48#issuecomment-627881407.

**Comment by jonathanmetzman** [comment]
> This depends on the objective of the evaluation. If you want to determine which fuzzer performs best on an arbitrary subject (I suppose, in general you could find other subjects just like libpcap), then the result summary should contain results over all subjects. If you want to evaluate how your fuzzer performs in different settings (e.g., only when valid seed is available), then maybe FuzzBench should allow to filter subjects according to such criteria during result reporting.
> 
> See also [#48 (comment)](https://github.com/google/fuzzbench/issues/48#issuecomment-627881407).

I think if we are only going to provide one summary, the goal of the summary/aggregate results should be to show "which fuzzer performs best on an arbitrary subject". Therefore, to answer @thuanpv 's request, I don't think we should drop this benchmark from the aggregate results.
I wouldn't say this decision is final, but I think the right approach is for defaults to support the generic use-case while allowing other use-cases through some extra effort by those users. Do people think this is the right approach?

I think lowering the bar for customizing reports (as @mboehme suggested "filtering") would make the issues @thuanpv points out less of a problem. Do you agree?

I've filed https://github.com/google/fuzzbench/issues/481 to track this work (didn't want to hijack this thread)

**Comment by thuanpv** [comment]
Hi @jonathanmetzman. Following is my understanding of how the average normalized score is calculated. Could you please confirm whether it is correct?

As explained in the report, it is calculated based on the average of per-benchmarks scores, where the score represents the percentage of the highest reached median coverage on a given benchmark (higher value is better). Suppose that we have 2 fuzzers (F1, F2) and 5 benchmarks (B1, B2, B3, B4, and B5) and B5 is something like libpcap. If the scores for F1 on the 5 benchmarks are 100, 100, 100, 100, 10 and the scores for F2 are 90, 90, 90, 90, 100 then the final score for F1 is 82 while the F2's score is 92. So in this simple example, F1 is considered worse than F2 even though it produces better results on 4/5 subjects.
