### ISSUE TITLE
Cache_from in generated.mk broken

### ISSUE THREAD

**Issue by jonathanmetzman** [google/fuzzbench#476]
The cache_from line in generated.mk is broken.
[It currently is](https://github.com/google/fuzzbench/blob/master/docker/generate_makefile.py#L26):
```
BOILERPLATE = """
cache_from = $(if ${RUNNING_ON_CI},--cache-from {fuzzer},)
"""
```
This isn't templated and seems wrong to me. I'm not sure what the impact is yet.
CC @mbarbella-chromium who changed this line.

**Comment by jonathanmetzman** [comment]
Ping.
You can see how {fuzzer} is passed as a commandline argument here: https://github.com/google/fuzzbench/pull/521/checks?check_run_id=867116521

**Comment by inferno-chromium** [comment]
Not applicable now.
