### ISSUE TITLE
convert global config (like env var) to a non-global way

### ISSUE THREAD

**Issue by zchcai** [google/fuzzbench#484]
Currently, global config makes code hard to understand and write unit tests. Also it makes hard to debug code.

**Comment by inferno-chromium** [comment]
no one is working on this and unsure what is to be done here, so closing.

**Comment by zchcai** [comment]
> no one is working on this and unsure what is to be done here, so closing.

I guess this will be implemented along with the new queue-based arch platform in the future, as it will pass `config` as a function argument during job creation. Currently, under `fuzzbench/` folder, it uses one config file to store all configurations and that will be parsed as a dictionary object.
