### ISSUE TITLE
SSH time out

### ISSUE THREAD

**Issue by Shadoom7** [google/fuzzbench#486]
ssh time out when trying to run experiment on gcp.

**Comment by zchcai** [comment]
> ssh time out when trying to run experiment on gcp.

Could you provide more details? For [example](https://github.com/zchcai/github-issue-templates/blob/master/questions-answers/ISSUE_TEMPLATE.md).

**Comment by Shadoom7** [comment]
When trying to run experiment on gcp, the error occurs like this:

$ PYTHONPATH=../fuzzbench python3 ../fuzzbench/experiment/run_experiment.py -e ruikang2 -c ./fuzzbench-test.yaml --fuzzers afl libfuzzer --benchmarks libpng-1.2.56 mbedtls_fuzz_dtlsclient
INFO:root:GCP instance isn't ready yet. Rerunning SSH momentarily.
INFO:root:GCP instance isn't ready yet. Rerunning SSH momentarily.
INFO:root:GCP instance isn't ready yet. Rerunning SSH momentarily.
INFO:root:GCP instance isn't ready yet. Rerunning SSH momentarily.
INFO:root:GCP instance isn't ready yet. Rerunning SSH momentarily.
INFO:root:GCP instance isn't ready yet. Rerunning SSH momentarily.
INFO:root:GCP instance isn't ready yet. Rerunning SSH momentarily.
INFO:root:GCP instance isn't ready yet. Rerunning SSH momentarily.
INFO:root:GCP instance isn't ready yet. Rerunning SSH momentarily.
INFO:root:GCP instance isn't ready yet. Rerunning SSH momentarily.
Traceback (most recent call last):
  File "../fuzzbench/experiment/run_experiment.py", line 549, in <module>
    sys.exit(main())
  File "../fuzzbench/experiment/run_experiment.py", line 541, in main
    args.benchmarks, fuzzer_configs)
  File "../fuzzbench/experiment/run_experiment.py", line 260, in start_experiment
    start_dispatcher(config, CONFIG_DIR)
  File "../fuzzbench/experiment/run_experiment.py", line 272, in start_dispatcher
    dispatcher.start()
  File "../fuzzbench/experiment/run_experiment.py", line 425, in start
    self.config['cloud_compute_zone'])
  File "/home/ruikangshi/work/fuzzbench/common/gcloud.py", line 62, in robust_begin_gcloud_ssh
    raise Exception('Couldn\'t SSH to instance.')
Exception: Couldn't SSH to instance.

I was doing it locally instead of on CRD.

**Comment by zchcai** [comment]
Could you provide your `fuzzbench-test.yaml`? Is this a pure local run or running dependent on Google Cloud services?

**Comment by Shadoom7** [comment]
> Could you provide your `fuzzbench-test.yaml`? Is this a pure local run or running dependent on Google Cloud services?

The latter one I think. The file looks like this:

`experiment_filestore: gs://my-fuzzbench-data
report_filestore: gs://my-fuzzbench-reports
cloud_project: fuzzbench-test
cloud_sql_instance_connection_name: "fuzzbench-test:us-central1:postgres=tcp:5432"

# These fields are explained more in the guide to running an experiment.
cloud_compute_zone: us-central1-a
max_total_time: 82800  # 23 hours, the default for a preemptible experiment.
trials: 2
preemptible_runners: true`

**Comment by jonathanmetzman** [comment]
@zchcai keep in mind this isn't local experiment, but cloud experiment.

**Comment by jonathanmetzman** [comment]
Fixed by #489.
