### ISSUE TITLE
Makefile uses Python3 even though project doesn't support Python3.8

### ISSUE THREAD

**Issue by jonathanmetzman** [google/fuzzbench#515]
This has become a problem for me personally because python3.8 is now the default python3 on my machine (don't know why this is or if this happened recently).
The result of this is that pytype fails to install or work when make presubmit is run and the test `test_build_all_measurers` in `test_builder.py` hangs forever.

I guess the fix for this could be to specify Python3.7, but we might want to consider making the project work with other versions of Python.

**Comment by inferno-chromium** [comment]
i ran into that hang as well, had to create a python3.7 virtualenv. but yeah 3.8 should be made to work.

**Comment by jonathanmetzman** [comment]
I think we fixed this.
