### ISSUE TITLE
llvm-cov show error message on bloaty_fuzz_target

### ISSUE THREAD

**Issue by Shadoom7** [google/fuzzbench#518]
After running the experiment using clang-based coverage. The file generated by 
'llvm-cov export -format=text --summary-only [binary file for bloaty-fuzz-target] -instr-profile=[.profdata file generated by clang-based coverage]'
will have an error message preceding the normal output.
The error looks like this:
'warning: 7 functions have mismatched data'

The same error occurs when trying to use 'llvm-cov show' on bloaty_fuzz_target using clang-based coverage instrumentation.

**Comment by jonathanmetzman** [comment]
I don't have the cycles to debug this right now. But I think it's OK to merge in spite of this problem, and we can disable the bloaty benchmark until I fix it or decide it can't be fixed.

**Comment by jonathanmetzman** [comment]
@inferno-chromium WDYT of this plan?

**Comment by inferno-chromium** [comment]
That warning is not a blocking error, i remember this from the old days in chromium. right @Dor1s ?

**Comment by jonathanmetzman** [comment]
I think it was preventing coverage from being obtained. @Shadoom7 can you confirm?

**Comment by inferno-chromium** [comment]
And yes, i am fine with disabling bloaty to unblock this.

**Comment by Shadoom7** [comment]
> I think it was preventing coverage from being obtained. @Shadoom7 can you confirm?

It's not. I can still get the coverage information if I choose to ignore this warning, though the coverage data may not be complete.

**Comment by Shadoom7** [comment]
The llvm-cov will still generate the information for coverage despite this warning. I just don't know should we use that since I'm not sure how llvm-cov deals with those 7 mismatched functions (generate the coverage information as those functions don't exist OR have some deeper impacts on the coverage information)

I've ran a small experiment (2 fuzzers and 2 benchmarks) to skip this warning and generate the [report](https://storage.googleapis.com/my-fuzzbench-reports/ruikang6/index.html) with bloaty in it. The result looks good to me.

**Comment by Dor1s** [comment]
Those warnings might be different. IIRC there was a warning from `llvm-profdata` that would actually result in an error and empty or nearly empty coverage reports. Warnings from `llvm-cov` are less dangerous, especially if you end up with a report that look reasonably correct.

Conclusion: should be fine to leave as is. If you ever notice any instability in this report, then you have to either ignore this benchmark or find out those conflicting functions and try to fix.
