### ISSUE TITLE
Use BuildKit for better docker build caching

### ISSUE THREAD

**Issue by lszekeres** [google/fuzzbench#536]
By default `docker build` can only use the local cache. Currently, when we build images, in order to take advantage of the local cache, we pull images from the registry first. These steps can be eliminated and our build process can be simplified by using BuildKit. (This includes the local `make` based building, the GCB based building, and it will make the new distributed queue-based build process much simpler too.)

BuildKit is an advanced docker image building backend, which (among other things) can use the (remote) registry as a cache. I.e., with BuilKit enabled, when we build images like this: 
```shell
docker build -t fuzzbench/base-runner --build-arg BUILDKIT_INLINE_CACHE=1 ...
docker push fuzzbench/base-runner
```
Then the caching information is inlined and uploaded to the registry, so when we build an image on another machine, and use the --cache-from flag:
```shell
docker build --cache-from fuzzbench/base-runner ...
```
BuildKit will check if the there's a cache hit and automatically pulls data from the registry, if there is. Also, it downloads only the parts of the image that are actually useful.

BuildKit can be enabled by setting the `DOCKER_BUILDKIT=1` env var (before running `docker build`). See:
https://docs.docker.com/engine/reference/commandline/build/#specifying-external-cache-sources

While BuildKit is part of Docker now, it can also be used as a standalone tool:
https://github.com/moby/buildkit
https://github.com/genuinetools/img

Alternative tools we could use that support using the registry as a remote cache:
https://github.com/GoogleContainerTools/kaniko
https://github.com/uber/makisu

**Comment by zchcai** [comment]
If I understand correctly, these two will only be used once at the beginning, for initializing the registry.
> docker build -t gcr.io/fuzzbench/base-runner --build-arg BUILDKIT_INLINE_CACHE=1
docker push gcr.io/fuzzbench/base-runner

And the following is our logic in new arch:
> DOCKER_BUILDKIT=1 docker build --cache-from gcr.io/fuzzbench/base-runner

**Comment by lszekeres** [comment]
There'd be just one build step for each image, that uses the registry as cache and inlines the cache info in newly built images, ie:
```
export DOCKER_BUILDKIT=1
docker build --cache-from $REGISTRY/base-runner --build-arg BUILDKIT_INLINE_CACHE=1 ...
docker push ...
```
(Note that in the single machine scenario we don't need to push and we don't need a registry, we need this central cache when we're doing a distributed build with multiple machines.)

**Comment by inferno-chromium** [comment]
I think this is done, please reopen if not, we have to bring back #615, but that is tracked in another bug.
