### ISSUE TITLE
Issues in installation

### ISSUE THREAD

**Issue by tthtlc** [google/fuzzbench#54]
After I initiated the installation, I got this error:

+ make -j 8 -C src fuzzing
make: Entering directory '/src/BUILD/src'
  GEN      hb-buffer-deserialize-json.hh
  GEN      hb-buffer-deserialize-text.hh
  GEN      hb-ot-shape-complex-indic-machine.hh
  GEN      hb-ot-shape-complex-myanmar-machine.hh
  GEN      hb-ot-shape-complex-use-machine.hh
  CXX      libharfbuzz_fuzzing_la-hb-buffer.lo
  CXX      libharfbuzz_fuzzing_la-hb-blob.lo
  CXX      libharfbuzz_fuzzing_la-hb-buffer-serialize.lo
hb-buffer-serialize.cc:389:10: fatal error: 'hb-buffer-deserialize-json.hh' file not found
#include "hb-buffer-deserialize-json.hh"
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
Makefile:1606: recipe for target 'libharfbuzz_fuzzing_la-hb-buffer-serialize.lo' failed
make: *** [libharfbuzz_fuzzing_la-hb-buffer-serialize.lo] Error 1
make: *** Waiting for unfinished jobs....
make: Leaving directory '/src/BUILD/src'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/src/fuzzer.py", line 41, in build
    utils.build_benchmark()
  File "/src/fuzzers/utils.py", line 42, in build_benchmark
    subprocess.check_call(['/bin/bash', '-ex', build_script], env=env)
  File "/usr/local/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/bin/bash', '-ex', 'benchmark/build.sh']' returned non-zero exit status 1.
The command '/bin/sh -c python3 -u -c "import fuzzer; fuzzer.build()"' returned a non-zero code: 1
docker/build.mk:114: recipe for target '.libfuzzer-harfbuzz-1.3.2-builder' failed
make: *** [.libfuzzer-harfbuzz-1.3.2-builder] Error 1

help?

**Comment by inferno-chromium** [comment]
Are you running `make run-libfuzzer-harfbuzz-1.3.2`
i cannot reproduce it, we have been running this for a while, could be transient error, can you retry.

**Comment by tthtlc** [comment]
Appreciate your reply.
I did not directly run "make run-libfuzzer-harfbuzz-1.3.2".   But I run "make" after "pip install -r requirement.txt" instead.   Correct?
The execution log is listed here:
https://drive.google.com/file/d/15YQhmiOPpb4xGT05dgSejTvrQCN9gogC/view?usp=sharing
and at the end is the error I encounterd.
Perhaps it is transient, so I will retry again.   Thanks.

**Comment by inferno-chromium** [comment]
Sorry that is not the documented workflow, please follow our documentation - https://google.github.io/fuzzbench/getting-started/prerequisites/
