### ISSUE TITLE
Measure time difference between clang cov and sancov

### ISSUE THREAD

**Issue by jonathanmetzman** [google/fuzzbench#546]
After doing #545 you can use the stackdriver API to query logs and get the time it takes to measure each cycle, then you can compare the overall times it takes for sancov vs clang cov.

**Comment by jonathanmetzman** [comment]
Any updates?

**Comment by Shadoom7** [comment]
Sorry, I haven't got the time to figure out how to do it locally. I only have a version that could do it on fuzzbench but it is always occupied. I'll try to do it locally by this week.

**Comment by jonathanmetzman** [comment]
Couldn't you use fuzzbench-test for this purpose? It's fine if you need to copy some builds or database entities (you can export to csv and import from csv)

**Comment by Shadoom7** [comment]
Got you. I'll try it!

**Comment by Shadoom7** [comment]
Looks like the time to measure a cycle is less than 2 times longer using clang-cov compared to sancov.
Here are some logs for the time to measure the same pair of fuzzer and benchmark using both tools:
[sancov](https://pantheon.corp.google.com/logs/viewer?organizationId=433637338589&project=fuzzbench-test&minLogLevel=0&expandAll=false&timestamp=2020-08-06T21:55:31.255597154Z&customFacets=&limitCustomFacetWidth=true&interval=PT1H&resource=global&scrollTimestamp=2020-08-06T22:25:34.892116597Z&dateRangeStart=2020-08-06T21:29:53.889Z&dateRangeEnd=2020-08-06T22:29:53.889Z&advancedFilter=resource.type%3D%22global%22%0AjsonPayload.experiment%3D%22compare-sancov-3%22%0AjsonPayload.benchmark%3D%22libpcap_fuzz_both%22%0AjsonPayload.fuzzer%3D%22honggfuzz%22%0AjsonPayload.cycle%3D%2249%22%0Aseconds), [clang-cov](https://pantheon.corp.google.com/logs/viewer?project=fuzzbench&organizationId=433637338589&minLogLevel=0&expandAll=false&timestamp=2020-08-06T22:26:11.624000000Z&customFacets=&limitCustomFacetWidth=true&dateRangeStart=2020-07-05T21:26:23.000Z&dateRangeEnd=2020-07-09T22:26:23.000Z&interval=CUSTOM&resource=global&scrollTimestamp=2020-07-09T12:15:07.044199190Z&advancedFilter=resource.type%3D%22global%22%0AjsonPayload.experiment%3D%22clang-cov-test%22%0AjsonPayload.benchmark%3D%22libpcap_fuzz_both%22%0AjsonPayload.fuzzer%3D%22honggfuzz%22%0AjsonPayload.cycle%3D%2249%22%0Aseconds)

**Comment by lszekeres** [comment]
Thanks @Shadoom7! <2x is pretty good, i'd say!

**Comment by Shadoom7** [comment]
> Thanks @Shadoom7! <2x is pretty good, i'd say!

No problem! Yeah I think so too.
