### ISSUE TITLE
Make sure clang cov data is always dumped by libfuzzer

### ISSUE THREAD

**Issue by jonathanmetzman** [google/fuzzbench#547]
In https://github.com/google/fuzzbench/blob/master/fuzzers/coverage/patch.diff you can see that I added some code to make sure the coverage is always dumped by libFuzzer (I think the patch is to handle ooms and timeouts). I believe libFuzzer already did this for crashes.
DumpCoverage calls a sancov specific function, you'll probably need to add the clang-cov specific one. @Dor1s might know the name of this.

**Comment by Dor1s** [comment]
I think you're looking for https://source.chromium.org/chromium/chromium/src/+/master:base/test/clang_profiling.cc

**Comment by inferno-chromium** [comment]
Clang code coverage profraw is not generated when run_coverage fails on timeout.

**Comment by inferno-chromium** [comment]
https://pantheon.corp.google.com/logs/viewer?resource=global&logName=projects%2Ffuzzbench%2Flogs%2Ferrors&expandAll=false&timestamp=2020-07-28T14:35:16.000000000Z&project=fuzzbench&src=ac&minLogLevel=0&customFacets=&limitCustomFacetWidth=true&advancedFilter=severity%3E%3DERROR&interval=JUMP_TO_TIME&scrollTimestamp=2020-07-28T10:22:10.004998190Z

**Comment by inferno-chromium** [comment]
```
 jsonPayload: {
  component: "dispatcher"   
  coverage_binary: "/work/coverage-binaries/sqlite3_ossfuzz/ossfuzz"   
  experiment: "2020-07-27"   
  instance_name: "d-2020-07-27"   
  message: "Coverage run failed."   
  output: "WARNING: Failed to find function "__sanitizer_acquire_crash_state".
WARNING: Failed to find function "__sanitizer_print_stack_trace".
WARNING: Failed to find function "__sanitizer_set_death_callback".
INFO: Seed: 892174498
MERGE-OUTER: 296 files, 0 in the initial corpus, 0 processed earlier
MERGE-OUTER: attempt 1
WARNING: Failed to find function "__sanitizer_acquire_crash_state".
WARNING: Failed to find function "__sanitizer_print_stack_trace".
WARNING: Failed to find function "__sanitizer_set_death_callback".
INFO: Seed: 892267735
INFO: -max_len is not provided; libFuzzer will not generate inputs larger than 1048576 bytes
MERGE-INNER: using the control file '/tmp/libFuzzerTemp.Merge3332240.txt'
MERGE-INNER: 296 total files; 0 processed earlier; will process 296 files now
#1	pulse  exec/s: 0 rss: 23Mb
#2	pulse  exec/s: 0 rss: 24Mb
#4	pulse  exec/s: 0 rss: 24Mb
#8	pulse  exec/s: 0 rss: 25Mb
#16	pulse  exec/s: 3 rss: 43Mb
#32	pulse  exec/s: 6 rss: 43Mb
#64	pulse  exec/s: 12 rss: 43Mb
ALARM: working on the last Unit for 6 seconds
       and the timeout value is 5 (use -timeout=N to change)
MS: 0 "   
  subcomponent: "measurer"   
 }
 logName: "projects/fuzzbench/logs/run_coverage"  
 receiveTimestamp: "2020-07-28T09:53:51.872417655Z"  
 resource: {…}  
 severity: "ERROR"  
 timestamp: "2020-07-28T09:53:51.872417655Z" 
```

**Comment by Dor1s** [comment]
I'd suggest passing a greater timeout value to avoid timeouts (same for OOMs) during coverage generation, e.g. see https://github.com/google/oss-fuzz/blob/c22ec3a33da652ad58f7975ae90a6122d0202a35/infra/base-images/base-runner/coverage#L77

**Comment by inferno-chromium** [comment]
> I'd suggest passing a greater timeout value to avoid timeouts (same for OOMs) during coverage generation, e.g. see https://github.com/google/oss-fuzz/blob/c22ec3a33da652ad58f7975ae90a6122d0202a35/infra/base-images/base-runner/coverage#L77

We need to finish measuring a snapshot in like max 15 minutes. So, we kept a unit timeout as 5 sec, maybe this is too low after clang code coverage switch. What value do you suggest 10 sec or higher (given we can have 100-200 avg items in corpus or even higher).

**Comment by Dor1s** [comment]
Depends on the value you use during fuzzing. For coverage I'd use 4x that.

**Comment by inferno-chromium** [comment]
> Depends on the value you use during fuzzing. For coverage I'd use 4x that.

in fuzzing, we let fuzzer use its default. for libfuzzer, it is 1200 sec, for afl, i think was like <1sec.

**Comment by jonathanmetzman** [comment]
> > Depends on the value you use during fuzzing. For coverage I'd use 4x that.
> 
> in fuzzing, we let fuzzer use its default. for libfuzzer, it is 1200 sec, for afl, i think was like <1sec.

I think this default is a bit crazy. I'd be fine with picking something sane like 15 seconds in coverage.

**Comment by inferno-chromium** [comment]
This is done in https://github.com/google/fuzzbench/pull/602
