### ISSUE TITLE
Use deadsnakes ppa instead of compiling Python from scratch in base image

### ISSUE THREAD

**Issue by ammaraskar** [google/fuzzbench#56]
https://github.com/google/fuzzbench/blob/b59cd48ccc9bee5581f40e9215c0abedce4dbbe1/docker/base-image/Dockerfile#L33-L39

Python is compiled from scratch in the base-image, I noticed during the CI patch, this takes up a decent chunk of time in the start. Instead it's possible to just pull it in from the deadsnakes repo https://launchpad.net/~deadsnakes/+archive/ubuntu/ppa

It'll also probably be a bit of a faster interpreter because they build with profile guided + link time optimizations.

**Comment by jonathanmetzman** [comment]
We also build with PGO. We don't like getting packages from unofficial sources so I think we're stuck building.

Pulling the base-images would probably be a better way to speed things up.
But if/when we switch to using GCB, this will be handled for us.
