### ISSUE TITLE
Reports should support single fuzzer experiments

### ISSUE THREAD

**Issue by jonathanmetzman** [google/fuzzbench#562]
It might add a bit of complexity, but I think supporting single fuzzer experiments is a good idea since it provides some real time feedback and confirmation that an experiment is working. I imagine for many users these experiments will be common (example: https://github.com/google/fuzzbench/blob/master/service/experiment-requests.yaml#L24).
To do this I'm guessing the aggregate rankings need to be skipped.

**Comment by lszekeres** [comment]
It doesn't work currently?

> To do this I'm guessing the aggregate rankings need to be skipped.

It should already be skipped in case of a single fuzzer: https://github.com/google/fuzzbench/blob/master/analysis/report_templates/default.html#L70

**Comment by jonathanmetzman** [comment]
Ah OK, I assumed it didn't (I think not having reports for 2020-07-20 made me think this but there were no reports because of a different bug). I'll reopen if it isn't the case.
