### ISSUE TITLE
[service] Merge with clobber isn't working properly

### ISSUE THREAD

**Issue by jonathanmetzman** [google/fuzzbench#563]
In https://www.fuzzbench.com/reports/2020-07-13/index.html#bloaty_fuzz_target-summary we don't appear to be merging with clobber properly.
If you look at that benchmark aflplusplus and aflplusplus_optimal_shmem have 40 and 35 trials respectively.
This means that they are including data from multiple experiments. They should have 20 trials.

**Comment by jonathanmetzman** [comment]
Another bug.
This command:
```
PYTHONPATH=. python3 analysis/generate_report.py -q -m -d /tmp/nontransparent-benchmarks-report 2020-05-24 2020-06-26 2020-06-30 2020-07-20
```
Produces a report without libFuzzer. Dropping `-m` produces a report with libfuzzer. The point of merge with clobber is to use the data from the most recent experiment for each fuzzer.

**Comment by jonathanmetzman** [comment]
The second bug actually WAI. It happens because `2020-07-20` has libFuzzer so data from previous experiments with libFuzzer gets clobbered. But in 2020-07-20 all trials end at 78300 seconds (ie 87 cycles or 21.75 hours) instead of 23 hours.

**Comment by inferno-chromium** [comment]
Should be fixed with https://github.com/google/fuzzbench/pull/658, can file a new bug if see something new.
