### ISSUE TITLE
Name conflict for building tasks `fuzzers/coverage`

### ISSUE THREAD

**Issue by zchcai** [google/fuzzbench#575]
We already have a `coverage-builder` image to build:
https://github.com/google/fuzzbench/blob/17959e39a2b00b239e8c4e0edbeced31536e50cc/docker/image_types.yaml#L20-L25
and `{fuzzer}-builder` image to build:
https://github.com/google/fuzzbench/blob/17959e39a2b00b239e8c4e0edbeced31536e50cc/docker/image_types.yaml#L34-L39
Since we assume every folder under `fuzzers` are fuzzers' name, we'd better rename it.
Otherwise, when we want to parse the fuzzer name from an image name, it will have conflict.
 
Similarly, 'coverage-{benchmark}-builder' and '{fuzzer}-{benchmark}-builder'.

**Comment by lszekeres** [comment]
> Since we assume every folder under fuzzers are fuzzers' name, we'd better rename it.

I'd recommend leaving out "coverage" from the fuzzer list, pls see discussion here: https://github.com/google/fuzzbench/pull/543#discussion_r458354778

**Comment by zchcai** [comment]
> > Since we assume every folder under fuzzers are fuzzers' name, we'd better rename it.
> 
> I'd recommend leaving out "coverage" from the fuzzer list, pls see discussion here: [#543 (comment)](https://github.com/google/fuzzbench/pull/543#discussion_r458354778)

That also make senses since `coverage` is not a fuzzer.

**Comment by jonathanmetzman** [comment]
I think this was resolved.
