### ISSUE TITLE
worker mode change

### ISSUE THREAD

**Issue by zchcai** [google/fuzzbench#579]
Currently, we use brust mode for all workers.
However, this may let some workers quickly down when there is nothing to do temporarily.
For example, when one job is worked by worker A, and all other jobs are deferred or finished, then all other workers will exit.

I guess, we still need these workers on until all jobs finish.

**Comment by zchcai** [comment]
This will also introduce uncertain behavior for end-to-end testing in Github CI test.

**Comment by zchcai** [comment]
One solution is to remove the brust mode setting, and shutdown workers from the `fuzzbench/run_experiment.py` when all jobs are finished or one job is failed.

**Comment by lszekeres** [comment]
> One solution is to remove the brust mode setting, and shutdown workers from the `fuzzbench/run_experiment.py` when all jobs are finished or one job is failed.

Sounds good to me.
