### ISSUE TITLE
Build simplification

### ISSUE THREAD

**Issue by jonathanmetzman** [google/fuzzbench#580]
We need to simplify how things are built in FuzzBench. This is a tracking bug for that effort.

**Comment by jonathanmetzman** [comment]
PRs: #607 #567 #584

**Comment by inferno-chromium** [comment]
Need to bring back https://github.com/google/fuzzbench/pull/615

**Comment by inferno-chromium** [comment]
I have the fix to bring back #615

**Comment by inferno-chromium** [comment]
Rest should be done with https://github.com/google/fuzzbench/pull/729
