### ISSUE TITLE
aflplusplus variants can be removed, in favor of aflplusplus_optimal

### ISSUE THREAD

**Issue by inferno-chromium** [google/fuzzbench#587]
Since the variant tests are all done, can we remove various aflplusplus variants so that we can easily run full experiments with all fuzzers in fuzzers/

**Comment by vanhauser-thc** [comment]
I always send a remove pr once they are not needed anymore. Will do that Sunday

**Comment by inferno-chromium** [comment]
Sorry bad timing, feel free to do next week anytime, no need to wrry on sunday.

**Comment by vanhauser-thc** [comment]
no issue, I had planned to do that on sunday, not that you forced me to it ;)
