### ISSUE TITLE
bloaty and curl fail?

### ISSUE THREAD

**Issue by vanhauser-thc** [google/fuzzbench#598]
https://www.fuzzbench.com/reports/2020-07-28/index.html

take a look at the two benchmarks - empty results.
all others are ok.

**Comment by inferno-chromium** [comment]
Sorry about that, we are in process of transitioning to clang source code coverage.
It is fixed in https://github.com/google/fuzzbench/pull/594, i will stop the current one and start a new one.

**Comment by inferno-chromium** [comment]
Will let service re-run the experiment - https://github.com/google/fuzzbench/pull/599
