### ISSUE TITLE
Buildkit failing in CI

### ISSUE THREAD

**Issue by jonathanmetzman** [google/fuzzbench#629]
On [this CI run ](https://github.com/google/fuzzbench/pull/628/checks?check_run_id=947692658) AFL build fails with the message `failed to solve with frontend dockerfile.v0: failed to build LLB: mount already exists with name`.
I don't know what is causing this but I assume it's something to do with the buildkit changes.
I've never seen this happen before, I assume it was introduced by buildkit. Can you please look at other CI runs and see if it happens frequently?

**Comment by jonathanmetzman** [comment]
Looks like this caused 6/8 failures here: https://github.com/google/fuzzbench/pull/625

**Comment by jonathanmetzman** [comment]
From googling this, it seems like a buildkit error: https://github.com/moby/buildkit/issues/1460

**Comment by jonathanmetzman** [comment]
More errors: https://github.com/google/fuzzbench/pull/633/checks?check_run_id=951608193

@tanq16 did you try copying the fuzzer and fuzzers/ directory from host instead? Does that work.
You can force CI to build everything by modifying runner.py But please don't do this too much or else there will be a backlog for CI bots.

**Comment by Tanq16** [comment]
Fixed by #632
