### ISSUE TITLE
Have option in graphs to switch between normal and log-scale on x-axis

### ISSUE THREAD

**Issue by inferno-chromium** [google/fuzzbench#655]
We do have --log-scale flag in generate_report.py, but it is not available in an already generated report. Instead, we should just generate both graphs, and allow user to toggle. Maybe log-scale should be default, although sometimes it gets confusing, compare https://www.fuzzbench.com/reports/2020-08-03/index.html vs http://commondatastorage.googleapis.com/fuzzbench-reports/aarya-log-scale-test/index.html

**Comment by inferno-chromium** [comment]
See also @eqv comment [https://github.com/google/fuzzbench/issues/654#issuecomment-671542972]:
```
Lastly: Log plots. I don't like log plots. They blow all the noise completely out of proportion. A linear plot tells you very nicely where each fuzzer flatlines. We do want to see if the fuzzer was run long enough, and that we don't expect it to get better any time soon.
```

**Comment by mboehme** [comment]
@eqv
> A linear plot tells you very nicely where each fuzzer flatlines. We do want to see if the fuzzer was run long enough, and that we don't expect it to get better any time soon.
On a linear scale it is just really difficult to see whether a fuzzer is flatlining before another fuzzer, or whether it is just very slowly over-taking the other fuzzer. On a log-scale, you can more intuitively extrapolate.

Here two examples.
![](https://storage.googleapis.com/fuzzer-test-suite-public/exectime-report/freetype2-2017_coverage_growth.svg)
![](https://storage.googleapis.com/fuzzer-test-suite-public/exectime-report/lcms-2017-03-21_coverage_growth.svg)

> They blow all the noise completely out of proportion.
Not sure, I agree with this statement. Maybe you could quickly check whether variance is really higher at the beginning of the fuzzing campaign.

**Comment by eqv** [comment]
Just want to point out that I was not really talking about variance primarily here. I meant "tiny differences that won't really matter for a human that lives in linear time". I don't care if fuzzer 2 is only "looking like it's flat-lining" and in reality is going to overtake in some 2**10 days. Similarly, I don't care if fuzzer 2 is faster during the first 15 minutes. I care about getting good results in a reasonable amount of time (e.g. I believe overnight). 

Time to equal coverage is a questionable metric, as for experiments where fuzzer A gets more coverage than fuzzer B, we can almost always arbitrarily increase the number by making the experiment longer. "look it only took us 5 minutes to find the same coverage as fuzzer B found in a week, 1000000x speedup" IF fuzzer B even finds a single new edge/basic block at the end of the week.

**Comment by eqv** [comment]
I also just noticed that the variance is plotted in terms of standard deviations not percentiles. In my experience this drastically underestimates the real variance. Looking at theses plots might tell us VERY little about what is really going on. I just opened an issue to address this.

**Comment by mboehme** [comment]
> I care about getting good results in a reasonable amount of time (e.g. I believe overnight).

See, there is the challenge. For you one CPU *day* is a reasonable time budget, for ClusterFuzz one CPU *year* might be a reasonable time budget, and for Malory one CPU *century* is a reasonable time budget. I can see why you wouldn't care about coverage increase in the first few seconds; but - if you accept that coverage gets exponentially harder to achieve - you should at least consider looking at the log-scale, as well. No?

> Time to equal coverage is a questionable metric

I would argue the exact opposite. [Here](https://twitter.com/mboehme_/status/1302844857581355012) is why: 
> Technically, we are talking about the same quantity, coverage over time, only that we set a threshold value (arbitrarily) either at the y-axis or the x-axis. However, a fuzzer can be 4x faster than another over the entire campaign, but achieving 10% more coverage will get increasingly more difficult until it is impossible.

The discussion on time-to-same-coverage is tracked here: https://github.com/google/fuzzbench/issues/327

**Comment by inferno-chromium** [comment]
this is added by @wideglide in https://github.com/google/fuzzbench/pull/935
