### ISSUE TITLE
Linter complains about `No module named common/__init__.py (fatal)`

### ISSUE THREAD

**Issue by jonathanmetzman** [google/fuzzbench#670]
Then it will fail everywhere because that file isn't there.
I fixed it by creating that file. We should figure out why this happens and stop it.

**Comment by jonathanmetzman** [comment]
Another complaint I have about the new method we use for linting is it complains about uncommitted files, so if you like to keep a dirty tree with oneoff scripts like I do, you will get a lot of false positives.

**Comment by inferno-chromium** [comment]
Haven't seen this at all, but can prioritize if you feel we hit this often.

**Comment by jonathanmetzman** [comment]
Haven't seen this happen recently.
