### ISSUE TITLE
Eclipser maxfilelen value

### ISSUE THREAD

**Issue by andreafioraldi** [google/fuzzbench#70]
I experienced the same problem that you had in choosing maxfilelen to evaluate Eclipser some time ago.
I found that they used 1048576 in their experiments (https://github.com/SoftSec-KAIST/Eclipser-Artifact/blob/master/docker-scripts/experiment-scripts/package-exp/run_eclipser.sh#L25), so maybe you want to use this value to produce consistent results with the paper.

**Comment by jchoi2022** [comment]
Hi, sorry for the late confirm. 

Yes, you should provide `--maxfilelen 1048576` to align the configuration with AFL. When the option is not provided, an extremely small value is used as default value (to align with KLEE configuration).

Next, `-t` option specifies the timeout of the whole fuzzing campaign, in second. If you want to run each fuzzer for 24 hours, you can provide `-t 86400`.

Lastly, if the target benchmark is large and long-running, then you may provide `--exectimeout <millisecond>` option to adjust the timeout for each execution of program under test. The default value is 500, meaning that Eclipser expects the program to terminate within 0.5 second. While AFL automatically adjust this timeout threshold in its 'calibration' phase, we didn't have time to implement it in Eclipser. We recommend to use `--exectimeout 2000`, as the benchmark programs  look substantial in size.

**Comment by inferno-chromium** [comment]
Thank you very much @jchoi2022 !

**Comment by jonathanmetzman** [comment]
Thanks for the feedback! 

> Next, `-t` option specifies the timeout of the whole fuzzing campaign, in second. If you want to run each fuzzer for 24 hours, you can provide `-t 86400`.

I don't think this one is necessary since the fuzzer.py process and descendants will be terminated at 24 hours anyway. It seems cleaner this way rather than exposing to fuzzers how long they will run for.
