### ISSUE TITLE
Colors in the report

### ISSUE THREAD

**Issue by vanhauser-thc** [google/fuzzbench#707]
A run was just started with 5 fuzzer variants: https://www.fuzzbench.com/reports/2020-09-02/index.html

of those 5, 4 have similar colors (light blue, dark blue and light orange, dark orange).
especially the light blue is hard to see vs. the dark blue, especially as these are very close variants.

I would propose rearranging the color ordering so that lighter colors are only used after the darker ones have been selected already.

**Comment by inferno-chromium** [comment]
@vanhauser-thc - you want to help us fix it :) - https://github.com/google/fuzzbench/blob/d27bae7382e3863d9798b8342ad87bcfd4a119d7/analysis/plotting.py#L65

Otherwise, we can get to it in the next week or two.

**Comment by vanhauser-thc** [comment]
beat me to it :)
busy getting the GSoC libafl project ready for fuzzbench ...
