### ISSUE TITLE
easy fine-grained graphs

### ISSUE THREAD

**Issue by vanhauser-thc** [google/fuzzbench#715]
The last weeks I scripted around my own analysis scripts for afl++ runs.
out/plot_data has limited information and they are not per-second although it is much more often than fuzzbench snapshots.

So instead I took the file name information. They state when they were created and other useful information.
This works great for me, however for e.g. honggfuzz and libfuzzer this does not work as the name is just a hash.

Yesterday I then had such a simple idea that would also work for fuzzbench - for the time information in the graph do not rely on the snapshot time, just sort by file creation time and work from there. the first file is always a seed so it is at time offset 0, and from there you know exactly at what exact second a queue entry was generated in the run and what the coverage increase is - and build graphs that are correct on the specific second.

this way you have second correct coverage information.
this would not work for exec counts obviously, but that is not measures by fuzzbench anyway.

**Comment by lszekeres** [comment]
thanks! yes, that's a good idea!

we can also touch a `fuzzer-start` file when we start running a fuzzer to use as a reference point

**Comment by jonathanmetzman** [comment]
I think there is a problem with using timestamps to determine when a fuzzer found coverage. At least in libFuzzer if edge X is the only edge that testcase A in the corpus/queue covers uniquely (i.e. no other testcase covers it) A will get deleted if we find a testcase B that is smaller than A that also covers X.

**Comment by vanhauser-thc** [comment]
a fuzzer that deletes queue data? that is a first :)
It makes sense to forget/ignore an entry if there is a better entry, but deleting it ....
I would vote for that this is changed in libfuzzer.

but: this would still work - just not for libfuzzer if this is not changed. just do it for all the other fuzzers. it is an improvement and a fuzzer that doesnt support it should not hold the analysis of the other back.

**Comment by lszekeres** [comment]
> I think there is a problem with using timestamps to determine when a fuzzer found coverage. At least in libFuzzer if edge X is the only edge that testcase A in the corpus/queue covers uniquely (i.e. no other testcase covers it) A will get deleted if we find a testcase B that is smaller than A that also covers X.

Using timestamps would still give is more precise data then our current approach. Say libfuzzer finds the following inputs:

```
Minute 1: Input A
Minute 3: Input B
Minute 6: Input C subsuming Input A
```

Currently, by snapshotting every 15 minutes, we get:

```
Minute 15: B
Minute 15: C
```

But by snapshotting every 15 minute and looking at timestamps, we'd get *more* information:

```
Minute 3: B
Minute 6: C

```

**Comment by lszekeres** [comment]
We can also easily add a flag to libfuzzer that disables [deleting inputs](https://github.com/llvm-mirror/compiler-rt/blob/c438ef37dfc4b954ead9df6222fe0bb36987268e/lib/fuzzer/FuzzerCorpus.h#L228).

**Comment by vanhauser-thc** [comment]
@lszekeres 
if you do the analysis for per 15 minutes snapshot then yes this is even for libfuzzer an improvement.
It would just not work if done at the end.

I would recommend such a flag for libfuzzer alone for the purpose to be able to perform better performance analysis in libfuzzer, not only for fuzzbench.

**Comment by lszekeres** [comment]
> It would just not work if done at the end.

I'd definitely not do it only at the end, because i'd like to keep seeing results while the experiment is running.

**Comment by vanhauser-thc** [comment]
yes you would not, it is just how I use my script that uses that ;)

**Comment by mboehme** [comment]
LibFuzzer in fork mode [copies](https://github.com/llvm/llvm-project/blob/master/compiler-rt/lib/fuzzer/FuzzerFork.cpp#L218) the "fork-local" corpus to a "main corpus". It looks like an entirely new file is created (i.e., file attributes such as modification time are not preserved.

**Comment by mboehme** [comment]
@vanhauser-thc 
> a fuzzer that deletes queue data? that is a first :)
> It makes sense to forget/ignore an entry if there is a better entry, but deleting it ....
> I would vote for that this is changed in libfuzzer.

From KCC's FuzzCon slides, it seems you can discuss this here: 
* https://github.com/google/fuzzing/issues
* {fuzzing-discuss,libfuzzer}@googlegroups.com

**Comment by vanhauser-thc** [comment]
if the libfuzzer fork mode a version that is competitive - so that it makes sense that it becomes the core fuzzer setting of libfuzzer?
If not and it is rather a variant then I dont think this would need to be taken care of.

I agree with @lszekeres that the 15 min snapshots + timestamp base analysis together will improve the analysis for all fuzzers, even for libfuzzer "I like to fork and copy it" and libfuzzer "I like to delete my queue" :)

@mbiehme I am not a libfuzzer user nor developer, and I am not sure I would be happy to go through the whole llvm commit dance until such a patch would be accepted. So I rather leave that people who's goal it is to make libfuzzer better :) if they even want and like that change

**Comment by jonathanmetzman** [comment]
"if the libfuzzer fork mode a version that is competitive - so that it makes sense that it becomes the core fuzzer setting of libfuzzer?"

We use fork mode because libfuzzer's original behavior of crashing on first timeout/oom/crash doesn't make sense for fuzzbench (even though it does for ClusterFuzz).
I see the point about how this improves things for all fuzzers but on the other hand I would be happier with a solution that didn't expect this behavior of fuzzers. It doesn't seem like this is an intuitive constraint and I imagine many fuzzers written from scratch won't obey it.

**Comment by vanhauser-thc** [comment]
an alternative would be a daemon that uses inotify on the corpus directory to learn about new files being created and set hard links to them into a different directory. then the file times would be preserved and the file data themself as well

**Comment by wideglide** [comment]
Please correct me if I'm wrong, but neither file time stamps nor hard links will provide accurate queue history.  With the snapshot mechanism they might provide more accurate information like @lszekeres mentions?

- hard links will preserve deleted files, but will not prevent the metadata from being modified (timestamps).
- AFL (and most variants) often trims an input when it starts fuzzing a new entry from the queue which modifies the timestamps.  Unfortunately there's no "created" timestamp in unix, so all the timestamps get updated when file content is modified.  You can list an AFL queue directory in timestamp order and see that the IDs are not always sequential even though the IDs are the order in which the queue inputs were created.

**Comment by mboehme** [comment]
For AFL and LibFuzzer, it should be possible to add a time stamp to the file name upon creation.

**Comment by vanhauser-thc** [comment]
> Please correct me if I'm wrong, but neither file time stamps nor hard links will provide accurate queue history. With the snapshot mechanism they might provide more accurate information like @lszekeres mentions?
> 
>     * hard links will preserve deleted files, but will not prevent the metadata from being modified (timestamps).
> 
>     * AFL (and most variants) often trims an input when it starts fuzzing a new entry from the queue which modifies the timestamps.  Unfortunately there's no "created" timestamp in unix, so all the timestamps get updated when file content is modified.  You can list an AFL queue directory in timestamp order and see that the IDs are not always sequential even though the IDs are the order in which the queue inputs were created.

I wanted to rebuke this as afl documents the discovery time in the filename, looked, but it is only afl++ doing this ;)
I must have added this long time ago and forgotten ...
so yeah: afl variants trim a new queue entry the first time it is selected, and this can be much later than discovered, changing it's file time. afl++ however writes the time in the filename: `id:000003,src:000002,time:1153,op:flip1,pos:1,+cov`

**Comment by vanhauser-thc** [comment]
great idea but not working with libfuzzer :(
