### ISSUE TITLE
Confidence Intervals in plots. 

### ISSUE THREAD

**Issue by eqv** [google/fuzzbench#716]
It seems as if the CI for the coverage growth plot is given in SD with an implicit normality assumption. In my experience the CI given by this is MUCH smaller than the actual CI given by the percentiles of the experiments. As a consequence, It often looks like fuzzers are significantly different even though their real CI are strongly overlapping. It might be worth considering changing this default.

**Comment by lszekeres** [comment]
Thanks @eqv for raising this!

The CI bar of the plot is is not given in SD, but [uses](https://github.com/google/fuzzbench/blob/master/analysis/plotting.py#L141) seaborn's default, which is computed from the percentiles, with this function: 

https://github.com/mwaskom/seaborn/blob/4dd57d63e23e4628d8b7f41cdefdf64f7fefcf74/seaborn/utils.py#L371

Do you think we should use something else? 

(Note that for statistical significance we have dedicated plots in the report, which are independent from the coverage growth plot. The coverage plot shouldn't be used to estimate what is stat. significantly different. )

**Comment by eqv** [comment]
Oh, I need to investigate this. The plots don't look like they were generated from percentiles. For example, the lower band should be monotonous (as each individual line is monotonous). However in plots like this it doesn't seem to be the case (look at the entropic plot around 2h).
https://camo.githubusercontent.com/806192cfe7e3bf69b171702be4e857231d639020/68747470733a2f2f73746f726167652e676f6f676c65617069732e636f6d2f66757a7a65722d746573742d73756974652d7075626c69632f6578656374696d652d7265706f72742f6c636d732d323031372d30332d32315f636f7665726167655f67726f7774682e737667

**Comment by eqv** [comment]
It seems you are right. https://github.com/mwaskom/seaborn/blob/0534e48f9db6bb982405c2522e65a408db465938/seaborn/relational.py#L390

The ci is computed by taking the percentiles from a bootstraped sample with n=1000. That's significantly better than SD based methods. But given the highly multimodal distribution of fuzzing runs I'm not sure if this only causes some weird artifacts or actually threatens the validity of the CI generated. While I don't really see any reason why it should cause serious problems, statistics are complicated.

I think this issue can be closed.
