### ISSUE TITLE
Interpretation of the FuzzBench Reports

### ISSUE THREAD

**Issue by mboehme** [google/fuzzbench#717]
The available fuzzer configurations and the results might be confusing for someone who looks at a random FuzzBench report for the first time. To avoid misinterpretation of the results, maybe there could be
1. a description of the intent of the evaluation and/or an explanation of the evaluated fuzzer configurations, and
2. a distinction between "master/official/representative" and "developer" evaluations and fuzzer variants.

**Comment by jonathanmetzman** [comment]
I think I agree with this overall. 1 seems easy to do, we should probably link to some place in the docs where we explain what the report is and provide necessary caveats. I'm having a hard time imagining what 2 looks like in practice though. Maybe people can tag fuzzers as "official" or not and that tag can make its way into reports. On some level though I think adding this functionality might not be the highest priority.

**Comment by mboehme** [comment]
What about naming fuzzer configurations accordingly?

**Comment by jonathanmetzman** [comment]
Ah. So for example, if one of the fuzzbench devs integrates ankou, we would name the fuzzer "ankou_experimental"? If this isn't what you have in mind could you provide a specific example?

**Comment by mboehme** [comment]
Yes, for instance. There was a discussion on Twitter where aflplusplus_optimal (which is highly overfitted to the benchmark just to represent the best version of AFL++, and @vanhauser-thc uses more as a reference to find good "mainline" AFL++ default settings) was misunderstood as the mainline AFL++ version.

**Comment by vanhauser-thc** [comment]
this also happened because the aflplusplus instance was not in the report. as I previously stated (months ago), both should be in there, aflplusplus and aflplusplus_optimal for fairness.

**Comment by lszekeres** [comment]
- for 1) we could introduce a `description.txt` in every fuzzer directory that'd describe the config and include that in the report
- for 2) we've been discussing having a list of the "official" fuzzers (that'd be included by default in the "official" reports) in a file, but we could do this too with having special files in the fuzzer dirs (e.g. just leaving an empty `.experimental` file or something)

**Comment by inferno-chromium** [comment]
for 2), we have official list in https://github.com/google/fuzzbench/blob/master/service/core-fuzzers.yaml

**Comment by lszekeres** [comment]
Nice! For 1) we could use that list to put "experimental" reports under say `fuzzbench.com/reports/experimental`

For 2, @vanhauser-thc, would you mind adding a super short `description.md` under the `fuzzer/aflplusplus_*` dirs? 
(Feel free to use markdown to include links and such) 
I can try to describe the rest of them.

**Comment by vanhauser-thc** [comment]
> For 2, @vanhauser-thc, would you mind adding a super short `description.md` under the `fuzzer/aflplusplus_*` dirs?
> (Feel free to use markdown to include links and such)
> I can try to describe the rest of them.

sure I will add that in the next push.
do you want to also for temporary variants that are just there for a single test?

**Comment by lszekeres** [comment]
> sure I will add that in the next push.

Thanks!

> do you want to also for temporary variants that are just there for a single test?

Yes, the goal is to not leave anything unexplained in any report :) thanks!

**Comment by jonathanmetzman** [comment]
It might also help to hyperlink fuzzer.py in each report.

**Comment by mboehme** [comment]
You could mark unsupported fuzzers.

**Comment by vanhauser-thc** [comment]
I put a description.md with a detailed description. for future temporary variants I will keep it shorter though :)

**Comment by lszekeres** [comment]
> For 1) we could use that list to put "experimental" reports under say `fuzzbench.com/reports/experimental`

Filed https://github.com/google/fuzzbench/issues/773 for this.

> You could mark fuzzers that do not support a particular benchmark (explaining an unusually low rank) -- but (probably needing a separate Issue) I actually think that fuzzers should be able to "register" for certain _categories_ of benchmarks (e.g., only those that take structured file formats), but not specific benchmarks. Fuzzers would only be evaluated within their specific categories.
> 
> [Edit: Whoops, wrong button.]

Filed https://github.com/google/fuzzbench/issues/774 for this, thanks! 

> I put a description.md with a detailed description. for future temporary variants I will keep it shorter though :)

Thanks a lot!
