### ISSUE TITLE
Is FuzzBench reporting edge or region coverage?

### ISSUE THREAD

**Issue by murx-** [google/fuzzbench#718]
I have a question regarding the reports from FuzzBench. Is FuzzBench actually measuring the edge coverage? At some point you switched from SanCov to Source-based Code Coverage. The latter has no edge coverage as far as I can tell. The difference is also [mentioned](https://github.com/google/fuzzbench/pull/564#issuecomment-663359743) in the discussion of the [PR that introduced the change from SanCov to source-based coverage](https://github.com/google/fuzzbench/pull/564). Skimming through the code I did not find where you are transforming the region coverage to edge coverage, did I miss something or are the labels not yet updated as the comment is suggesting it?

**Comment by inferno-chromium** [comment]
It is reporting region coverage, and yes the graph y-axis need to be fixed.

**Comment by inferno-chromium** [comment]
Fixed with https://github.com/google/fuzzbench/pull/714
