### ISSUE TITLE
Unique coverage plot improvements - improve readability with just unique cov number, add ranking, etc.

### ISSUE THREAD

**Issue by vanhauser-thc** [google/fuzzbench#719]
I really like the "Unique coverage plots" I noticed for the first time in https://www.fuzzbench.com/reports/2020-09-07/index.html

could we have a 3rd rank listing on the top for these? I think there would still be space or one :) but not sure if this should be based on rank or % or total.

For the bars in the individual benchmarks, the "unique" bar is usually so small that there is no color to see and some numbers are difficult to make out at least on my screen e.g.:
https://www.fuzzbench.com/reports/2020-09-07/index.html#ranking-by-unique-regions-covered-1 (not sure this link works, it is the unique cov graph of curl)
Not sure what would be better, maybe only showing the unqiues in the graph and not the total coverage too?

**Comment by jonathanmetzman** [comment]
>I really like the "Unique coverage plots" I noticed for the first time in https://www.fuzzbench.com/reports/2020-09-07/index.html

Glad you like it.

>could we have a 3rd rank listing on the top for these?

@lszekeres I think you had some objections to this WDYT? My main concern is while this ranking would reveal useful data about the fuzzers, it is a much worse way of evaluating "which fuzzers are best" than the other aggregate rankings. Thus it could be confusing to people not so familiar with the project.

> but not sure if this should be based on rank or % or total.

What do you think of ranking by # of non-normalized unique edges/regions?

>For the bars in the individual benchmarks, the "unique" bar is usually so small that there is no color to see and some numbers are difficult to make out at least on my screen e.g.:
>https://www.fuzzbench.com/reports/2020-09-07/index.html#ranking-by-unique-regions-covered-1 (not sure this link works, it is the unique cov graph of curl)
>Not sure what would be better, maybe only showing the unqiues in the graph and not the total coverage too?

It is rather hard to see this. i'm not sure what's the best solution here though either. I think it's probably only graphing the unique edges and leaving out total as you say.

**Comment by vanhauser-thc** [comment]
> > could we have a 3rd rank listing on the top for these?
> 
> @lszekeres I think you had some objections to this WDYT? My main concern is while this ranking would reveal useful data about the fuzzers, it is a much worse way of evaluating "which fuzzers are best" than the other aggregate rankings. Thus it could be confusing to people not so familiar with the project.

I think this is true. How about an extra table below the ranking then?

> > but not sure if this should be based on rank or % or total.
> 
> What do you think of ranking by # of non-normalized unique edges/regions?

I am not sure I understand what this mean.
No wrong, I do not understand at all what this exactly means :)

**Comment by lszekeres** [comment]
> > @lszekeres I think you had some objections to this WDYT? My main concern is while this ranking would reveal useful data about the fuzzers, it is a much worse way of evaluating "which fuzzers are best" than the other aggregate rankings. Thus it could be confusing to people not so familiar with the project.
> 
> I think this is true. How about an extra table below the ranking then?

What would you like to see in the table?

**Comment by lszekeres** [comment]
> It is rather hard to see this. i'm not sure what's the best solution here though either. I think it's probably only graphing the unique edges and leaving out total as you say.

I think that context, ie the total number of edges, is very important there, otherwise there's not way to know if say 463 unique edges is actually a lot or a little, whether it matters or not. Therefore, I'd def keep the total.

> > For the bars in the individual benchmarks, the "unique" bar is usually so small that there is no color to see and some numbers are difficult to make out at least on my screen 

Yes, that is what I'd like you to see there: nothing -- meaning that practically no fuzzer covers non-negligible amount of code that wouldn't be covered by the other fuzzers. 

Wdyt?

**Comment by jonathanmetzman** [comment]
> I am not sure I understand what this mean.
> No wrong, I do not understand at all what this exactly means :)

Heh, it was lacking context so it makes sense you don't understand.
basically, you suggested a 3rd ranking, but were unsure what it would look like (do you average the rank according to unique cov on each benchmark? Do you do something like average normalized score). I was suggesting that this 3rd ranking rank by total number of unique edges covered without any normalization (e.g. AFL has 5 unique on curl, 2 unique on bloaty, AFL++ 8 unique on curl 1 unique on bloaty, therefore the total unique edges is 7 for AFL 9 for AFL++ so AFL++ ranks higher).
The exact method isn't so important for now.

There's one problem with "unique" coverage though (that the pairwise table doesn't have). It penalizes fuzzers like AFL or AFL++ that have a lot of variants. Honggfuzz is advantaged here because there is only 1 fuzzer in the honggfuzz family in fuzzbench. But say there are some edges that only fuzzers in the AFL family will find, these wont be unique because not only will AFL find them, AFL++ will probably find them (as might mopt and fairfuzz etc).

**Comment by vanhauser-thc** [comment]
> Yes, that is what I'd like you to see there: nothing -- meaning that that fuzzer covers no or negligible amount of code that wouldn't be covered by the other fuzzers.

but that makes the table pointless right? there are differences and the differences should be readable, otherwise scratch the table :)

> > I am not sure I understand what this mean.
> > No wrong, I do not understand at all what this exactly means :)
> 
> Heh, it was lacking context so it makes sense you don't understand.

@lszekeres that is what I would like to see in the table below:
I think something like the first table is the best.
So total unique edges found in curl is 100, and honggfuzz found 50, afl++ found 20, entropic 20, afl 10 and so hongfuzz gets 50%, AFL 10% and then the average is generated over the number of benchmarks.

> There's one problem with "unique" coverage though (that the pairwise table doesn't have). It penalizes fuzzers like AFL or AFL++ that have a lot of variants. Honggfuzz is advantaged here because there is only 1 fuzzer in the honggfuzz family in fuzzbench. But say there are some edges that only fuzzers in the AFL family will find, these wont be unique because not only will AFL find them, AFL++ will probably find them (as might mopt and fairfuzz etc). Same problem exists with libFuzzer and entropic.

that is an issue yes. that also affects libfuzzer + entropic.
how about that for the assessment the other variants are excluded in the analysis?
so libfuzzer is compared with the uniqueness to all fuzzers except entropic etc?
and hongfuzz / hongguzz_qemu, aflplusplus/aflplusplus_optimal/aflplusplus_qemu, ...
honggfuzz has already an advantage here as all afl variants share the mutations to 100% (except Mopt), but honggfuzz has a unique mutator :)

**Comment by lszekeres** [comment]
> > Yes, that is what I'd like you to see there: nothing -- meaning that that fuzzer covers no or negligible amount of code that wouldn't be covered by the other fuzzers.
> 
> but that makes the table pointless right?

no, we probably don't explain that plot correctly and there's a misunderstanding. what eg.
https://www.fuzzbench.com/reports/2020-09-07/index.html#ranking-by-unique-regions-covered shows is actually something very interesting: namely that practically none of the fuzzers cover anything substantial that wasn't covered by some other fuzzer. 
this is important information!

> there are differences and the differences should be readable, otherwise scratch the table :)

not in this case: it doesn't matter that mopt has 47 unique edges and afl has 11 and aflfast has 1 (the internal colored bars). both of these numbers are practically nothing compared to 10000 (surrounding transparent bar) and they don't matter. again, the surrounding boxes represent the total coverage, while the internal colored bars are supposed to show the unique coverage. the fact that the colored bars are not visible means that the amounts (and the differences) are negligible. 

do you think it would help if we pointed this out explicitly in the plot description?

or do you think there's a better way to visualize this, or explain it in the plot description?

**Comment by vanhauser-thc** [comment]
> > > Yes, that is what I'd like you to see there: nothing -- meaning that that fuzzer covers no or negligible amount of code that wouldn't be covered by the other fuzzers.
> > 
> > 
> > but that makes the table pointless right?
> 
> no, we probably don't explain that plot correctly and there's a misunderstanding. what eg.
> https://www.fuzzbench.com/reports/2020-09-07/index.html#ranking-by-unique-regions-covered shows is actually something very interesting: namely that practically none of the fuzzers cover anything substantial that wasn't covered by some other fuzzer.
> this is important information!

I would not see it like that. If a fuzzer is able to cover a single block that no other fuzzer can, then for me that is interesting.

a single basic block might have an undiscovered bug.
a queue entry with that single block might make a different fuzzer able to find more following paths.

> > there are differences and the differences should be readable, otherwise scratch the table :)
> 
> not in this case: it doesn't matter that mopt has 47 unique edges and afl has 11 and aflfast has 1 (the internal colored bars). both of these numbers are practically nothing compared to 10000 (surrounding transparent bar) and they don't matter. again, the surrounding boxes represent the total coverage, while the internal colored bars are supposed to show the unique coverage. the fact that the colored bars are not visible means that the amounts (and the differences) are negligible.
> 
> do you think it would help if we pointed this out explicitly in the plot description?

as I wrote above, for me that is not the conclusion I would take from that.

**Comment by lszekeres** [comment]
> I would not see it like that. If a fuzzer is able to cover a single block that no other fuzzer can, then for me that is interesting.

right, i agree. the two conclusions are not exclusive.

i agree that having a single unique basic block is interesting too, and that the absolute numbers on the plot should be visible. (they more or less are i think, but not great indeed, will def. try to improve on the plots).

with my previous answer i was trying to address the question whether to keep the total numbers or not, and point out why we shouldn't remove the total number of edges as reference points from the bar plot. ie. without that context, if we had a plot with mopt showing 30 edges and afl showing 3 edges, that'd suggest that mopt is 10x "better" than afl, while in reality both 30 and 3 are negligible numbers, essentially noise, compared to say 500K total edges. does that make sense?

**Comment by vanhauser-thc** [comment]
I agree that "this fuzzer is better" would get to wrong conclusion.
how about maybe instead the boxed result that is comparing what is unique vs others fuzzers, but that over all benchmarks?
because the most interesting thing is maybe which fuzzers to combine, and that this box would show.

**Comment by lszekeres** [comment]
> I agree that "this fuzzer is better" would get to wrong conclusion.
> how about maybe instead the boxed result that is comparing what is unique vs others fuzzers, but that over all benchmarks?

Sorry, not sure i understand your suggestion, could you clarify?

> because the most interesting thing is maybe which fuzzers to combine, and that this box would show.

The "Pairwise unique coverage" plots (eg [report](https://www.fuzzbench.com/reports/2020-09-08/index.html
)) show exactly that. Ie it shows for each fuzzer X how many edges were covered by fuzzer X that were not covered by fuzzer Y. Do you find that sufficient?

I also made the numbers easier to read on both the ranking and pairwise plot in #732 and #731 (that will show up in upcoming reports). Let me know if you think more changes are needed on the plots.

**Comment by lszekeres** [comment]
> I was suggesting that this 3rd ranking rank by total number of unique edges covered without any normalization (e.g. AFL has 5 unique on curl, 2 unique on bloaty, AFL++ 8 unique on curl 1 unique on bloaty, therefore the total unique edges is 7 for AFL 9 for AFL++ so AFL++ ranks higher).

> I think something like the first table is the best.
> So total unique edges found in curl is 100, and honggfuzz found 50, afl++ found 20, entropic 20, afl 10 and so hongfuzz gets 50%, AFL 10% and then the average is generated over the number of benchmarks.

Re. adding a new aggregate / cross-benchmark ranking based on unique edges, I'd recommend against it.
I'm not sure if it was even meaningful to normalize and aggregate these per benchmark numbers. I'm also not sure if anyone would pick a fuzzer based on that aggregate ranking. One thing I'm fairly sure of is that i'd be very confusing. Given that the current rankings already confuse a lot of people, I'd rather not add even more confusion. 
(Note that this shouldn't prevent researchers to compute these aggregate numbers if they find it useful, but I'd not add it to the main reports that we publish.)
Wdyt?

**Comment by vanhauser-thc** [comment]
> > because the most interesting thing is maybe which fuzzers to combine, and that this box would show.
> 
> The "Pairwise unique coverage" plots (eg [report](https://www.fuzzbench.com/reports/2020-09-08/index.html)) show exactly that. Ie it shows for each fuzzer X how many edges were covered by fuzzer X that were not covered by fuzzer Y. Do you find that sufficient?

yes that box made over all benchmark (so one box with the data from the 21 benchmamrks) under the two summary table on the top - I think this would be the most helpful for both fuzzer users and fuzzer developers.
(plus some text what that box means).
I agree that any other summary of that data  is not that helpful. I first thought it would, but no :)

**Comment by lszekeres** [comment]
> > > because the most interesting thing is maybe which fuzzers to combine, and that this box would show.
> > 
> > 
> > The "Pairwise unique coverage" plots (eg [report](https://www.fuzzbench.com/reports/2020-09-08/index.html)) show exactly that. Ie it shows for each fuzzer X how many edges were covered by fuzzer X that were not covered by fuzzer Y. Do you find that sufficient?
> 
> yes that box made over all benchmark (so one box with the data from the 21 benchmamrks) under the two summary table on the top - I think this would be the most helpful for both fuzzer users and fuzzer developers.
> (plus some text what that box means).
> I agree that any other summary of that data is not that helpful. I first thought it would, but no :)

You mean an aggregate/cross-benchmark version of the "Pairwise unique coverage" heatmap plot, right? That might be interesting. The question is how to normalize and compute the values for the fuzzer pairs in that matrix. One option I can think of is:
-  for each benchmark, and for each fuzzer pair (f1, f2), compute the percentage of the unique and combined coverage, 
   ie. val_{bench,f1,f2} = C(f1)\C(f2) / C(f1)UC(f2).
- then in the aggregate chart, for each fuzzer pair (f1, f2), take the average of the per-benchmark values
  ie. val_{f1,f2} = AVG_{bench in all benchmarks}(val_{benc,f1,f2})

I'm still not completely sure how useful this would. It will show higher percentages for fuzzers that reach higher coverage in general, so it's not clear if the numbers computed like this could be used to figure out which fuzzers are best to combine with each other.

Wdyt?

**Comment by vanhauser-thc** [comment]
I am also not sure if it will be useful. I am just guessing that it could be.
to see which fuzzers are complementing each other is a very good thing. if that aggregated heatmap will be able to show this? I dont know, I hope so though :) We won't know until we have a real example to look at I guess

**Comment by lszekeres** [comment]
> I am also not sure if it will be useful. I am just guessing that it could be.
> to see which fuzzers are complementing each other is a very good thing. if that aggregated heatmap will be able to show this? I dont know, I hope so though :) We won't know until we have a real example to look at I guess

Sounds good! I created a tracking issue for this in https://github.com/google/fuzzbench/issues/741.

With the readability issues fixed in #732, #731, can this one be closed?
