### ISSUE TITLE
Some preemptible experiments like 09-10, 09-11 take longer, seem to be stuck in measuring loops.

### ISSUE THREAD

**Issue by inferno-chromium** [google/fuzzbench#735]

**Comment by jonathanmetzman** [comment]
It doesn't seem obvious to me why this would happen for preemptible experiments specifically.
Maybe instances are getting preempted but the scheduler isn't realizing so the measurer keeps trying to meaure them agian?
But I thought we fixed this issue.

**Comment by inferno-chromium** [comment]
> It doesn't seem obvious to me why this would happen for preemptible experiments specifically.
> Maybe instances are getting preempted but the scheduler isn't realizing so the measurer keeps trying to meaure them agian?
> But I thought we fixed this issue.

Will wait a day or two more, but this needs analysis, experiments aren't finishing in 3-4 days and this does not seem like coverage slowness, like logs said failed to find trial or something. this is just for tracking this important issue.

**Comment by inferno-chromium** [comment]
09-10 finished, but as i remember vm instances were gone way before that, unsure why measurer kept waiting.

**Comment by inferno-chromium** [comment]
Seems to be fixed with https://github.com/google/fuzzbench/pull/742, rest is slow measuring which we plan to address.
