### ISSUE TITLE
undefined reference to `__afl_area_ptr'

### ISSUE THREAD

**Issue by powerthe900** [google/fuzzbench#744]
I am compiling bitcoin core with afl-clang-fast and afl-clang-fast++.
Here is my code.
`./autogen.sh
CC=afl-clang-fast CCX=afl-clang-fast++ ./configure
make`

I get this error 
`secp256k1/.libs/libsecp256k1.a(libsecp256k1_la-secp256k1.o): In function `secp256k1_context_preallocated_size':
/home/redacted/bitcoin/src/secp256k1/src/secp256k1.c:87: undefined reference to `__afl_prev_loc'
/home/redacted/bitcoin/src/secp256k1/src/secp256k1.c:87: undefined reference to `__afl_area_ptr'
secp256k1/.libs/libsecp256k1.a(libsecp256k1_la-secp256k1.o): In function `secp256k1_default_illegal_callback_fn':
/home/redacted/bitcoin/src/secp256k1/src/secp256k1.c:45: undefined reference to `__afl_prev_loc'
secp256k1/.libs/libsecp256k1.a(libsecp256k1_la-secp256k1.o): In function `secp256k1_context_preallocated_clone_size':
/home/redacted/bitcoin/src/secp256k1/src/secp256k1.c:105: undefined reference to `__afl_prev_loc'
/home/redacted/bitcoin/src/secp256k1/src/secp256k1.c:105: undefined reference to `__afl_area_ptr'`

I did some research and found that someone had this issue with openssl earlier. The solution they offered was to put afl-llvm-rt.o in the cc_params. How do I do this?

**Comment by jonathanmetzman** [comment]
This isn't the AFL repo. Are you sure you are reporting this in the write place?

**Comment by powerthe900** [comment]
The previous similar issue was on this repository, so I decided to open the issue on here. Nonetheless, I found the issue: it was shared libraries. If you type --disable-shared, it compiles.
