### ISSUE TITLE
Creating JIRA tickets / Notifications to External Defect Tracking Systems

### ISSUE THREAD

**Issue by hpathuri** [google/fuzzbench#756]
How can we route the crashes for analysis to different team members? Where can we specify?

Where is the documentation to understand what is currently supported and how to use it?
Thanks

**Comment by inferno-chromium** [comment]
I think you meant to file an issue for ClusterFuzz here - https://github.com/google/clusterfuzz/issues. This repo is for FuzzBench and involves issues related to fuzzer benchmarking.

**Comment by hpathuri** [comment]
I should have been more clearer. The crashes from our fuzzers need to be sent to our internal development teams via some sort of bug tracking system like JIRA. Typically we need to create an internal ticket with Crash detials, test case, Binary from which the crash is reproduced. This will enable our debugging process. What hooks are available to integrate into our traiging workflow.

**Comment by inferno-chromium** [comment]
Again, did you file this issue in the right tracker. This one is for FuzzBench which does not seem related to your question.
For ClusterFuzz, you need to set these two values in your Config datastore table - https://github.com/google/clusterfuzz/blob/master/src/python/datastore/data_types.py#L730 and then define your jira issue tracker config in config directory (use type: jira), see config - https://github.com/google/clusterfuzz/blob/master/configs/test/issue_trackers/config.yaml#L23
