### ISSUE TITLE
Presubmit failure: AssertionError - "experiment/test_run_coverage.py"

### ISSUE THREAD

**Issue by BharathMonash** [google/fuzzbench#770]
I get this error every-time I  ```make presubmit``` 

```experiment/test_run_coverage.py::TestIntegrationRunCoverage::test_integration_do_coverage_run_crash FAILED```
```experiment/test_run_coverage.py::TestIntegrationRunCoverage::test_integration_do_coverage_run_no_crash FAILED```

```ERROR    root:logs.py:161 Coverage run failed. Extras: {'coverage_binary': '/home/bk**/fuzzbench/experiment/test_data/test_run_coverage/fuzz-target-clang-cov', 'output': "/home/bk**/fuzzbench/experiment/test_data/test_run_coverage/fuzz-target-clang-cov: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.22' not found```

Maybe this particular test should be skipped for now?

**Comment by inferno-chromium** [comment]
Can you try https://github.com/google/fuzzbench/pull/771 to see if this fixes it for you ? Do you run into any other test failures ?

**Comment by BharathMonash** [comment]
#772 - This fixes it, Thanks Abhishek. 
Sometimes I do run into rsync tests failures (running on gcloud).
