### ISSUE TITLE
make presubmit - lint failed ?

### ISSUE THREAD

**Issue by Anothonio** [google/fuzzbench#807]
Hi .

What is the meaning of lint failed?

There are some similar codes between my fuzzer codes and also I get some Trailing whitespace warnings / bad-indentation / duplicate-code and such which they are many . then how get rid of these while `make presubmit` ?

Thank you.
Anthonio

**Comment by inferno-chromium** [comment]
many of these you can fix automatically with `make format`. after that run 'make lint' to fix remaining stuff manually [not all lint error can be fixed automatically].

**Comment by Anothonio** [comment]
What is the meaning of these in fuzzbench? formatting the code is necessary? 

I mean all these are a **MUST** part for submitting a new integration ?

**Comment by inferno-chromium** [comment]
> @inferno-chromium
> What is the meaning of these in fuzzbench? formatting the code is necessary?
> 
> I mean all these are a **MUST** part for submitting a new integration ?

Yes submitting code that matches python code style and indents is a requirement for submitting new integration. This makes code readable and easily maintainable for future. if some pylint failures are not feasible to fix or intended, they could be disabled, but most of them need to be addressed.
