### ISSUE TITLE
[ Local benchmark probelm ] ERROR [1000] error waiting for container : unexpected EOF

### ISSUE THREAD

**Issue by Microsvuln** [google/fuzzbench#853]
Hey guys!

It's about 2-3 days that I'm failed at running fuzzbench benchmarks locally. before that, I had multiple successful experiences without any problem.

Here's the config file from my latest run :

```
# The number of trials of a fuzzer-benchmark pair.
trials: 3

# The amount of time in seconds that each trial is run for.
# 1 day = 24 * 60 * 60 = 86400
max_total_time: 15000

# The location of the docker registry.
# FIXME: Support custom docker registry.
# See https://github.com/google/fuzzbench/issues/777
docker_registry: gcr.io/fuzzbench

# The local experiment folder that will store most of the experiment data.
# Please use an absolute path.
experiment_filestore: /home/arash/test/experiment-data-whole-3h12


# The local report folder where HTML reports and summary data will be stored.
# Please use an absolute path.
report_filestore: /home/arash/test/report-data-whole-3h12

# Flag that indicates this is a local experiment.
local_experiment: true

```

I also attached the picture of the occurred error.

![photo_2020-10-21_03-59-07](https://user-images.githubusercontent.com/55649192/96659080-f4308a80-1352-11eb-9ebf-a2a7fd34d795.jpg)

Any workaround to this?

Thanks!

**Comment by inferno-chromium** [comment]
If it worked before, it is probably one of the recent patches
https://github.com/google/fuzzbench/pull/843
https://github.com/google/fuzzbench/pull/845
https://github.com/google/fuzzbench/pull/844

**Comment by inferno-chromium** [comment]
@Microsvuln - this does not reproduce for me on tip-of-tree trunk, i would say sync to head and try:

1. try on a new dir for experiment_filestore and report_filestore and see if it reproduces.
2. Try on short time and small set of fuzzers, like try with 2 fuzzers on 1 benchmark (with -b) and time like 900 secs and see if experiment ends gracefully and see if it reproduces.
3. if 1 and 2 dont work, let me know here like what fuzzers and benchmarks are running. local experiment is still geared for small workflows, so need an idea on the workload you are testing.

**Comment by inferno-chromium** [comment]
Also @Microsvuln this looks like a docker OOM issue, see https://github.com/moby/moby/issues/36324#issue-297527391

Are you using lot of trials, maybe try with smaller list of benchmarks / less number of trials ?

**Comment by Microsvuln** [comment]
@inferno-chromium Thanks, I just update the repo and the recent issue has been gone.

Now, I'm getting the Freespace error, I think I should do a revise and clean-up some junkies but I don't know if it's related to limitations of fuzzbench local run or not. should test and get back to you.

Thanks.

**Comment by inferno-chromium** [comment]
> @inferno-chromium Thanks, I just update the repo and the recent issue has been gone.
> 
> Now, I'm getting the Freespace error, I think I should do a revise and clean-up some junkies but I don't know if it's related to limitations of fuzzbench local run or not. should test and get back to you.
> 
> Thanks.

freespace should be a disk full issue, unrelated to fuzzbench.

You can cleanup using
```
#!/bin/bash

# Stop all containers
docker stop `docker ps -qa`

# Remove all containers
docker rm `docker ps -qa`

# Remove all images
docker rmi -f `docker images -qa `

# Remove all volumes
docker volume rm $(docker volume ls -q)
```

**Comment by Microsvuln** [comment]
@inferno-chromium 
I mean in the docker itself .

And what about using this ?

`docker system prune -a
`

Ran it and got the same error as appeared on the first comment .

Is there any documentation about limititations of fuzzbench local run ?

Thanks.

**Comment by jonathanmetzman** [comment]
Youre saying the dispatcher container runs out of space? I don't there is any diskspace limit on that container other than the one your machine has.

**Comment by inferno-chromium** [comment]
> @inferno-chromium
> I mean in the docker itself .
> 
> And what about using this ?
> 
> `docker system prune -a `
> 
> Ran it and got the same error as appeared on the first comment .
> 
> Is there any documentation about limititations of fuzzbench local run ?
> 
> Thanks.

Fuzzbench local experiment run is new and hasnt been tested at scale. if you can provide exact steps to reproduce a failure, we can look at fixing this. Usually OOMs and disk space issues are coming from lack of sufficient machine resources, so that is why we recommend doing a small set of fuzzer, benchmark and trials combination.

**Comment by Microsvuln** [comment]
@jonathanmetzman As I got all this while aflplusplus tried to download LLVM11 through a build process in Docker container, I though these might be related to the dispatcher container and that happened to me multiple times, but I think you're right although my machine space is 900GB (I'm wondering why this takes too much space ...).

> Fuzzbench local experiment run is new and hasnt been tested at scale. if you can provide exact steps to reproduce a failure, we can look at fixing this. Usually OOMs and disk space issues are coming from lack of sufficient machine resources, so that is why we recommend doing a small set of fuzzer, benchmark, and trials combination.

@inferno-chromium 
By now, I have a running benchmark, seems problem solved (However there were some small memory errors around as I can see, after this benchmark I'll look if I can catch these errors and send them here.

By now I have a running local benchmark with 8 fuzzers and about 18 targets, I'm also trying to make a new VM on the server with 3TB and start that local benchmark again to see what's going on. 

Indeed it seems that I should wait for those results for my fuzzer from your side as local experiments thing is new.

Thanks!
