### ISSUE TITLE
Disable ptrace_scope in fuzzbench dockers?

### ISSUE THREAD

**Issue by Microsvuln** [google/fuzzbench#855]
I want to disable ptrace scope in a fuzzbench docker container :

`echo 0| tee /proc/sys/kernel/yama/ptrace_scope`

But I received an error regarding the file system is read-only . Looked up the issue and found that if I can pass a --privileged switch to docker container run command then it's possible to do this but I don't know how to pass this so fuzzbench can run dockers with this switch.

Would you please help in this case or any predefined solution in fuzzbench for fuzzers that use intel pin to disable ptrace_scope?

Thanks.

**Comment by inferno-chromium** [comment]
$ git grep ptrace_scope
experiment/resources/dispatcher-startup-script-template.sh:echo 0 | sudo tee /proc/sys/kernel/yama/ptrace_scope
experiment/resources/runner-startup-script-template.sh:echo 0 > /proc/sys/kernel/yama/ptrace_scope

and privileged is already passed to runner (that runs fuzzer trials)
experiment/resources/runner-startup-script-template.sh:--privileged --cpus=1 --rm \
