### ISSUE TITLE
Support specifying which benchmarks to include in the report 

### ISSUE THREAD

**Issue by thuanpv** [google/fuzzbench#86]
The current set of benchmarks is diverse, which is great. However, since some fuzzers may not work very well with all types of input formats (e.g., context-free grammar inputs vs chunk-based inputs, binary inputs vs text inputs), it would be great if there is an option for us to choose which benchmarks should be included in the report. Of course, when we submit papers for review, we should explain why we ignore some benchmarks from our evaluation.

**Comment by inferno-chromium** [comment]
Should be a simple change to do, similar to https://github.com/google/fuzzbench/commit/2db4efc668f23a5dde4ae10de30998af19cf739e ? That will allow you to generate report for only a set of benchmarks.

**Comment by thuanpv** [comment]
Thanks, Abhishek.
Yes, perfect! A change imilar to 2db4efc should work even though the argument could be very long :) There are several benchmarks and their names are longer than the fuzzers' names.
