### ISSUE TITLE
CI times out as number of benchmarks scale, happening with Eclipser.

### ISSUE THREAD

**Issue by inferno-chromium** [google/fuzzbench#891]
Filed from https://github.com/google/fuzzbench/pull/868#issuecomment-717917112

**Comment by inferno-chromium** [comment]
Testing in https://github.com/google/fuzzbench/pull/890

**Comment by inferno-chromium** [comment]
ok https://github.com/google/fuzzbench/runs/1315705381?check_suite_focus=true is 6hr CI timeout
eclipser locally works fine on that benchmark
```
[eclipser] Run Eclipser with command: dotnet /Eclipser/build/Eclipser.dll -p /out/uninstrumented/cms_transform_fuzzer -s /out/corpus -o /out/corpus/eclipser_output --arg foo -f foo -v 2 --exectimeout 5000 -i /out/seeds
[run_afl_fuzz] Running command: ./afl-fuzz -i /out/seeds -o /out/corpus -m none -t 1000+ -S afl-worker -- /out/cms_transform_fuzzer 2147483647
[00:00:00:00] [*] Fuzz target : /out/uninstrumented/cms_transform_fuzzer
[00:00:00:00] [*] Total 1 initial seeds
[00:00:00:00] [*] No time limit given, run infinitely
[00:00:00:00] [*] Start fuzzing
[00:00:00:00] Fuzzing with:  ...800bytes... (0) (Right)
[00:00:00:05] Fuzzing with:  ...800bytes... (1) (Right)
[00:00:00:11] Fuzzing with:  ...800bytes... (2) (Right)
[00:00:00:16] Fuzzing with:  ...800bytes... (3) (Right)
INFO:root:Doing final sync.
```

**Comment by jonathanmetzman** [comment]
One option is to create a 3rd build job. What do you think?
We may have too many fuzzers to do this.

**Comment by inferno-chromium** [comment]
> One option is to create a 3rd build job. What do you think?
> We may have too many fuzzers to do this.

yes i think we can move bug based benchmarks into its own category ?

**Comment by jonathanmetzman** [comment]
I was thinking this too.

**Comment by inferno-chromium** [comment]
> I was thinking this too. I'll get on it.

so @Vaush left an issue with "type: bug" missing in benchmark.yaml on those new additions. but ci will fail as qemu fuzzers dont work with asan. i was thinking if should blocklist them in all bug based benchmarks or like not add sanitizer flags in those cases
