### ISSUE TITLE
matio benchmark fails with qemu fuzzers

### ISSUE THREAD

**Issue by inferno-chromium** [google/fuzzbench#894]
See https://github.com/google/fuzzbench/pull/886#issuecomment-717992496

@Vaush fyi, any thoughts here ?

**Comment by inferno-chromium** [comment]
> matio is a very problematic benchmark. Originally, in #666, it didn't work with aflplusplus and its variants, nor with qemu fuzzers, any of them (see [#666 (comment)](https://github.com/google/fuzzbench/pull/666#issuecomment-704359550)). After your fix, #800, by the checks it works on aflplusplus but doesn't work in almost any other fuzzer, such as afl or libfuzzer. I am honestly not sure about what's happening here, but I will look into it. I will open a draft PR to fix matio.

Can you disable/blocklist it on all the qemu benchmarks where it fails. this avoid dev confusion on CI.

**Comment by Vaush** [comment]
We did originally, I will blocklist them again while I try to fix it

**Comment by vanhauser-thc** [comment]
> matio is a very problematic benchmark. Originally, in **#666**, ...

very prophetic :D

**Comment by inferno-chromium** [comment]
fuzzers are blacklisted.
