### ISSUE TITLE
Eclipser was mishandling initial seed corpus 

### ISSUE THREAD

**Issue by jchoi2022** [google/fuzzbench#91]
Hi, thank you for open-sourcing a great project.

I investigated the results of Eclipser, and found that the coverage achieved by initial seed corpus was not correctly reflected in the final output. The issue has remained unrevealed since most of the experiments in Eclipser paper was performed with empty initial seed corpus.

The issue (along with some others ones) is fixed in commit b072f045324869 of https://github.com/SoftSec-KAIST/Eclipser. I will open a PR to replace the commit of Eclipser.

**Comment by inferno-chromium** [comment]
We will update/close this issue once a new report is generated, thanks for the fix.

**Comment by inferno-chromium** [comment]
Results are available in https://www.fuzzbench.com/reports/2020-03-11/index.html
