### ISSUE TITLE
Reporting stopped working

### ISSUE THREAD

**Issue by vanhauser-thc** [google/fuzzbench#932]
2020-11-02 and 2020-10-31-hlwn-long stopped updating the reports 12 hours ago (but are still running).

**Comment by inferno-chromium** [comment]
both have an issue with sql db. 2020-11-02 i cant find easy way to recover, so rerequesting it in https://github.com/google/fuzzbench/commit/5730ca407d7bebc6e62fde6bb83b791bf9489ecc

**Comment by vanhauser-thc** [comment]
@inferno-chromium you can cancel the new 2020-11-02 run, the 1/2 results plus the following test have enough information. No need to rerun it.

**Comment by inferno-chromium** [comment]
2020-11-02 is already stopped now. we restarted it in 2020-11-05, can let it finish.
