### ISSUE TITLE
Local run experiment error after upgrading to Python3.8 

### ISSUE THREAD

**Issue by Microsvuln** [google/fuzzbench#940]
Looking at the recent [commits](https://github.com/google/fuzzbench/commit/516e32ee07ec74998cfb6e06a4513c0301c0777f) I've considered that I should upgrade to python3.8 .

After installing python3.8 I'm getting the following error after running `make install-dependencies` :

```
arash@fuzzbench-scale1:~/new/fuzzbench$ make install-dependencies
Makefile:45: docker/generated.mk: No such file or directory
source .venv/bin/activate && PYTHONPATH=. python3 docker/generate_makefile.py docker/generated.mk
Traceback (most recent call last):
  File "docker/generate_makefile.py", line 19, in <module>
    from common import yaml_utils
  File "/home/arash/new/fuzzbench/common/yaml_utils.py", line 16, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'
Makefile:57: recipe for target 'docker/generated.mk' failed
make: *** [docker/generated.mk] Error 1
```

Tried to install with `pip3.8 install pyyaml` but seems it's already satisfied.

Looking for a solution .

Thanks.

**Comment by inferno-chromium** [comment]
Try deleting your old virtualenv using `rm -rf .venv` and then retry. Close issue if it works for you.

**Comment by Microsvuln** [comment]
@inferno-chromium 

Thanks, did this but still get the error :

First get `ModuleNotFoundError: No module named 'pybind11'`, installed it using `pip3.8 install pybind11` but same result :

```
 Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-5l88bibq/pytype/setup.py", line 24, in <module>
        from pybind11.setup_helpers import Pybind11Extension  # pylint: disable=g-import-not-at-top,wrong-import-position
    ModuleNotFoundError: No module named 'pybind11'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-5l88bibq/pytype/
Makefile:51: recipe for target '.venv/bin/activate' failed
make: *** [.venv/bin/activate] Error 1
arash@fuzzbench-scale1:~/new/fuzzbench$ pip3.8 install pybind11
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pybind11 in /home/arash/.local/lib/python3.8/site-packages (2.6.0)
arash@fuzzbench-scale1:~/new/fuzzbench$ make install-dependencies
Makefile:45: docker/generated.mk: No such file or directory
source .venv/bin/activate && PYTHONPATH=. python3 docker/generate_makefile.py docker/generated.mk
Traceback (most recent call last):
  File "docker/generate_makefile.py", line 19, in <module>
    from common import yaml_utils
  File "/home/arash/new/fuzzbench/common/yaml_utils.py", line 16, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'
Makefile:57: recipe for target 'docker/generated.mk' failed
make: *** [docker/generated.mk] Error 1
arash@fuzzbench-scale1:~/new/fuzzbench$ 
```

**Comment by inferno-chromium** [comment]
something is up with your python install, works fine for me

```
$ pip3.8 install pybind11
Collecting pybind11
  Downloading https://files.pythonhosted.org/packages/92/a5/796ccb611a92cbdf1f6eaa9b2ec9458d5784a7b909efdf8e8afaa3861783/pybind11-2.6.0-py2.py3-none-any.whl (187kB)
     |\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588| 194kB 9.7MB/s 
Installing collected packages: pybind11
Successfully installed pybind11-2.6.0
```

is your pip up to date, try `pip3 install --upgrade pip`.

**Comment by Microsvuln** [comment]
If you look at the previous log it also runs without problem for me :

```
arash@fuzzbench-scale1:~/new/fuzzbench$ pip3.8 install pybind11
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pybind11 in /home/arash/.local/lib/python3.8/site-packages (2.6.0)
```


But still get the same for yaml :

```
arash@fuzzbench-scale1:~/new/fuzzbench$ make install-dependencies
Makefile:45: docker/generated.mk: No such file or directory
source .venv/bin/activate && PYTHONPATH=. python3 docker/generate_makefile.py docker/generated.mk
Traceback (most recent call last):
  File "docker/generate_makefile.py", line 19, in <module>
    from common import yaml_utils
  File "/home/arash/new/fuzzbench/common/yaml_utils.py", line 16, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'
Makefile:57: recipe for target 'docker/generated.mk' failed
make: *** [docker/generated.mk] Error 1
arash@fuzzbench-scale1:~/new/fuzzbench$ 
```

`is your pip up to date, try pip3 install --upgrade pip.
`
Tried this, no problem :

arash@fuzzbench-scale1:~/new/fuzzbench$ pip3 install --upgrade pip
Defaulting to user installation because normal site-packages is not writeable
Requirement already up-to-date: pip in /usr/local/lib/python3.8/dist-packages (20.2.4)

But the problem still exists.

**Comment by inferno-chromium** [comment]
can you try this
```source .venv/bin/activate
pip install requirements.txt```
and then run the command, does that succeed ? you need to run all commands inside the virtualenv shell.

**Comment by Microsvuln** [comment]
`pip install requirements.txt ` raised error but `pip -r install requirements.txt` works fine!

Solved!

Thanks!

**Comment by Microsvuln** [comment]
@inferno-chromium 

I tested and involved this precisely over hours ago, just wanted to add this note:

Those who have problems with pybind11 or yaml or other python3.8 dependencies, make sure you will run the following command :

`pip install --upgrade setuptools`

This command along with what @inferno-chromium mentioned in the above as :

```
source .venv/bin/activate
pip install -r requirements.txt
```

Can save your time and solve this problem finally.

**Comment by RosenZhu** [comment]
@Microsvuln @inferno-chromium Hi all, I tried 

```
source .venv/bin/activate
pip install -r requirements.txt
```
But an error happens:
```
The conflict is caused by:
    The user requested google-auth==1.21.2
    clusterfuzz 0.0.1a0 depends on google-auth>=1.22.1
```
What should I do?

**Comment by inferno-chromium** [comment]
> @Microsvuln @inferno-chromium Hi all, I tried
> 
> ```
> source .venv/bin/activate
> pip install -r requirements.txt
> ```
> 
> But an error happens:
> 
> ```
> The conflict is caused by:
>     The user requested google-auth==1.21.2
>     clusterfuzz 0.0.1a0 depends on google-auth>=1.22.1
> ```
> 
> What should I do? (I also have the problem about pybind11 and yaml)

We can upgrade the versions after the holidays, but it shouldn't block anything, "make install-dependencies" still finishes. Use "make install-dependencies", that makes sure you use python3. anything >= python3.8 should work.

**Comment by RosenZhu** [comment]
> Use "make install-dependencies", that makes sure you use python3. anything >= python3.8 should work.

When I used "make install-dependencies", I got the errors that @Microsvuln mentioned in this issue (no module named "pybind11" or "yaml"). So I tried "pip install -r requirements.txt", and then I got version conflict as I mentioned.

**Comment by RosenZhu** [comment]
I notice that when using "make install-dependencies", requirements are also installed:
```
Makefile:45: docker/generated.mk: No such file or directory
python3.8 -m venv .venv || python3 -m venv .venv
source .venv/bin/activate && python3 -m pip install -r requirements.txt
```

**Comment by inferno-chromium** [comment]
> I notice that when using "make install-dependencies", requirements are also installed:
> 
> ```
> Makefile:45: docker/generated.mk: No such file or directory
> python3.8 -m venv .venv || python3 -m venv .venv
> source .venv/bin/activate && python3 -m pip install -r requirements.txt
> ```
> 
> Should I just edit the requirements.txt?

yes just bump up google-auth version manually in requirements and see if it works. if yes, can upload a PR.

Also try with
python3 -m pip install -r requirements.txt
Which python version are you using, best to start a new bug with these issues.

**Comment by RosenZhu** [comment]
Thanks! It works! 
1. I change the version as required in requirements.txt
2. `source .venv/bin/activate'
3. `python3 -m pip install -r requirements.txt`
4. `make install-dependencies`
