### ISSUE TITLE
Build logs not uploaded for coverage build failures

### ISSUE THREAD

**Issue by jonathanmetzman** [google/fuzzbench#944]
Uploading these is helpful for determining when something is horribly wrong with building.

**Comment by inferno-chromium** [comment]
I checked the code (https://github.com/google/fuzzbench/blob/master/experiment/build/gcb_build.py#L70) and data folder, i do see 
https://storage.googleapis.com/fuzzbench-data/2020-11-08/build-logs/benchmark-bloaty_fuzz_target-coverage.txt
so we do seem to capture them.

**Comment by inferno-chromium** [comment]
Closing since we already do this, @jonathanmetzman reopen if incorrect.

**Comment by jonathanmetzman** [comment]
Reopening this since I have a reason to think this isn't actually working as intended.
Will share details offline.

**Comment by jonathanmetzman** [comment]
> I checked the code (https://github.com/google/fuzzbench/blob/master/experiment/build/gcb_build.py#L70) and data folder, i do see
> https://storage.googleapis.com/fuzzbench-data/2020-11-08/build-logs/benchmark-bloaty_fuzz_target-coverage.txt
> so we do seem to capture them.

Right that is a build success.
I think we aren't uploading failures though.
[On this line we build](https://github.com/google/fuzzbench/blob/master/experiment/build/gcb_build.py#L100) and on [the next line the logs are uploaded](https://github.com/google/fuzzbench/blob/master/experiment/build/gcb_build.py#L104).
But when there's an exception we won't get to the next line.
I'm pretty sure there is an exception, see [here](https://github.com/google/fuzzbench/blob/master/common/new_process.py#L122) for how new_process.execute handles failures.
As you can see [here](https://github.com/google/fuzzbench/blob/4eec33d326b73a46f1e1875bb64edc267eb2ec8a/experiment/build/builder.py#L87) we expect build failures to exception.
